// Code generated by ent, DO NOT EDIT.

package proxytrafficlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the proxytrafficlog type in the database.
	Label = "proxy_traffic_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRentalID holds the string denoting the rental_id field in the database.
	FieldRentalID = "rental_id"
	// FieldDeltaBytes holds the string denoting the delta_bytes field in the database.
	FieldDeltaBytes = "delta_bytes"
	// FieldOperatorID holds the string denoting the operator_id field in the database.
	FieldOperatorID = "operator_id"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// EdgeRental holds the string denoting the rental edge name in mutations.
	EdgeRental = "rental"
	// EdgeOperator holds the string denoting the operator edge name in mutations.
	EdgeOperator = "operator"
	// Table holds the table name of the proxytrafficlog in the database.
	Table = "proxy_traffic_logs"
	// RentalTable is the table that holds the rental relation/edge.
	RentalTable = "proxy_traffic_logs"
	// RentalInverseTable is the table name for the ProxyRental entity.
	// It exists in this package in order to avoid circular dependency with the "proxyrental" package.
	RentalInverseTable = "proxy_rentals"
	// RentalColumn is the table column denoting the rental relation/edge.
	RentalColumn = "rental_id"
	// OperatorTable is the table that holds the operator relation/edge.
	OperatorTable = "proxy_traffic_logs"
	// OperatorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OperatorInverseTable = "users"
	// OperatorColumn is the table column denoting the operator relation/edge.
	OperatorColumn = "operator_id"
)

// Columns holds all SQL columns for proxytrafficlog fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRentalID,
	FieldDeltaBytes,
	FieldOperatorID,
	FieldNote,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DeltaBytesValidator is a validator for the "delta_bytes" field. It is called by the builders before save.
	DeltaBytesValidator func(int64) error
	// DefaultNote holds the default value on creation for the "note" field.
	DefaultNote string
)

// OrderOption defines the ordering options for the ProxyTrafficLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRentalID orders the results by the rental_id field.
func ByRentalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRentalID, opts...).ToFunc()
}

// ByDeltaBytes orders the results by the delta_bytes field.
func ByDeltaBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeltaBytes, opts...).ToFunc()
}

// ByOperatorID orders the results by the operator_id field.
func ByOperatorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperatorID, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByRentalField orders the results by rental field.
func ByRentalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRentalStep(), sql.OrderByField(field, opts...))
	}
}

// ByOperatorField orders the results by operator field.
func ByOperatorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOperatorStep(), sql.OrderByField(field, opts...))
	}
}
func newRentalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RentalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RentalTable, RentalColumn),
	)
}
func newOperatorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OperatorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OperatorTable, OperatorColumn),
	)
}
