// Code generated by ent, DO NOT EDIT.

package proxytrafficlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/meitianwang/fast-frame/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// RentalID applies equality check predicate on the "rental_id" field. It's identical to RentalIDEQ.
func RentalID(v int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldEQ(FieldRentalID, v))
}

// DeltaBytes applies equality check predicate on the "delta_bytes" field. It's identical to DeltaBytesEQ.
func DeltaBytes(v int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldEQ(FieldDeltaBytes, v))
}

// OperatorID applies equality check predicate on the "operator_id" field. It's identical to OperatorIDEQ.
func OperatorID(v int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldEQ(FieldOperatorID, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldEQ(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldLTE(FieldUpdatedAt, v))
}

// RentalIDEQ applies the EQ predicate on the "rental_id" field.
func RentalIDEQ(v int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldEQ(FieldRentalID, v))
}

// RentalIDNEQ applies the NEQ predicate on the "rental_id" field.
func RentalIDNEQ(v int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldNEQ(FieldRentalID, v))
}

// RentalIDIn applies the In predicate on the "rental_id" field.
func RentalIDIn(vs ...int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldIn(FieldRentalID, vs...))
}

// RentalIDNotIn applies the NotIn predicate on the "rental_id" field.
func RentalIDNotIn(vs ...int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldNotIn(FieldRentalID, vs...))
}

// DeltaBytesEQ applies the EQ predicate on the "delta_bytes" field.
func DeltaBytesEQ(v int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldEQ(FieldDeltaBytes, v))
}

// DeltaBytesNEQ applies the NEQ predicate on the "delta_bytes" field.
func DeltaBytesNEQ(v int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldNEQ(FieldDeltaBytes, v))
}

// DeltaBytesIn applies the In predicate on the "delta_bytes" field.
func DeltaBytesIn(vs ...int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldIn(FieldDeltaBytes, vs...))
}

// DeltaBytesNotIn applies the NotIn predicate on the "delta_bytes" field.
func DeltaBytesNotIn(vs ...int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldNotIn(FieldDeltaBytes, vs...))
}

// DeltaBytesGT applies the GT predicate on the "delta_bytes" field.
func DeltaBytesGT(v int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldGT(FieldDeltaBytes, v))
}

// DeltaBytesGTE applies the GTE predicate on the "delta_bytes" field.
func DeltaBytesGTE(v int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldGTE(FieldDeltaBytes, v))
}

// DeltaBytesLT applies the LT predicate on the "delta_bytes" field.
func DeltaBytesLT(v int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldLT(FieldDeltaBytes, v))
}

// DeltaBytesLTE applies the LTE predicate on the "delta_bytes" field.
func DeltaBytesLTE(v int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldLTE(FieldDeltaBytes, v))
}

// OperatorIDEQ applies the EQ predicate on the "operator_id" field.
func OperatorIDEQ(v int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorIDNEQ applies the NEQ predicate on the "operator_id" field.
func OperatorIDNEQ(v int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldNEQ(FieldOperatorID, v))
}

// OperatorIDIn applies the In predicate on the "operator_id" field.
func OperatorIDIn(vs ...int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldIn(FieldOperatorID, vs...))
}

// OperatorIDNotIn applies the NotIn predicate on the "operator_id" field.
func OperatorIDNotIn(vs ...int64) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldNotIn(FieldOperatorID, vs...))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.FieldContainsFold(FieldNote, v))
}

// HasRental applies the HasEdge predicate on the "rental" edge.
func HasRental() predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RentalTable, RentalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRentalWith applies the HasEdge predicate on the "rental" edge with a given conditions (other predicates).
func HasRentalWith(preds ...predicate.ProxyRental) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(func(s *sql.Selector) {
		step := newRentalStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOperator applies the HasEdge predicate on the "operator" edge.
func HasOperator() predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OperatorTable, OperatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOperatorWith applies the HasEdge predicate on the "operator" edge with a given conditions (other predicates).
func HasOperatorWith(preds ...predicate.User) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(func(s *sql.Selector) {
		step := newOperatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProxyTrafficLog) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProxyTrafficLog) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProxyTrafficLog) predicate.ProxyTrafficLog {
	return predicate.ProxyTrafficLog(sql.NotPredicates(p))
}
