// Code generated by ent, DO NOT EDIT.

package proxycredential

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the proxycredential type in the database.
	Label = "proxy_credential"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRentalID holds the string denoting the rental_id field in the database.
	FieldRentalID = "rental_id"
	// FieldHTTPUsername holds the string denoting the http_username field in the database.
	FieldHTTPUsername = "http_username"
	// FieldHTTPPassword holds the string denoting the http_password field in the database.
	FieldHTTPPassword = "http_password"
	// FieldVlessUUID holds the string denoting the vless_uuid field in the database.
	FieldVlessUUID = "vless_uuid"
	// FieldVlessLink holds the string denoting the vless_link field in the database.
	FieldVlessLink = "vless_link"
	// EdgeRental holds the string denoting the rental edge name in mutations.
	EdgeRental = "rental"
	// Table holds the table name of the proxycredential in the database.
	Table = "proxy_credentials"
	// RentalTable is the table that holds the rental relation/edge.
	RentalTable = "proxy_credentials"
	// RentalInverseTable is the table name for the ProxyRental entity.
	// It exists in this package in order to avoid circular dependency with the "proxyrental" package.
	RentalInverseTable = "proxy_rentals"
	// RentalColumn is the table column denoting the rental relation/edge.
	RentalColumn = "rental_id"
)

// Columns holds all SQL columns for proxycredential fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRentalID,
	FieldHTTPUsername,
	FieldHTTPPassword,
	FieldVlessUUID,
	FieldVlessLink,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// HTTPUsernameValidator is a validator for the "http_username" field. It is called by the builders before save.
	HTTPUsernameValidator func(string) error
	// HTTPPasswordValidator is a validator for the "http_password" field. It is called by the builders before save.
	HTTPPasswordValidator func(string) error
	// VlessUUIDValidator is a validator for the "vless_uuid" field. It is called by the builders before save.
	VlessUUIDValidator func(string) error
	// VlessLinkValidator is a validator for the "vless_link" field. It is called by the builders before save.
	VlessLinkValidator func(string) error
)

// OrderOption defines the ordering options for the ProxyCredential queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRentalID orders the results by the rental_id field.
func ByRentalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRentalID, opts...).ToFunc()
}

// ByHTTPUsername orders the results by the http_username field.
func ByHTTPUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPUsername, opts...).ToFunc()
}

// ByHTTPPassword orders the results by the http_password field.
func ByHTTPPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPPassword, opts...).ToFunc()
}

// ByVlessUUID orders the results by the vless_uuid field.
func ByVlessUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVlessUUID, opts...).ToFunc()
}

// ByVlessLink orders the results by the vless_link field.
func ByVlessLink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVlessLink, opts...).ToFunc()
}

// ByRentalField orders the results by rental field.
func ByRentalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRentalStep(), sql.OrderByField(field, opts...))
	}
}
func newRentalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RentalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, RentalTable, RentalColumn),
	)
}
