// Code generated by ent, DO NOT EDIT.

package proxynode

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the proxynode type in the database.
	Label = "proxy_node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldIPAddress holds the string denoting the ip_address field in the database.
	FieldIPAddress = "ip_address"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldCountryCode holds the string denoting the country_code field in the database.
	FieldCountryCode = "country_code"
	// FieldCity holds the string denoting the city field in the database.
	FieldCity = "city"
	// FieldIsp holds the string denoting the isp field in the database.
	FieldIsp = "isp"
	// FieldHTTPPort holds the string denoting the http_port field in the database.
	FieldHTTPPort = "http_port"
	// FieldVlessPort holds the string denoting the vless_port field in the database.
	FieldVlessPort = "vless_port"
	// FieldVlessNetwork holds the string denoting the vless_network field in the database.
	FieldVlessNetwork = "vless_network"
	// FieldVlessTLS holds the string denoting the vless_tls field in the database.
	FieldVlessTLS = "vless_tls"
	// FieldVlessSni holds the string denoting the vless_sni field in the database.
	FieldVlessSni = "vless_sni"
	// FieldVlessWsPath holds the string denoting the vless_ws_path field in the database.
	FieldVlessWsPath = "vless_ws_path"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeRentals holds the string denoting the rentals edge name in mutations.
	EdgeRentals = "rentals"
	// Table holds the table name of the proxynode in the database.
	Table = "proxy_nodes"
	// RentalsTable is the table that holds the rentals relation/edge.
	RentalsTable = "proxy_rentals"
	// RentalsInverseTable is the table name for the ProxyRental entity.
	// It exists in this package in order to avoid circular dependency with the "proxyrental" package.
	RentalsInverseTable = "proxy_rentals"
	// RentalsColumn is the table column denoting the rentals relation/edge.
	RentalsColumn = "node_id"
)

// Columns holds all SQL columns for proxynode fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldIPAddress,
	FieldCountry,
	FieldCountryCode,
	FieldCity,
	FieldIsp,
	FieldHTTPPort,
	FieldVlessPort,
	FieldVlessNetwork,
	FieldVlessTLS,
	FieldVlessSni,
	FieldVlessWsPath,
	FieldTags,
	FieldStatus,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/meitianwang/fast-frame/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	IPAddressValidator func(string) error
	// DefaultCountry holds the default value on creation for the "country" field.
	DefaultCountry string
	// CountryValidator is a validator for the "country" field. It is called by the builders before save.
	CountryValidator func(string) error
	// DefaultCountryCode holds the default value on creation for the "country_code" field.
	DefaultCountryCode string
	// CountryCodeValidator is a validator for the "country_code" field. It is called by the builders before save.
	CountryCodeValidator func(string) error
	// DefaultCity holds the default value on creation for the "city" field.
	DefaultCity string
	// CityValidator is a validator for the "city" field. It is called by the builders before save.
	CityValidator func(string) error
	// DefaultIsp holds the default value on creation for the "isp" field.
	DefaultIsp string
	// IspValidator is a validator for the "isp" field. It is called by the builders before save.
	IspValidator func(string) error
	// DefaultHTTPPort holds the default value on creation for the "http_port" field.
	DefaultHTTPPort int
	// DefaultVlessPort holds the default value on creation for the "vless_port" field.
	DefaultVlessPort int
	// DefaultVlessNetwork holds the default value on creation for the "vless_network" field.
	DefaultVlessNetwork string
	// VlessNetworkValidator is a validator for the "vless_network" field. It is called by the builders before save.
	VlessNetworkValidator func(string) error
	// DefaultVlessTLS holds the default value on creation for the "vless_tls" field.
	DefaultVlessTLS bool
	// DefaultVlessSni holds the default value on creation for the "vless_sni" field.
	DefaultVlessSni string
	// VlessSniValidator is a validator for the "vless_sni" field. It is called by the builders before save.
	VlessSniValidator func(string) error
	// DefaultVlessWsPath holds the default value on creation for the "vless_ws_path" field.
	DefaultVlessWsPath string
	// VlessWsPathValidator is a validator for the "vless_ws_path" field. It is called by the builders before save.
	VlessWsPathValidator func(string) error
	// DefaultTags holds the default value on creation for the "tags" field.
	DefaultTags []string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
)

// OrderOption defines the ordering options for the ProxyNode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByIPAddress orders the results by the ip_address field.
func ByIPAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIPAddress, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByCountryCode orders the results by the country_code field.
func ByCountryCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountryCode, opts...).ToFunc()
}

// ByCity orders the results by the city field.
func ByCity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCity, opts...).ToFunc()
}

// ByIsp orders the results by the isp field.
func ByIsp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsp, opts...).ToFunc()
}

// ByHTTPPort orders the results by the http_port field.
func ByHTTPPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPPort, opts...).ToFunc()
}

// ByVlessPort orders the results by the vless_port field.
func ByVlessPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVlessPort, opts...).ToFunc()
}

// ByVlessNetwork orders the results by the vless_network field.
func ByVlessNetwork(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVlessNetwork, opts...).ToFunc()
}

// ByVlessTLS orders the results by the vless_tls field.
func ByVlessTLS(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVlessTLS, opts...).ToFunc()
}

// ByVlessSni orders the results by the vless_sni field.
func ByVlessSni(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVlessSni, opts...).ToFunc()
}

// ByVlessWsPath orders the results by the vless_ws_path field.
func ByVlessWsPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVlessWsPath, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByRentalsCount orders the results by rentals count.
func ByRentalsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRentalsStep(), opts...)
	}
}

// ByRentals orders the results by rentals terms.
func ByRentals(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRentalsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRentalsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RentalsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RentalsTable, RentalsColumn),
	)
}
