// Code generated by ent, DO NOT EDIT.

package proxynode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/meitianwang/fast-frame/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldDeletedAt, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldIPAddress, v))
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldCountry, v))
}

// CountryCode applies equality check predicate on the "country_code" field. It's identical to CountryCodeEQ.
func CountryCode(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldCountryCode, v))
}

// City applies equality check predicate on the "city" field. It's identical to CityEQ.
func City(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldCity, v))
}

// Isp applies equality check predicate on the "isp" field. It's identical to IspEQ.
func Isp(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldIsp, v))
}

// HTTPPort applies equality check predicate on the "http_port" field. It's identical to HTTPPortEQ.
func HTTPPort(v int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldHTTPPort, v))
}

// VlessPort applies equality check predicate on the "vless_port" field. It's identical to VlessPortEQ.
func VlessPort(v int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldVlessPort, v))
}

// VlessNetwork applies equality check predicate on the "vless_network" field. It's identical to VlessNetworkEQ.
func VlessNetwork(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldVlessNetwork, v))
}

// VlessTLS applies equality check predicate on the "vless_tls" field. It's identical to VlessTLSEQ.
func VlessTLS(v bool) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldVlessTLS, v))
}

// VlessSni applies equality check predicate on the "vless_sni" field. It's identical to VlessSniEQ.
func VlessSni(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldVlessSni, v))
}

// VlessWsPath applies equality check predicate on the "vless_ws_path" field. It's identical to VlessWsPathEQ.
func VlessWsPath(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldVlessWsPath, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldStatus, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotNull(FieldDeletedAt))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContainsFold(FieldIPAddress, v))
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldCountry, v))
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldCountry, v))
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIn(FieldCountry, vs...))
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotIn(FieldCountry, vs...))
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGT(FieldCountry, v))
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGTE(FieldCountry, v))
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLT(FieldCountry, v))
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLTE(FieldCountry, v))
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContains(FieldCountry, v))
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasPrefix(FieldCountry, v))
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasSuffix(FieldCountry, v))
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEqualFold(FieldCountry, v))
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContainsFold(FieldCountry, v))
}

// CountryCodeEQ applies the EQ predicate on the "country_code" field.
func CountryCodeEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldCountryCode, v))
}

// CountryCodeNEQ applies the NEQ predicate on the "country_code" field.
func CountryCodeNEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldCountryCode, v))
}

// CountryCodeIn applies the In predicate on the "country_code" field.
func CountryCodeIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIn(FieldCountryCode, vs...))
}

// CountryCodeNotIn applies the NotIn predicate on the "country_code" field.
func CountryCodeNotIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotIn(FieldCountryCode, vs...))
}

// CountryCodeGT applies the GT predicate on the "country_code" field.
func CountryCodeGT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGT(FieldCountryCode, v))
}

// CountryCodeGTE applies the GTE predicate on the "country_code" field.
func CountryCodeGTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGTE(FieldCountryCode, v))
}

// CountryCodeLT applies the LT predicate on the "country_code" field.
func CountryCodeLT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLT(FieldCountryCode, v))
}

// CountryCodeLTE applies the LTE predicate on the "country_code" field.
func CountryCodeLTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLTE(FieldCountryCode, v))
}

// CountryCodeContains applies the Contains predicate on the "country_code" field.
func CountryCodeContains(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContains(FieldCountryCode, v))
}

// CountryCodeHasPrefix applies the HasPrefix predicate on the "country_code" field.
func CountryCodeHasPrefix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasPrefix(FieldCountryCode, v))
}

// CountryCodeHasSuffix applies the HasSuffix predicate on the "country_code" field.
func CountryCodeHasSuffix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasSuffix(FieldCountryCode, v))
}

// CountryCodeEqualFold applies the EqualFold predicate on the "country_code" field.
func CountryCodeEqualFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEqualFold(FieldCountryCode, v))
}

// CountryCodeContainsFold applies the ContainsFold predicate on the "country_code" field.
func CountryCodeContainsFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContainsFold(FieldCountryCode, v))
}

// CityEQ applies the EQ predicate on the "city" field.
func CityEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldCity, v))
}

// CityNEQ applies the NEQ predicate on the "city" field.
func CityNEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldCity, v))
}

// CityIn applies the In predicate on the "city" field.
func CityIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIn(FieldCity, vs...))
}

// CityNotIn applies the NotIn predicate on the "city" field.
func CityNotIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotIn(FieldCity, vs...))
}

// CityGT applies the GT predicate on the "city" field.
func CityGT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGT(FieldCity, v))
}

// CityGTE applies the GTE predicate on the "city" field.
func CityGTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGTE(FieldCity, v))
}

// CityLT applies the LT predicate on the "city" field.
func CityLT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLT(FieldCity, v))
}

// CityLTE applies the LTE predicate on the "city" field.
func CityLTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLTE(FieldCity, v))
}

// CityContains applies the Contains predicate on the "city" field.
func CityContains(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContains(FieldCity, v))
}

// CityHasPrefix applies the HasPrefix predicate on the "city" field.
func CityHasPrefix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasPrefix(FieldCity, v))
}

// CityHasSuffix applies the HasSuffix predicate on the "city" field.
func CityHasSuffix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasSuffix(FieldCity, v))
}

// CityEqualFold applies the EqualFold predicate on the "city" field.
func CityEqualFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEqualFold(FieldCity, v))
}

// CityContainsFold applies the ContainsFold predicate on the "city" field.
func CityContainsFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContainsFold(FieldCity, v))
}

// IspEQ applies the EQ predicate on the "isp" field.
func IspEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldIsp, v))
}

// IspNEQ applies the NEQ predicate on the "isp" field.
func IspNEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldIsp, v))
}

// IspIn applies the In predicate on the "isp" field.
func IspIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIn(FieldIsp, vs...))
}

// IspNotIn applies the NotIn predicate on the "isp" field.
func IspNotIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotIn(FieldIsp, vs...))
}

// IspGT applies the GT predicate on the "isp" field.
func IspGT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGT(FieldIsp, v))
}

// IspGTE applies the GTE predicate on the "isp" field.
func IspGTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGTE(FieldIsp, v))
}

// IspLT applies the LT predicate on the "isp" field.
func IspLT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLT(FieldIsp, v))
}

// IspLTE applies the LTE predicate on the "isp" field.
func IspLTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLTE(FieldIsp, v))
}

// IspContains applies the Contains predicate on the "isp" field.
func IspContains(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContains(FieldIsp, v))
}

// IspHasPrefix applies the HasPrefix predicate on the "isp" field.
func IspHasPrefix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasPrefix(FieldIsp, v))
}

// IspHasSuffix applies the HasSuffix predicate on the "isp" field.
func IspHasSuffix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasSuffix(FieldIsp, v))
}

// IspEqualFold applies the EqualFold predicate on the "isp" field.
func IspEqualFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEqualFold(FieldIsp, v))
}

// IspContainsFold applies the ContainsFold predicate on the "isp" field.
func IspContainsFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContainsFold(FieldIsp, v))
}

// HTTPPortEQ applies the EQ predicate on the "http_port" field.
func HTTPPortEQ(v int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldHTTPPort, v))
}

// HTTPPortNEQ applies the NEQ predicate on the "http_port" field.
func HTTPPortNEQ(v int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldHTTPPort, v))
}

// HTTPPortIn applies the In predicate on the "http_port" field.
func HTTPPortIn(vs ...int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIn(FieldHTTPPort, vs...))
}

// HTTPPortNotIn applies the NotIn predicate on the "http_port" field.
func HTTPPortNotIn(vs ...int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotIn(FieldHTTPPort, vs...))
}

// HTTPPortGT applies the GT predicate on the "http_port" field.
func HTTPPortGT(v int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGT(FieldHTTPPort, v))
}

// HTTPPortGTE applies the GTE predicate on the "http_port" field.
func HTTPPortGTE(v int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGTE(FieldHTTPPort, v))
}

// HTTPPortLT applies the LT predicate on the "http_port" field.
func HTTPPortLT(v int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLT(FieldHTTPPort, v))
}

// HTTPPortLTE applies the LTE predicate on the "http_port" field.
func HTTPPortLTE(v int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLTE(FieldHTTPPort, v))
}

// VlessPortEQ applies the EQ predicate on the "vless_port" field.
func VlessPortEQ(v int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldVlessPort, v))
}

// VlessPortNEQ applies the NEQ predicate on the "vless_port" field.
func VlessPortNEQ(v int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldVlessPort, v))
}

// VlessPortIn applies the In predicate on the "vless_port" field.
func VlessPortIn(vs ...int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIn(FieldVlessPort, vs...))
}

// VlessPortNotIn applies the NotIn predicate on the "vless_port" field.
func VlessPortNotIn(vs ...int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotIn(FieldVlessPort, vs...))
}

// VlessPortGT applies the GT predicate on the "vless_port" field.
func VlessPortGT(v int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGT(FieldVlessPort, v))
}

// VlessPortGTE applies the GTE predicate on the "vless_port" field.
func VlessPortGTE(v int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGTE(FieldVlessPort, v))
}

// VlessPortLT applies the LT predicate on the "vless_port" field.
func VlessPortLT(v int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLT(FieldVlessPort, v))
}

// VlessPortLTE applies the LTE predicate on the "vless_port" field.
func VlessPortLTE(v int) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLTE(FieldVlessPort, v))
}

// VlessNetworkEQ applies the EQ predicate on the "vless_network" field.
func VlessNetworkEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldVlessNetwork, v))
}

// VlessNetworkNEQ applies the NEQ predicate on the "vless_network" field.
func VlessNetworkNEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldVlessNetwork, v))
}

// VlessNetworkIn applies the In predicate on the "vless_network" field.
func VlessNetworkIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIn(FieldVlessNetwork, vs...))
}

// VlessNetworkNotIn applies the NotIn predicate on the "vless_network" field.
func VlessNetworkNotIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotIn(FieldVlessNetwork, vs...))
}

// VlessNetworkGT applies the GT predicate on the "vless_network" field.
func VlessNetworkGT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGT(FieldVlessNetwork, v))
}

// VlessNetworkGTE applies the GTE predicate on the "vless_network" field.
func VlessNetworkGTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGTE(FieldVlessNetwork, v))
}

// VlessNetworkLT applies the LT predicate on the "vless_network" field.
func VlessNetworkLT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLT(FieldVlessNetwork, v))
}

// VlessNetworkLTE applies the LTE predicate on the "vless_network" field.
func VlessNetworkLTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLTE(FieldVlessNetwork, v))
}

// VlessNetworkContains applies the Contains predicate on the "vless_network" field.
func VlessNetworkContains(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContains(FieldVlessNetwork, v))
}

// VlessNetworkHasPrefix applies the HasPrefix predicate on the "vless_network" field.
func VlessNetworkHasPrefix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasPrefix(FieldVlessNetwork, v))
}

// VlessNetworkHasSuffix applies the HasSuffix predicate on the "vless_network" field.
func VlessNetworkHasSuffix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasSuffix(FieldVlessNetwork, v))
}

// VlessNetworkEqualFold applies the EqualFold predicate on the "vless_network" field.
func VlessNetworkEqualFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEqualFold(FieldVlessNetwork, v))
}

// VlessNetworkContainsFold applies the ContainsFold predicate on the "vless_network" field.
func VlessNetworkContainsFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContainsFold(FieldVlessNetwork, v))
}

// VlessTLSEQ applies the EQ predicate on the "vless_tls" field.
func VlessTLSEQ(v bool) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldVlessTLS, v))
}

// VlessTLSNEQ applies the NEQ predicate on the "vless_tls" field.
func VlessTLSNEQ(v bool) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldVlessTLS, v))
}

// VlessSniEQ applies the EQ predicate on the "vless_sni" field.
func VlessSniEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldVlessSni, v))
}

// VlessSniNEQ applies the NEQ predicate on the "vless_sni" field.
func VlessSniNEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldVlessSni, v))
}

// VlessSniIn applies the In predicate on the "vless_sni" field.
func VlessSniIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIn(FieldVlessSni, vs...))
}

// VlessSniNotIn applies the NotIn predicate on the "vless_sni" field.
func VlessSniNotIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotIn(FieldVlessSni, vs...))
}

// VlessSniGT applies the GT predicate on the "vless_sni" field.
func VlessSniGT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGT(FieldVlessSni, v))
}

// VlessSniGTE applies the GTE predicate on the "vless_sni" field.
func VlessSniGTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGTE(FieldVlessSni, v))
}

// VlessSniLT applies the LT predicate on the "vless_sni" field.
func VlessSniLT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLT(FieldVlessSni, v))
}

// VlessSniLTE applies the LTE predicate on the "vless_sni" field.
func VlessSniLTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLTE(FieldVlessSni, v))
}

// VlessSniContains applies the Contains predicate on the "vless_sni" field.
func VlessSniContains(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContains(FieldVlessSni, v))
}

// VlessSniHasPrefix applies the HasPrefix predicate on the "vless_sni" field.
func VlessSniHasPrefix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasPrefix(FieldVlessSni, v))
}

// VlessSniHasSuffix applies the HasSuffix predicate on the "vless_sni" field.
func VlessSniHasSuffix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasSuffix(FieldVlessSni, v))
}

// VlessSniEqualFold applies the EqualFold predicate on the "vless_sni" field.
func VlessSniEqualFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEqualFold(FieldVlessSni, v))
}

// VlessSniContainsFold applies the ContainsFold predicate on the "vless_sni" field.
func VlessSniContainsFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContainsFold(FieldVlessSni, v))
}

// VlessWsPathEQ applies the EQ predicate on the "vless_ws_path" field.
func VlessWsPathEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldVlessWsPath, v))
}

// VlessWsPathNEQ applies the NEQ predicate on the "vless_ws_path" field.
func VlessWsPathNEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldVlessWsPath, v))
}

// VlessWsPathIn applies the In predicate on the "vless_ws_path" field.
func VlessWsPathIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIn(FieldVlessWsPath, vs...))
}

// VlessWsPathNotIn applies the NotIn predicate on the "vless_ws_path" field.
func VlessWsPathNotIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotIn(FieldVlessWsPath, vs...))
}

// VlessWsPathGT applies the GT predicate on the "vless_ws_path" field.
func VlessWsPathGT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGT(FieldVlessWsPath, v))
}

// VlessWsPathGTE applies the GTE predicate on the "vless_ws_path" field.
func VlessWsPathGTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGTE(FieldVlessWsPath, v))
}

// VlessWsPathLT applies the LT predicate on the "vless_ws_path" field.
func VlessWsPathLT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLT(FieldVlessWsPath, v))
}

// VlessWsPathLTE applies the LTE predicate on the "vless_ws_path" field.
func VlessWsPathLTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLTE(FieldVlessWsPath, v))
}

// VlessWsPathContains applies the Contains predicate on the "vless_ws_path" field.
func VlessWsPathContains(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContains(FieldVlessWsPath, v))
}

// VlessWsPathHasPrefix applies the HasPrefix predicate on the "vless_ws_path" field.
func VlessWsPathHasPrefix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasPrefix(FieldVlessWsPath, v))
}

// VlessWsPathHasSuffix applies the HasSuffix predicate on the "vless_ws_path" field.
func VlessWsPathHasSuffix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasSuffix(FieldVlessWsPath, v))
}

// VlessWsPathEqualFold applies the EqualFold predicate on the "vless_ws_path" field.
func VlessWsPathEqualFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEqualFold(FieldVlessWsPath, v))
}

// VlessWsPathContainsFold applies the ContainsFold predicate on the "vless_ws_path" field.
func VlessWsPathContainsFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContainsFold(FieldVlessWsPath, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContainsFold(FieldStatus, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ProxyNode {
	return predicate.ProxyNode(sql.FieldContainsFold(FieldDescription, v))
}

// HasRentals applies the HasEdge predicate on the "rentals" edge.
func HasRentals() predicate.ProxyNode {
	return predicate.ProxyNode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RentalsTable, RentalsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRentalsWith applies the HasEdge predicate on the "rentals" edge with a given conditions (other predicates).
func HasRentalsWith(preds ...predicate.ProxyRental) predicate.ProxyNode {
	return predicate.ProxyNode(func(s *sql.Selector) {
		step := newRentalsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProxyNode) predicate.ProxyNode {
	return predicate.ProxyNode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProxyNode) predicate.ProxyNode {
	return predicate.ProxyNode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProxyNode) predicate.ProxyNode {
	return predicate.ProxyNode(sql.NotPredicates(p))
}
