// Code generated by ent, DO NOT EDIT.

package proxyrental

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the proxyrental type in the database.
	Label = "proxy_rental"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldNodeID holds the string denoting the node_id field in the database.
	FieldNodeID = "node_id"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldPaymentOrderID holds the string denoting the payment_order_id field in the database.
	FieldPaymentOrderID = "payment_order_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldTrafficUsedBytes holds the string denoting the traffic_used_bytes field in the database.
	FieldTrafficUsedBytes = "traffic_used_bytes"
	// FieldTrafficLimitBytes holds the string denoting the traffic_limit_bytes field in the database.
	FieldTrafficLimitBytes = "traffic_limit_bytes"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeNode holds the string denoting the node edge name in mutations.
	EdgeNode = "node"
	// EdgeProduct holds the string denoting the product edge name in mutations.
	EdgeProduct = "product"
	// EdgeCredential holds the string denoting the credential edge name in mutations.
	EdgeCredential = "credential"
	// EdgeTrafficLogs holds the string denoting the traffic_logs edge name in mutations.
	EdgeTrafficLogs = "traffic_logs"
	// Table holds the table name of the proxyrental in the database.
	Table = "proxy_rentals"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "proxy_rentals"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// NodeTable is the table that holds the node relation/edge.
	NodeTable = "proxy_rentals"
	// NodeInverseTable is the table name for the ProxyNode entity.
	// It exists in this package in order to avoid circular dependency with the "proxynode" package.
	NodeInverseTable = "proxy_nodes"
	// NodeColumn is the table column denoting the node relation/edge.
	NodeColumn = "node_id"
	// ProductTable is the table that holds the product relation/edge.
	ProductTable = "proxy_rentals"
	// ProductInverseTable is the table name for the ProxyProduct entity.
	// It exists in this package in order to avoid circular dependency with the "proxyproduct" package.
	ProductInverseTable = "proxy_products"
	// ProductColumn is the table column denoting the product relation/edge.
	ProductColumn = "product_id"
	// CredentialTable is the table that holds the credential relation/edge.
	CredentialTable = "proxy_credentials"
	// CredentialInverseTable is the table name for the ProxyCredential entity.
	// It exists in this package in order to avoid circular dependency with the "proxycredential" package.
	CredentialInverseTable = "proxy_credentials"
	// CredentialColumn is the table column denoting the credential relation/edge.
	CredentialColumn = "rental_id"
	// TrafficLogsTable is the table that holds the traffic_logs relation/edge.
	TrafficLogsTable = "proxy_traffic_logs"
	// TrafficLogsInverseTable is the table name for the ProxyTrafficLog entity.
	// It exists in this package in order to avoid circular dependency with the "proxytrafficlog" package.
	TrafficLogsInverseTable = "proxy_traffic_logs"
	// TrafficLogsColumn is the table column denoting the traffic_logs relation/edge.
	TrafficLogsColumn = "rental_id"
)

// Columns holds all SQL columns for proxyrental fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldNodeID,
	FieldProductID,
	FieldPaymentOrderID,
	FieldStatus,
	FieldStartedAt,
	FieldExpiresAt,
	FieldTrafficUsedBytes,
	FieldTrafficLimitBytes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultTrafficUsedBytes holds the default value on creation for the "traffic_used_bytes" field.
	DefaultTrafficUsedBytes int64
	// DefaultTrafficLimitBytes holds the default value on creation for the "traffic_limit_bytes" field.
	DefaultTrafficLimitBytes int64
)

// OrderOption defines the ordering options for the ProxyRental queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByNodeID orders the results by the node_id field.
func ByNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeID, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByPaymentOrderID orders the results by the payment_order_id field.
func ByPaymentOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentOrderID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByTrafficUsedBytes orders the results by the traffic_used_bytes field.
func ByTrafficUsedBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrafficUsedBytes, opts...).ToFunc()
}

// ByTrafficLimitBytes orders the results by the traffic_limit_bytes field.
func ByTrafficLimitBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrafficLimitBytes, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByNodeField orders the results by node field.
func ByNodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNodeStep(), sql.OrderByField(field, opts...))
	}
}

// ByProductField orders the results by product field.
func ByProductField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductStep(), sql.OrderByField(field, opts...))
	}
}

// ByCredentialField orders the results by credential field.
func ByCredentialField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCredentialStep(), sql.OrderByField(field, opts...))
	}
}

// ByTrafficLogsCount orders the results by traffic_logs count.
func ByTrafficLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTrafficLogsStep(), opts...)
	}
}

// ByTrafficLogs orders the results by traffic_logs terms.
func ByTrafficLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTrafficLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newNodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, NodeTable, NodeColumn),
	)
}
func newProductStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
	)
}
func newCredentialStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CredentialInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, CredentialTable, CredentialColumn),
	)
}
func newTrafficLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TrafficLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TrafficLogsTable, TrafficLogsColumn),
	)
}
