// Code generated by ent, DO NOT EDIT.

package proxyrental

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/meitianwang/fast-frame/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldUserID, v))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldNodeID, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldProductID, v))
}

// PaymentOrderID applies equality check predicate on the "payment_order_id" field. It's identical to PaymentOrderIDEQ.
func PaymentOrderID(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldPaymentOrderID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldStatus, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldStartedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldExpiresAt, v))
}

// TrafficUsedBytes applies equality check predicate on the "traffic_used_bytes" field. It's identical to TrafficUsedBytesEQ.
func TrafficUsedBytes(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldTrafficUsedBytes, v))
}

// TrafficLimitBytes applies equality check predicate on the "traffic_limit_bytes" field. It's identical to TrafficLimitBytesEQ.
func TrafficLimitBytes(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldTrafficLimitBytes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNotIn(FieldUserID, vs...))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNotIn(FieldNodeID, vs...))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNotIn(FieldProductID, vs...))
}

// PaymentOrderIDEQ applies the EQ predicate on the "payment_order_id" field.
func PaymentOrderIDEQ(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDNEQ applies the NEQ predicate on the "payment_order_id" field.
func PaymentOrderIDNEQ(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDIn applies the In predicate on the "payment_order_id" field.
func PaymentOrderIDIn(vs ...int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDNotIn applies the NotIn predicate on the "payment_order_id" field.
func PaymentOrderIDNotIn(vs ...int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNotIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDGT applies the GT predicate on the "payment_order_id" field.
func PaymentOrderIDGT(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGT(FieldPaymentOrderID, v))
}

// PaymentOrderIDGTE applies the GTE predicate on the "payment_order_id" field.
func PaymentOrderIDGTE(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGTE(FieldPaymentOrderID, v))
}

// PaymentOrderIDLT applies the LT predicate on the "payment_order_id" field.
func PaymentOrderIDLT(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLT(FieldPaymentOrderID, v))
}

// PaymentOrderIDLTE applies the LTE predicate on the "payment_order_id" field.
func PaymentOrderIDLTE(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLTE(FieldPaymentOrderID, v))
}

// PaymentOrderIDIsNil applies the IsNil predicate on the "payment_order_id" field.
func PaymentOrderIDIsNil() predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldIsNull(FieldPaymentOrderID))
}

// PaymentOrderIDNotNil applies the NotNil predicate on the "payment_order_id" field.
func PaymentOrderIDNotNil() predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNotNull(FieldPaymentOrderID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldContainsFold(FieldStatus, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNotNull(FieldStartedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNotNull(FieldExpiresAt))
}

// TrafficUsedBytesEQ applies the EQ predicate on the "traffic_used_bytes" field.
func TrafficUsedBytesEQ(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldTrafficUsedBytes, v))
}

// TrafficUsedBytesNEQ applies the NEQ predicate on the "traffic_used_bytes" field.
func TrafficUsedBytesNEQ(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNEQ(FieldTrafficUsedBytes, v))
}

// TrafficUsedBytesIn applies the In predicate on the "traffic_used_bytes" field.
func TrafficUsedBytesIn(vs ...int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldIn(FieldTrafficUsedBytes, vs...))
}

// TrafficUsedBytesNotIn applies the NotIn predicate on the "traffic_used_bytes" field.
func TrafficUsedBytesNotIn(vs ...int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNotIn(FieldTrafficUsedBytes, vs...))
}

// TrafficUsedBytesGT applies the GT predicate on the "traffic_used_bytes" field.
func TrafficUsedBytesGT(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGT(FieldTrafficUsedBytes, v))
}

// TrafficUsedBytesGTE applies the GTE predicate on the "traffic_used_bytes" field.
func TrafficUsedBytesGTE(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGTE(FieldTrafficUsedBytes, v))
}

// TrafficUsedBytesLT applies the LT predicate on the "traffic_used_bytes" field.
func TrafficUsedBytesLT(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLT(FieldTrafficUsedBytes, v))
}

// TrafficUsedBytesLTE applies the LTE predicate on the "traffic_used_bytes" field.
func TrafficUsedBytesLTE(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLTE(FieldTrafficUsedBytes, v))
}

// TrafficLimitBytesEQ applies the EQ predicate on the "traffic_limit_bytes" field.
func TrafficLimitBytesEQ(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldEQ(FieldTrafficLimitBytes, v))
}

// TrafficLimitBytesNEQ applies the NEQ predicate on the "traffic_limit_bytes" field.
func TrafficLimitBytesNEQ(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNEQ(FieldTrafficLimitBytes, v))
}

// TrafficLimitBytesIn applies the In predicate on the "traffic_limit_bytes" field.
func TrafficLimitBytesIn(vs ...int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldIn(FieldTrafficLimitBytes, vs...))
}

// TrafficLimitBytesNotIn applies the NotIn predicate on the "traffic_limit_bytes" field.
func TrafficLimitBytesNotIn(vs ...int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldNotIn(FieldTrafficLimitBytes, vs...))
}

// TrafficLimitBytesGT applies the GT predicate on the "traffic_limit_bytes" field.
func TrafficLimitBytesGT(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGT(FieldTrafficLimitBytes, v))
}

// TrafficLimitBytesGTE applies the GTE predicate on the "traffic_limit_bytes" field.
func TrafficLimitBytesGTE(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldGTE(FieldTrafficLimitBytes, v))
}

// TrafficLimitBytesLT applies the LT predicate on the "traffic_limit_bytes" field.
func TrafficLimitBytesLT(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLT(FieldTrafficLimitBytes, v))
}

// TrafficLimitBytesLTE applies the LTE predicate on the "traffic_limit_bytes" field.
func TrafficLimitBytesLTE(v int64) predicate.ProxyRental {
	return predicate.ProxyRental(sql.FieldLTE(FieldTrafficLimitBytes, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ProxyRental {
	return predicate.ProxyRental(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ProxyRental {
	return predicate.ProxyRental(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNode applies the HasEdge predicate on the "node" edge.
func HasNode() predicate.ProxyRental {
	return predicate.ProxyRental(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, NodeTable, NodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodeWith applies the HasEdge predicate on the "node" edge with a given conditions (other predicates).
func HasNodeWith(preds ...predicate.ProxyNode) predicate.ProxyRental {
	return predicate.ProxyRental(func(s *sql.Selector) {
		step := newNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProduct applies the HasEdge predicate on the "product" edge.
func HasProduct() predicate.ProxyRental {
	return predicate.ProxyRental(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductWith applies the HasEdge predicate on the "product" edge with a given conditions (other predicates).
func HasProductWith(preds ...predicate.ProxyProduct) predicate.ProxyRental {
	return predicate.ProxyRental(func(s *sql.Selector) {
		step := newProductStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCredential applies the HasEdge predicate on the "credential" edge.
func HasCredential() predicate.ProxyRental {
	return predicate.ProxyRental(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, CredentialTable, CredentialColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCredentialWith applies the HasEdge predicate on the "credential" edge with a given conditions (other predicates).
func HasCredentialWith(preds ...predicate.ProxyCredential) predicate.ProxyRental {
	return predicate.ProxyRental(func(s *sql.Selector) {
		step := newCredentialStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTrafficLogs applies the HasEdge predicate on the "traffic_logs" edge.
func HasTrafficLogs() predicate.ProxyRental {
	return predicate.ProxyRental(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TrafficLogsTable, TrafficLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTrafficLogsWith applies the HasEdge predicate on the "traffic_logs" edge with a given conditions (other predicates).
func HasTrafficLogsWith(preds ...predicate.ProxyTrafficLog) predicate.ProxyRental {
	return predicate.ProxyRental(func(s *sql.Selector) {
		step := newTrafficLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProxyRental) predicate.ProxyRental {
	return predicate.ProxyRental(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProxyRental) predicate.ProxyRental {
	return predicate.ProxyRental(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProxyRental) predicate.ProxyRental {
	return predicate.ProxyRental(sql.NotPredicates(p))
}
