// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/meitianwang/fast-frame/ent/predicate"
	"github.com/meitianwang/fast-frame/ent/proxynode"
	"github.com/meitianwang/fast-frame/ent/proxyrental"
)

// ProxyNodeUpdate is the builder for updating ProxyNode entities.
type ProxyNodeUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyNodeMutation
}

// Where appends a list predicates to the ProxyNodeUpdate builder.
func (_u *ProxyNodeUpdate) Where(ps ...predicate.ProxyNode) *ProxyNodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyNodeUpdate) SetUpdatedAt(v time.Time) *ProxyNodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProxyNodeUpdate) SetDeletedAt(v time.Time) *ProxyNodeUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProxyNodeUpdate) SetNillableDeletedAt(v *time.Time) *ProxyNodeUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProxyNodeUpdate) ClearDeletedAt() *ProxyNodeUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *ProxyNodeUpdate) SetIPAddress(v string) *ProxyNodeUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *ProxyNodeUpdate) SetNillableIPAddress(v *string) *ProxyNodeUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *ProxyNodeUpdate) SetCountry(v string) *ProxyNodeUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *ProxyNodeUpdate) SetNillableCountry(v *string) *ProxyNodeUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetCountryCode sets the "country_code" field.
func (_u *ProxyNodeUpdate) SetCountryCode(v string) *ProxyNodeUpdate {
	_u.mutation.SetCountryCode(v)
	return _u
}

// SetNillableCountryCode sets the "country_code" field if the given value is not nil.
func (_u *ProxyNodeUpdate) SetNillableCountryCode(v *string) *ProxyNodeUpdate {
	if v != nil {
		_u.SetCountryCode(*v)
	}
	return _u
}

// SetCity sets the "city" field.
func (_u *ProxyNodeUpdate) SetCity(v string) *ProxyNodeUpdate {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *ProxyNodeUpdate) SetNillableCity(v *string) *ProxyNodeUpdate {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// SetIsp sets the "isp" field.
func (_u *ProxyNodeUpdate) SetIsp(v string) *ProxyNodeUpdate {
	_u.mutation.SetIsp(v)
	return _u
}

// SetNillableIsp sets the "isp" field if the given value is not nil.
func (_u *ProxyNodeUpdate) SetNillableIsp(v *string) *ProxyNodeUpdate {
	if v != nil {
		_u.SetIsp(*v)
	}
	return _u
}

// SetHTTPPort sets the "http_port" field.
func (_u *ProxyNodeUpdate) SetHTTPPort(v int) *ProxyNodeUpdate {
	_u.mutation.ResetHTTPPort()
	_u.mutation.SetHTTPPort(v)
	return _u
}

// SetNillableHTTPPort sets the "http_port" field if the given value is not nil.
func (_u *ProxyNodeUpdate) SetNillableHTTPPort(v *int) *ProxyNodeUpdate {
	if v != nil {
		_u.SetHTTPPort(*v)
	}
	return _u
}

// AddHTTPPort adds value to the "http_port" field.
func (_u *ProxyNodeUpdate) AddHTTPPort(v int) *ProxyNodeUpdate {
	_u.mutation.AddHTTPPort(v)
	return _u
}

// SetVlessPort sets the "vless_port" field.
func (_u *ProxyNodeUpdate) SetVlessPort(v int) *ProxyNodeUpdate {
	_u.mutation.ResetVlessPort()
	_u.mutation.SetVlessPort(v)
	return _u
}

// SetNillableVlessPort sets the "vless_port" field if the given value is not nil.
func (_u *ProxyNodeUpdate) SetNillableVlessPort(v *int) *ProxyNodeUpdate {
	if v != nil {
		_u.SetVlessPort(*v)
	}
	return _u
}

// AddVlessPort adds value to the "vless_port" field.
func (_u *ProxyNodeUpdate) AddVlessPort(v int) *ProxyNodeUpdate {
	_u.mutation.AddVlessPort(v)
	return _u
}

// SetVlessNetwork sets the "vless_network" field.
func (_u *ProxyNodeUpdate) SetVlessNetwork(v string) *ProxyNodeUpdate {
	_u.mutation.SetVlessNetwork(v)
	return _u
}

// SetNillableVlessNetwork sets the "vless_network" field if the given value is not nil.
func (_u *ProxyNodeUpdate) SetNillableVlessNetwork(v *string) *ProxyNodeUpdate {
	if v != nil {
		_u.SetVlessNetwork(*v)
	}
	return _u
}

// SetVlessTLS sets the "vless_tls" field.
func (_u *ProxyNodeUpdate) SetVlessTLS(v bool) *ProxyNodeUpdate {
	_u.mutation.SetVlessTLS(v)
	return _u
}

// SetNillableVlessTLS sets the "vless_tls" field if the given value is not nil.
func (_u *ProxyNodeUpdate) SetNillableVlessTLS(v *bool) *ProxyNodeUpdate {
	if v != nil {
		_u.SetVlessTLS(*v)
	}
	return _u
}

// SetVlessSni sets the "vless_sni" field.
func (_u *ProxyNodeUpdate) SetVlessSni(v string) *ProxyNodeUpdate {
	_u.mutation.SetVlessSni(v)
	return _u
}

// SetNillableVlessSni sets the "vless_sni" field if the given value is not nil.
func (_u *ProxyNodeUpdate) SetNillableVlessSni(v *string) *ProxyNodeUpdate {
	if v != nil {
		_u.SetVlessSni(*v)
	}
	return _u
}

// SetVlessWsPath sets the "vless_ws_path" field.
func (_u *ProxyNodeUpdate) SetVlessWsPath(v string) *ProxyNodeUpdate {
	_u.mutation.SetVlessWsPath(v)
	return _u
}

// SetNillableVlessWsPath sets the "vless_ws_path" field if the given value is not nil.
func (_u *ProxyNodeUpdate) SetNillableVlessWsPath(v *string) *ProxyNodeUpdate {
	if v != nil {
		_u.SetVlessWsPath(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *ProxyNodeUpdate) SetTags(v []string) *ProxyNodeUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ProxyNodeUpdate) AppendTags(v []string) *ProxyNodeUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProxyNodeUpdate) SetStatus(v string) *ProxyNodeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProxyNodeUpdate) SetNillableStatus(v *string) *ProxyNodeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProxyNodeUpdate) SetDescription(v string) *ProxyNodeUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProxyNodeUpdate) SetNillableDescription(v *string) *ProxyNodeUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// AddRentalIDs adds the "rentals" edge to the ProxyRental entity by IDs.
func (_u *ProxyNodeUpdate) AddRentalIDs(ids ...int64) *ProxyNodeUpdate {
	_u.mutation.AddRentalIDs(ids...)
	return _u
}

// AddRentals adds the "rentals" edges to the ProxyRental entity.
func (_u *ProxyNodeUpdate) AddRentals(v ...*ProxyRental) *ProxyNodeUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRentalIDs(ids...)
}

// Mutation returns the ProxyNodeMutation object of the builder.
func (_u *ProxyNodeUpdate) Mutation() *ProxyNodeMutation {
	return _u.mutation
}

// ClearRentals clears all "rentals" edges to the ProxyRental entity.
func (_u *ProxyNodeUpdate) ClearRentals() *ProxyNodeUpdate {
	_u.mutation.ClearRentals()
	return _u
}

// RemoveRentalIDs removes the "rentals" edge to ProxyRental entities by IDs.
func (_u *ProxyNodeUpdate) RemoveRentalIDs(ids ...int64) *ProxyNodeUpdate {
	_u.mutation.RemoveRentalIDs(ids...)
	return _u
}

// RemoveRentals removes "rentals" edges to ProxyRental entities.
func (_u *ProxyNodeUpdate) RemoveRentals(v ...*ProxyRental) *ProxyNodeUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRentalIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyNodeUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyNodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxyNodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyNodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyNodeUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if proxynode.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxynode.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proxynode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyNodeUpdate) check() error {
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := proxynode.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := proxynode.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CountryCode(); ok {
		if err := proxynode.CountryCodeValidator(v); err != nil {
			return &ValidationError{Name: "country_code", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.country_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.City(); ok {
		if err := proxynode.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Isp(); ok {
		if err := proxynode.IspValidator(v); err != nil {
			return &ValidationError{Name: "isp", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.isp": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VlessNetwork(); ok {
		if err := proxynode.VlessNetworkValidator(v); err != nil {
			return &ValidationError{Name: "vless_network", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.vless_network": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VlessSni(); ok {
		if err := proxynode.VlessSniValidator(v); err != nil {
			return &ValidationError{Name: "vless_sni", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.vless_sni": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VlessWsPath(); ok {
		if err := proxynode.VlessWsPathValidator(v); err != nil {
			return &ValidationError{Name: "vless_ws_path", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.vless_ws_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := proxynode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyNodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxynode.Table, proxynode.Columns, sqlgraph.NewFieldSpec(proxynode.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxynode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(proxynode.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(proxynode.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(proxynode.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(proxynode.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.CountryCode(); ok {
		_spec.SetField(proxynode.FieldCountryCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(proxynode.FieldCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Isp(); ok {
		_spec.SetField(proxynode.FieldIsp, field.TypeString, value)
	}
	if value, ok := _u.mutation.HTTPPort(); ok {
		_spec.SetField(proxynode.FieldHTTPPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPPort(); ok {
		_spec.AddField(proxynode.FieldHTTPPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VlessPort(); ok {
		_spec.SetField(proxynode.FieldVlessPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVlessPort(); ok {
		_spec.AddField(proxynode.FieldVlessPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VlessNetwork(); ok {
		_spec.SetField(proxynode.FieldVlessNetwork, field.TypeString, value)
	}
	if value, ok := _u.mutation.VlessTLS(); ok {
		_spec.SetField(proxynode.FieldVlessTLS, field.TypeBool, value)
	}
	if value, ok := _u.mutation.VlessSni(); ok {
		_spec.SetField(proxynode.FieldVlessSni, field.TypeString, value)
	}
	if value, ok := _u.mutation.VlessWsPath(); ok {
		_spec.SetField(proxynode.FieldVlessWsPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(proxynode.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, proxynode.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(proxynode.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(proxynode.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.RentalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxynode.RentalsTable,
			Columns: []string{proxynode.RentalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRentalsIDs(); len(nodes) > 0 && !_u.mutation.RentalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxynode.RentalsTable,
			Columns: []string{proxynode.RentalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RentalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxynode.RentalsTable,
			Columns: []string{proxynode.RentalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxynode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxyNodeUpdateOne is the builder for updating a single ProxyNode entity.
type ProxyNodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyNodeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyNodeUpdateOne) SetUpdatedAt(v time.Time) *ProxyNodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProxyNodeUpdateOne) SetDeletedAt(v time.Time) *ProxyNodeUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProxyNodeUpdateOne) SetNillableDeletedAt(v *time.Time) *ProxyNodeUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProxyNodeUpdateOne) ClearDeletedAt() *ProxyNodeUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *ProxyNodeUpdateOne) SetIPAddress(v string) *ProxyNodeUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *ProxyNodeUpdateOne) SetNillableIPAddress(v *string) *ProxyNodeUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *ProxyNodeUpdateOne) SetCountry(v string) *ProxyNodeUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *ProxyNodeUpdateOne) SetNillableCountry(v *string) *ProxyNodeUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetCountryCode sets the "country_code" field.
func (_u *ProxyNodeUpdateOne) SetCountryCode(v string) *ProxyNodeUpdateOne {
	_u.mutation.SetCountryCode(v)
	return _u
}

// SetNillableCountryCode sets the "country_code" field if the given value is not nil.
func (_u *ProxyNodeUpdateOne) SetNillableCountryCode(v *string) *ProxyNodeUpdateOne {
	if v != nil {
		_u.SetCountryCode(*v)
	}
	return _u
}

// SetCity sets the "city" field.
func (_u *ProxyNodeUpdateOne) SetCity(v string) *ProxyNodeUpdateOne {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *ProxyNodeUpdateOne) SetNillableCity(v *string) *ProxyNodeUpdateOne {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// SetIsp sets the "isp" field.
func (_u *ProxyNodeUpdateOne) SetIsp(v string) *ProxyNodeUpdateOne {
	_u.mutation.SetIsp(v)
	return _u
}

// SetNillableIsp sets the "isp" field if the given value is not nil.
func (_u *ProxyNodeUpdateOne) SetNillableIsp(v *string) *ProxyNodeUpdateOne {
	if v != nil {
		_u.SetIsp(*v)
	}
	return _u
}

// SetHTTPPort sets the "http_port" field.
func (_u *ProxyNodeUpdateOne) SetHTTPPort(v int) *ProxyNodeUpdateOne {
	_u.mutation.ResetHTTPPort()
	_u.mutation.SetHTTPPort(v)
	return _u
}

// SetNillableHTTPPort sets the "http_port" field if the given value is not nil.
func (_u *ProxyNodeUpdateOne) SetNillableHTTPPort(v *int) *ProxyNodeUpdateOne {
	if v != nil {
		_u.SetHTTPPort(*v)
	}
	return _u
}

// AddHTTPPort adds value to the "http_port" field.
func (_u *ProxyNodeUpdateOne) AddHTTPPort(v int) *ProxyNodeUpdateOne {
	_u.mutation.AddHTTPPort(v)
	return _u
}

// SetVlessPort sets the "vless_port" field.
func (_u *ProxyNodeUpdateOne) SetVlessPort(v int) *ProxyNodeUpdateOne {
	_u.mutation.ResetVlessPort()
	_u.mutation.SetVlessPort(v)
	return _u
}

// SetNillableVlessPort sets the "vless_port" field if the given value is not nil.
func (_u *ProxyNodeUpdateOne) SetNillableVlessPort(v *int) *ProxyNodeUpdateOne {
	if v != nil {
		_u.SetVlessPort(*v)
	}
	return _u
}

// AddVlessPort adds value to the "vless_port" field.
func (_u *ProxyNodeUpdateOne) AddVlessPort(v int) *ProxyNodeUpdateOne {
	_u.mutation.AddVlessPort(v)
	return _u
}

// SetVlessNetwork sets the "vless_network" field.
func (_u *ProxyNodeUpdateOne) SetVlessNetwork(v string) *ProxyNodeUpdateOne {
	_u.mutation.SetVlessNetwork(v)
	return _u
}

// SetNillableVlessNetwork sets the "vless_network" field if the given value is not nil.
func (_u *ProxyNodeUpdateOne) SetNillableVlessNetwork(v *string) *ProxyNodeUpdateOne {
	if v != nil {
		_u.SetVlessNetwork(*v)
	}
	return _u
}

// SetVlessTLS sets the "vless_tls" field.
func (_u *ProxyNodeUpdateOne) SetVlessTLS(v bool) *ProxyNodeUpdateOne {
	_u.mutation.SetVlessTLS(v)
	return _u
}

// SetNillableVlessTLS sets the "vless_tls" field if the given value is not nil.
func (_u *ProxyNodeUpdateOne) SetNillableVlessTLS(v *bool) *ProxyNodeUpdateOne {
	if v != nil {
		_u.SetVlessTLS(*v)
	}
	return _u
}

// SetVlessSni sets the "vless_sni" field.
func (_u *ProxyNodeUpdateOne) SetVlessSni(v string) *ProxyNodeUpdateOne {
	_u.mutation.SetVlessSni(v)
	return _u
}

// SetNillableVlessSni sets the "vless_sni" field if the given value is not nil.
func (_u *ProxyNodeUpdateOne) SetNillableVlessSni(v *string) *ProxyNodeUpdateOne {
	if v != nil {
		_u.SetVlessSni(*v)
	}
	return _u
}

// SetVlessWsPath sets the "vless_ws_path" field.
func (_u *ProxyNodeUpdateOne) SetVlessWsPath(v string) *ProxyNodeUpdateOne {
	_u.mutation.SetVlessWsPath(v)
	return _u
}

// SetNillableVlessWsPath sets the "vless_ws_path" field if the given value is not nil.
func (_u *ProxyNodeUpdateOne) SetNillableVlessWsPath(v *string) *ProxyNodeUpdateOne {
	if v != nil {
		_u.SetVlessWsPath(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *ProxyNodeUpdateOne) SetTags(v []string) *ProxyNodeUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ProxyNodeUpdateOne) AppendTags(v []string) *ProxyNodeUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProxyNodeUpdateOne) SetStatus(v string) *ProxyNodeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProxyNodeUpdateOne) SetNillableStatus(v *string) *ProxyNodeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProxyNodeUpdateOne) SetDescription(v string) *ProxyNodeUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProxyNodeUpdateOne) SetNillableDescription(v *string) *ProxyNodeUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// AddRentalIDs adds the "rentals" edge to the ProxyRental entity by IDs.
func (_u *ProxyNodeUpdateOne) AddRentalIDs(ids ...int64) *ProxyNodeUpdateOne {
	_u.mutation.AddRentalIDs(ids...)
	return _u
}

// AddRentals adds the "rentals" edges to the ProxyRental entity.
func (_u *ProxyNodeUpdateOne) AddRentals(v ...*ProxyRental) *ProxyNodeUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRentalIDs(ids...)
}

// Mutation returns the ProxyNodeMutation object of the builder.
func (_u *ProxyNodeUpdateOne) Mutation() *ProxyNodeMutation {
	return _u.mutation
}

// ClearRentals clears all "rentals" edges to the ProxyRental entity.
func (_u *ProxyNodeUpdateOne) ClearRentals() *ProxyNodeUpdateOne {
	_u.mutation.ClearRentals()
	return _u
}

// RemoveRentalIDs removes the "rentals" edge to ProxyRental entities by IDs.
func (_u *ProxyNodeUpdateOne) RemoveRentalIDs(ids ...int64) *ProxyNodeUpdateOne {
	_u.mutation.RemoveRentalIDs(ids...)
	return _u
}

// RemoveRentals removes "rentals" edges to ProxyRental entities.
func (_u *ProxyNodeUpdateOne) RemoveRentals(v ...*ProxyRental) *ProxyNodeUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRentalIDs(ids...)
}

// Where appends a list predicates to the ProxyNodeUpdate builder.
func (_u *ProxyNodeUpdateOne) Where(ps ...predicate.ProxyNode) *ProxyNodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyNodeUpdateOne) Select(field string, fields ...string) *ProxyNodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxyNode entity.
func (_u *ProxyNodeUpdateOne) Save(ctx context.Context) (*ProxyNode, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyNodeUpdateOne) SaveX(ctx context.Context) *ProxyNode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxyNodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyNodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyNodeUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if proxynode.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxynode.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proxynode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyNodeUpdateOne) check() error {
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := proxynode.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := proxynode.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CountryCode(); ok {
		if err := proxynode.CountryCodeValidator(v); err != nil {
			return &ValidationError{Name: "country_code", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.country_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.City(); ok {
		if err := proxynode.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Isp(); ok {
		if err := proxynode.IspValidator(v); err != nil {
			return &ValidationError{Name: "isp", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.isp": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VlessNetwork(); ok {
		if err := proxynode.VlessNetworkValidator(v); err != nil {
			return &ValidationError{Name: "vless_network", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.vless_network": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VlessSni(); ok {
		if err := proxynode.VlessSniValidator(v); err != nil {
			return &ValidationError{Name: "vless_sni", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.vless_sni": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VlessWsPath(); ok {
		if err := proxynode.VlessWsPathValidator(v); err != nil {
			return &ValidationError{Name: "vless_ws_path", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.vless_ws_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := proxynode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyNodeUpdateOne) sqlSave(ctx context.Context) (_node *ProxyNode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxynode.Table, proxynode.Columns, sqlgraph.NewFieldSpec(proxynode.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxyNode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxynode.FieldID)
		for _, f := range fields {
			if !proxynode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxynode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxynode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(proxynode.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(proxynode.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(proxynode.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(proxynode.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.CountryCode(); ok {
		_spec.SetField(proxynode.FieldCountryCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(proxynode.FieldCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Isp(); ok {
		_spec.SetField(proxynode.FieldIsp, field.TypeString, value)
	}
	if value, ok := _u.mutation.HTTPPort(); ok {
		_spec.SetField(proxynode.FieldHTTPPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPPort(); ok {
		_spec.AddField(proxynode.FieldHTTPPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VlessPort(); ok {
		_spec.SetField(proxynode.FieldVlessPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVlessPort(); ok {
		_spec.AddField(proxynode.FieldVlessPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VlessNetwork(); ok {
		_spec.SetField(proxynode.FieldVlessNetwork, field.TypeString, value)
	}
	if value, ok := _u.mutation.VlessTLS(); ok {
		_spec.SetField(proxynode.FieldVlessTLS, field.TypeBool, value)
	}
	if value, ok := _u.mutation.VlessSni(); ok {
		_spec.SetField(proxynode.FieldVlessSni, field.TypeString, value)
	}
	if value, ok := _u.mutation.VlessWsPath(); ok {
		_spec.SetField(proxynode.FieldVlessWsPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(proxynode.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, proxynode.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(proxynode.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(proxynode.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.RentalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxynode.RentalsTable,
			Columns: []string{proxynode.RentalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRentalsIDs(); len(nodes) > 0 && !_u.mutation.RentalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxynode.RentalsTable,
			Columns: []string{proxynode.RentalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RentalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxynode.RentalsTable,
			Columns: []string{proxynode.RentalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProxyNode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxynode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
