// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/meitianwang/fast-frame/ent/proxyproduct"
	"github.com/meitianwang/fast-frame/ent/proxyrental"
	"github.com/shopspring/decimal"
)

// ProxyProductCreate is the builder for creating a ProxyProduct entity.
type ProxyProductCreate struct {
	config
	mutation *ProxyProductMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxyProductCreate) SetCreatedAt(v time.Time) *ProxyProductCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxyProductCreate) SetNillableCreatedAt(v *time.Time) *ProxyProductCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxyProductCreate) SetUpdatedAt(v time.Time) *ProxyProductCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxyProductCreate) SetNillableUpdatedAt(v *time.Time) *ProxyProductCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ProxyProductCreate) SetName(v string) *ProxyProductCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ProxyProductCreate) SetDescription(v string) *ProxyProductCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ProxyProductCreate) SetNillableDescription(v *string) *ProxyProductCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetDurationDays sets the "duration_days" field.
func (_c *ProxyProductCreate) SetDurationDays(v int) *ProxyProductCreate {
	_c.mutation.SetDurationDays(v)
	return _c
}

// SetTrafficLimitGB sets the "traffic_limit_gb" field.
func (_c *ProxyProductCreate) SetTrafficLimitGB(v int) *ProxyProductCreate {
	_c.mutation.SetTrafficLimitGB(v)
	return _c
}

// SetNillableTrafficLimitGB sets the "traffic_limit_gb" field if the given value is not nil.
func (_c *ProxyProductCreate) SetNillableTrafficLimitGB(v *int) *ProxyProductCreate {
	if v != nil {
		_c.SetTrafficLimitGB(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *ProxyProductCreate) SetPrice(v decimal.Decimal) *ProxyProductCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *ProxyProductCreate) SetSortOrder(v int) *ProxyProductCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *ProxyProductCreate) SetNillableSortOrder(v *int) *ProxyProductCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *ProxyProductCreate) SetIsActive(v bool) *ProxyProductCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *ProxyProductCreate) SetNillableIsActive(v *bool) *ProxyProductCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// AddRentalIDs adds the "rentals" edge to the ProxyRental entity by IDs.
func (_c *ProxyProductCreate) AddRentalIDs(ids ...int64) *ProxyProductCreate {
	_c.mutation.AddRentalIDs(ids...)
	return _c
}

// AddRentals adds the "rentals" edges to the ProxyRental entity.
func (_c *ProxyProductCreate) AddRentals(v ...*ProxyRental) *ProxyProductCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRentalIDs(ids...)
}

// Mutation returns the ProxyProductMutation object of the builder.
func (_c *ProxyProductCreate) Mutation() *ProxyProductMutation {
	return _c.mutation
}

// Save creates the ProxyProduct in the database.
func (_c *ProxyProductCreate) Save(ctx context.Context) (*ProxyProduct, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxyProductCreate) SaveX(ctx context.Context) *ProxyProduct {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyProductCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyProductCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxyProductCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := proxyproduct.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := proxyproduct.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := proxyproduct.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.TrafficLimitGB(); !ok {
		v := proxyproduct.DefaultTrafficLimitGB
		_c.mutation.SetTrafficLimitGB(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := proxyproduct.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := proxyproduct.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxyProductCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxyProduct.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxyProduct.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ProxyProduct.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := proxyproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxyProduct.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "ProxyProduct.description"`)}
	}
	if _, ok := _c.mutation.DurationDays(); !ok {
		return &ValidationError{Name: "duration_days", err: errors.New(`ent: missing required field "ProxyProduct.duration_days"`)}
	}
	if v, ok := _c.mutation.DurationDays(); ok {
		if err := proxyproduct.DurationDaysValidator(v); err != nil {
			return &ValidationError{Name: "duration_days", err: fmt.Errorf(`ent: validator failed for field "ProxyProduct.duration_days": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TrafficLimitGB(); !ok {
		return &ValidationError{Name: "traffic_limit_gb", err: errors.New(`ent: missing required field "ProxyProduct.traffic_limit_gb"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "ProxyProduct.price"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "ProxyProduct.sort_order"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "ProxyProduct.is_active"`)}
	}
	return nil
}

func (_c *ProxyProductCreate) sqlSave(ctx context.Context) (*ProxyProduct, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxyProductCreate) createSpec() (*ProxyProduct, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxyProduct{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxyproduct.Table, sqlgraph.NewFieldSpec(proxyproduct.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxyproduct.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyproduct.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(proxyproduct.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(proxyproduct.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.DurationDays(); ok {
		_spec.SetField(proxyproduct.FieldDurationDays, field.TypeInt, value)
		_node.DurationDays = value
	}
	if value, ok := _c.mutation.TrafficLimitGB(); ok {
		_spec.SetField(proxyproduct.FieldTrafficLimitGB, field.TypeInt, value)
		_node.TrafficLimitGB = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(proxyproduct.FieldPrice, field.TypeOther, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(proxyproduct.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(proxyproduct.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if nodes := _c.mutation.RentalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyproduct.RentalsTable,
			Columns: []string{proxyproduct.RentalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxyProduct.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyProductUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyProductCreate) OnConflict(opts ...sql.ConflictOption) *ProxyProductUpsertOne {
	_c.conflict = opts
	return &ProxyProductUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxyProduct.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyProductCreate) OnConflictColumns(columns ...string) *ProxyProductUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyProductUpsertOne{
		create: _c,
	}
}

type (
	// ProxyProductUpsertOne is the builder for "upsert"-ing
	//  one ProxyProduct node.
	ProxyProductUpsertOne struct {
		create *ProxyProductCreate
	}

	// ProxyProductUpsert is the "OnConflict" setter.
	ProxyProductUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyProductUpsert) SetUpdatedAt(v time.Time) *ProxyProductUpsert {
	u.Set(proxyproduct.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyProductUpsert) UpdateUpdatedAt() *ProxyProductUpsert {
	u.SetExcluded(proxyproduct.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *ProxyProductUpsert) SetName(v string) *ProxyProductUpsert {
	u.Set(proxyproduct.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxyProductUpsert) UpdateName() *ProxyProductUpsert {
	u.SetExcluded(proxyproduct.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *ProxyProductUpsert) SetDescription(v string) *ProxyProductUpsert {
	u.Set(proxyproduct.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ProxyProductUpsert) UpdateDescription() *ProxyProductUpsert {
	u.SetExcluded(proxyproduct.FieldDescription)
	return u
}

// SetDurationDays sets the "duration_days" field.
func (u *ProxyProductUpsert) SetDurationDays(v int) *ProxyProductUpsert {
	u.Set(proxyproduct.FieldDurationDays, v)
	return u
}

// UpdateDurationDays sets the "duration_days" field to the value that was provided on create.
func (u *ProxyProductUpsert) UpdateDurationDays() *ProxyProductUpsert {
	u.SetExcluded(proxyproduct.FieldDurationDays)
	return u
}

// AddDurationDays adds v to the "duration_days" field.
func (u *ProxyProductUpsert) AddDurationDays(v int) *ProxyProductUpsert {
	u.Add(proxyproduct.FieldDurationDays, v)
	return u
}

// SetTrafficLimitGB sets the "traffic_limit_gb" field.
func (u *ProxyProductUpsert) SetTrafficLimitGB(v int) *ProxyProductUpsert {
	u.Set(proxyproduct.FieldTrafficLimitGB, v)
	return u
}

// UpdateTrafficLimitGB sets the "traffic_limit_gb" field to the value that was provided on create.
func (u *ProxyProductUpsert) UpdateTrafficLimitGB() *ProxyProductUpsert {
	u.SetExcluded(proxyproduct.FieldTrafficLimitGB)
	return u
}

// AddTrafficLimitGB adds v to the "traffic_limit_gb" field.
func (u *ProxyProductUpsert) AddTrafficLimitGB(v int) *ProxyProductUpsert {
	u.Add(proxyproduct.FieldTrafficLimitGB, v)
	return u
}

// SetPrice sets the "price" field.
func (u *ProxyProductUpsert) SetPrice(v decimal.Decimal) *ProxyProductUpsert {
	u.Set(proxyproduct.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ProxyProductUpsert) UpdatePrice() *ProxyProductUpsert {
	u.SetExcluded(proxyproduct.FieldPrice)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *ProxyProductUpsert) SetSortOrder(v int) *ProxyProductUpsert {
	u.Set(proxyproduct.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ProxyProductUpsert) UpdateSortOrder() *ProxyProductUpsert {
	u.SetExcluded(proxyproduct.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ProxyProductUpsert) AddSortOrder(v int) *ProxyProductUpsert {
	u.Add(proxyproduct.FieldSortOrder, v)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *ProxyProductUpsert) SetIsActive(v bool) *ProxyProductUpsert {
	u.Set(proxyproduct.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *ProxyProductUpsert) UpdateIsActive() *ProxyProductUpsert {
	u.SetExcluded(proxyproduct.FieldIsActive)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProxyProduct.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxyProductUpsertOne) UpdateNewValues() *ProxyProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(proxyproduct.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxyProduct.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProxyProductUpsertOne) Ignore() *ProxyProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyProductUpsertOne) DoNothing() *ProxyProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyProductCreate.OnConflict
// documentation for more info.
func (u *ProxyProductUpsertOne) Update(set func(*ProxyProductUpsert)) *ProxyProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyProductUpsertOne) SetUpdatedAt(v time.Time) *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyProductUpsertOne) UpdateUpdatedAt() *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *ProxyProductUpsertOne) SetName(v string) *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxyProductUpsertOne) UpdateName() *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ProxyProductUpsertOne) SetDescription(v string) *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ProxyProductUpsertOne) UpdateDescription() *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.UpdateDescription()
	})
}

// SetDurationDays sets the "duration_days" field.
func (u *ProxyProductUpsertOne) SetDurationDays(v int) *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.SetDurationDays(v)
	})
}

// AddDurationDays adds v to the "duration_days" field.
func (u *ProxyProductUpsertOne) AddDurationDays(v int) *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.AddDurationDays(v)
	})
}

// UpdateDurationDays sets the "duration_days" field to the value that was provided on create.
func (u *ProxyProductUpsertOne) UpdateDurationDays() *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.UpdateDurationDays()
	})
}

// SetTrafficLimitGB sets the "traffic_limit_gb" field.
func (u *ProxyProductUpsertOne) SetTrafficLimitGB(v int) *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.SetTrafficLimitGB(v)
	})
}

// AddTrafficLimitGB adds v to the "traffic_limit_gb" field.
func (u *ProxyProductUpsertOne) AddTrafficLimitGB(v int) *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.AddTrafficLimitGB(v)
	})
}

// UpdateTrafficLimitGB sets the "traffic_limit_gb" field to the value that was provided on create.
func (u *ProxyProductUpsertOne) UpdateTrafficLimitGB() *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.UpdateTrafficLimitGB()
	})
}

// SetPrice sets the "price" field.
func (u *ProxyProductUpsertOne) SetPrice(v decimal.Decimal) *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.SetPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ProxyProductUpsertOne) UpdatePrice() *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.UpdatePrice()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ProxyProductUpsertOne) SetSortOrder(v int) *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ProxyProductUpsertOne) AddSortOrder(v int) *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ProxyProductUpsertOne) UpdateSortOrder() *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.UpdateSortOrder()
	})
}

// SetIsActive sets the "is_active" field.
func (u *ProxyProductUpsertOne) SetIsActive(v bool) *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *ProxyProductUpsertOne) UpdateIsActive() *ProxyProductUpsertOne {
	return u.Update(func(s *ProxyProductUpsert) {
		s.UpdateIsActive()
	})
}

// Exec executes the query.
func (u *ProxyProductUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyProductCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyProductUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProxyProductUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProxyProductUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProxyProductCreateBulk is the builder for creating many ProxyProduct entities in bulk.
type ProxyProductCreateBulk struct {
	config
	err      error
	builders []*ProxyProductCreate
	conflict []sql.ConflictOption
}

// Save creates the ProxyProduct entities in the database.
func (_c *ProxyProductCreateBulk) Save(ctx context.Context) ([]*ProxyProduct, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxyProduct, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxyProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxyProductCreateBulk) SaveX(ctx context.Context) []*ProxyProduct {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyProductCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyProductCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxyProduct.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyProductUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyProductCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProxyProductUpsertBulk {
	_c.conflict = opts
	return &ProxyProductUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxyProduct.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyProductCreateBulk) OnConflictColumns(columns ...string) *ProxyProductUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyProductUpsertBulk{
		create: _c,
	}
}

// ProxyProductUpsertBulk is the builder for "upsert"-ing
// a bulk of ProxyProduct nodes.
type ProxyProductUpsertBulk struct {
	create *ProxyProductCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProxyProduct.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxyProductUpsertBulk) UpdateNewValues() *ProxyProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(proxyproduct.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxyProduct.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProxyProductUpsertBulk) Ignore() *ProxyProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyProductUpsertBulk) DoNothing() *ProxyProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyProductCreateBulk.OnConflict
// documentation for more info.
func (u *ProxyProductUpsertBulk) Update(set func(*ProxyProductUpsert)) *ProxyProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyProductUpsertBulk) SetUpdatedAt(v time.Time) *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyProductUpsertBulk) UpdateUpdatedAt() *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *ProxyProductUpsertBulk) SetName(v string) *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxyProductUpsertBulk) UpdateName() *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ProxyProductUpsertBulk) SetDescription(v string) *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ProxyProductUpsertBulk) UpdateDescription() *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.UpdateDescription()
	})
}

// SetDurationDays sets the "duration_days" field.
func (u *ProxyProductUpsertBulk) SetDurationDays(v int) *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.SetDurationDays(v)
	})
}

// AddDurationDays adds v to the "duration_days" field.
func (u *ProxyProductUpsertBulk) AddDurationDays(v int) *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.AddDurationDays(v)
	})
}

// UpdateDurationDays sets the "duration_days" field to the value that was provided on create.
func (u *ProxyProductUpsertBulk) UpdateDurationDays() *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.UpdateDurationDays()
	})
}

// SetTrafficLimitGB sets the "traffic_limit_gb" field.
func (u *ProxyProductUpsertBulk) SetTrafficLimitGB(v int) *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.SetTrafficLimitGB(v)
	})
}

// AddTrafficLimitGB adds v to the "traffic_limit_gb" field.
func (u *ProxyProductUpsertBulk) AddTrafficLimitGB(v int) *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.AddTrafficLimitGB(v)
	})
}

// UpdateTrafficLimitGB sets the "traffic_limit_gb" field to the value that was provided on create.
func (u *ProxyProductUpsertBulk) UpdateTrafficLimitGB() *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.UpdateTrafficLimitGB()
	})
}

// SetPrice sets the "price" field.
func (u *ProxyProductUpsertBulk) SetPrice(v decimal.Decimal) *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.SetPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ProxyProductUpsertBulk) UpdatePrice() *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.UpdatePrice()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ProxyProductUpsertBulk) SetSortOrder(v int) *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ProxyProductUpsertBulk) AddSortOrder(v int) *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ProxyProductUpsertBulk) UpdateSortOrder() *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.UpdateSortOrder()
	})
}

// SetIsActive sets the "is_active" field.
func (u *ProxyProductUpsertBulk) SetIsActive(v bool) *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *ProxyProductUpsertBulk) UpdateIsActive() *ProxyProductUpsertBulk {
	return u.Update(func(s *ProxyProductUpsert) {
		s.UpdateIsActive()
	})
}

// Exec executes the query.
func (u *ProxyProductUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProxyProductCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyProductCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyProductUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
