// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/meitianwang/fast-frame/ent/predicate"
	"github.com/meitianwang/fast-frame/ent/proxycredential"
	"github.com/meitianwang/fast-frame/ent/proxyrental"
)

// ProxyCredentialUpdate is the builder for updating ProxyCredential entities.
type ProxyCredentialUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyCredentialMutation
}

// Where appends a list predicates to the ProxyCredentialUpdate builder.
func (_u *ProxyCredentialUpdate) Where(ps ...predicate.ProxyCredential) *ProxyCredentialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyCredentialUpdate) SetUpdatedAt(v time.Time) *ProxyCredentialUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRentalID sets the "rental_id" field.
func (_u *ProxyCredentialUpdate) SetRentalID(v int64) *ProxyCredentialUpdate {
	_u.mutation.SetRentalID(v)
	return _u
}

// SetNillableRentalID sets the "rental_id" field if the given value is not nil.
func (_u *ProxyCredentialUpdate) SetNillableRentalID(v *int64) *ProxyCredentialUpdate {
	if v != nil {
		_u.SetRentalID(*v)
	}
	return _u
}

// SetHTTPUsername sets the "http_username" field.
func (_u *ProxyCredentialUpdate) SetHTTPUsername(v string) *ProxyCredentialUpdate {
	_u.mutation.SetHTTPUsername(v)
	return _u
}

// SetNillableHTTPUsername sets the "http_username" field if the given value is not nil.
func (_u *ProxyCredentialUpdate) SetNillableHTTPUsername(v *string) *ProxyCredentialUpdate {
	if v != nil {
		_u.SetHTTPUsername(*v)
	}
	return _u
}

// SetHTTPPassword sets the "http_password" field.
func (_u *ProxyCredentialUpdate) SetHTTPPassword(v string) *ProxyCredentialUpdate {
	_u.mutation.SetHTTPPassword(v)
	return _u
}

// SetNillableHTTPPassword sets the "http_password" field if the given value is not nil.
func (_u *ProxyCredentialUpdate) SetNillableHTTPPassword(v *string) *ProxyCredentialUpdate {
	if v != nil {
		_u.SetHTTPPassword(*v)
	}
	return _u
}

// SetVlessUUID sets the "vless_uuid" field.
func (_u *ProxyCredentialUpdate) SetVlessUUID(v string) *ProxyCredentialUpdate {
	_u.mutation.SetVlessUUID(v)
	return _u
}

// SetNillableVlessUUID sets the "vless_uuid" field if the given value is not nil.
func (_u *ProxyCredentialUpdate) SetNillableVlessUUID(v *string) *ProxyCredentialUpdate {
	if v != nil {
		_u.SetVlessUUID(*v)
	}
	return _u
}

// SetVlessLink sets the "vless_link" field.
func (_u *ProxyCredentialUpdate) SetVlessLink(v string) *ProxyCredentialUpdate {
	_u.mutation.SetVlessLink(v)
	return _u
}

// SetNillableVlessLink sets the "vless_link" field if the given value is not nil.
func (_u *ProxyCredentialUpdate) SetNillableVlessLink(v *string) *ProxyCredentialUpdate {
	if v != nil {
		_u.SetVlessLink(*v)
	}
	return _u
}

// SetRental sets the "rental" edge to the ProxyRental entity.
func (_u *ProxyCredentialUpdate) SetRental(v *ProxyRental) *ProxyCredentialUpdate {
	return _u.SetRentalID(v.ID)
}

// Mutation returns the ProxyCredentialMutation object of the builder.
func (_u *ProxyCredentialUpdate) Mutation() *ProxyCredentialMutation {
	return _u.mutation
}

// ClearRental clears the "rental" edge to the ProxyRental entity.
func (_u *ProxyCredentialUpdate) ClearRental() *ProxyCredentialUpdate {
	_u.mutation.ClearRental()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyCredentialUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyCredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxyCredentialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyCredentialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyCredentialUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxycredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyCredentialUpdate) check() error {
	if v, ok := _u.mutation.HTTPUsername(); ok {
		if err := proxycredential.HTTPUsernameValidator(v); err != nil {
			return &ValidationError{Name: "http_username", err: fmt.Errorf(`ent: validator failed for field "ProxyCredential.http_username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HTTPPassword(); ok {
		if err := proxycredential.HTTPPasswordValidator(v); err != nil {
			return &ValidationError{Name: "http_password", err: fmt.Errorf(`ent: validator failed for field "ProxyCredential.http_password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VlessUUID(); ok {
		if err := proxycredential.VlessUUIDValidator(v); err != nil {
			return &ValidationError{Name: "vless_uuid", err: fmt.Errorf(`ent: validator failed for field "ProxyCredential.vless_uuid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VlessLink(); ok {
		if err := proxycredential.VlessLinkValidator(v); err != nil {
			return &ValidationError{Name: "vless_link", err: fmt.Errorf(`ent: validator failed for field "ProxyCredential.vless_link": %w`, err)}
		}
	}
	if _u.mutation.RentalCleared() && len(_u.mutation.RentalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProxyCredential.rental"`)
	}
	return nil
}

func (_u *ProxyCredentialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxycredential.Table, proxycredential.Columns, sqlgraph.NewFieldSpec(proxycredential.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxycredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HTTPUsername(); ok {
		_spec.SetField(proxycredential.FieldHTTPUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.HTTPPassword(); ok {
		_spec.SetField(proxycredential.FieldHTTPPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.VlessUUID(); ok {
		_spec.SetField(proxycredential.FieldVlessUUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.VlessLink(); ok {
		_spec.SetField(proxycredential.FieldVlessLink, field.TypeString, value)
	}
	if _u.mutation.RentalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   proxycredential.RentalTable,
			Columns: []string{proxycredential.RentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RentalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   proxycredential.RentalTable,
			Columns: []string{proxycredential.RentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxycredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxyCredentialUpdateOne is the builder for updating a single ProxyCredential entity.
type ProxyCredentialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyCredentialMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyCredentialUpdateOne) SetUpdatedAt(v time.Time) *ProxyCredentialUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRentalID sets the "rental_id" field.
func (_u *ProxyCredentialUpdateOne) SetRentalID(v int64) *ProxyCredentialUpdateOne {
	_u.mutation.SetRentalID(v)
	return _u
}

// SetNillableRentalID sets the "rental_id" field if the given value is not nil.
func (_u *ProxyCredentialUpdateOne) SetNillableRentalID(v *int64) *ProxyCredentialUpdateOne {
	if v != nil {
		_u.SetRentalID(*v)
	}
	return _u
}

// SetHTTPUsername sets the "http_username" field.
func (_u *ProxyCredentialUpdateOne) SetHTTPUsername(v string) *ProxyCredentialUpdateOne {
	_u.mutation.SetHTTPUsername(v)
	return _u
}

// SetNillableHTTPUsername sets the "http_username" field if the given value is not nil.
func (_u *ProxyCredentialUpdateOne) SetNillableHTTPUsername(v *string) *ProxyCredentialUpdateOne {
	if v != nil {
		_u.SetHTTPUsername(*v)
	}
	return _u
}

// SetHTTPPassword sets the "http_password" field.
func (_u *ProxyCredentialUpdateOne) SetHTTPPassword(v string) *ProxyCredentialUpdateOne {
	_u.mutation.SetHTTPPassword(v)
	return _u
}

// SetNillableHTTPPassword sets the "http_password" field if the given value is not nil.
func (_u *ProxyCredentialUpdateOne) SetNillableHTTPPassword(v *string) *ProxyCredentialUpdateOne {
	if v != nil {
		_u.SetHTTPPassword(*v)
	}
	return _u
}

// SetVlessUUID sets the "vless_uuid" field.
func (_u *ProxyCredentialUpdateOne) SetVlessUUID(v string) *ProxyCredentialUpdateOne {
	_u.mutation.SetVlessUUID(v)
	return _u
}

// SetNillableVlessUUID sets the "vless_uuid" field if the given value is not nil.
func (_u *ProxyCredentialUpdateOne) SetNillableVlessUUID(v *string) *ProxyCredentialUpdateOne {
	if v != nil {
		_u.SetVlessUUID(*v)
	}
	return _u
}

// SetVlessLink sets the "vless_link" field.
func (_u *ProxyCredentialUpdateOne) SetVlessLink(v string) *ProxyCredentialUpdateOne {
	_u.mutation.SetVlessLink(v)
	return _u
}

// SetNillableVlessLink sets the "vless_link" field if the given value is not nil.
func (_u *ProxyCredentialUpdateOne) SetNillableVlessLink(v *string) *ProxyCredentialUpdateOne {
	if v != nil {
		_u.SetVlessLink(*v)
	}
	return _u
}

// SetRental sets the "rental" edge to the ProxyRental entity.
func (_u *ProxyCredentialUpdateOne) SetRental(v *ProxyRental) *ProxyCredentialUpdateOne {
	return _u.SetRentalID(v.ID)
}

// Mutation returns the ProxyCredentialMutation object of the builder.
func (_u *ProxyCredentialUpdateOne) Mutation() *ProxyCredentialMutation {
	return _u.mutation
}

// ClearRental clears the "rental" edge to the ProxyRental entity.
func (_u *ProxyCredentialUpdateOne) ClearRental() *ProxyCredentialUpdateOne {
	_u.mutation.ClearRental()
	return _u
}

// Where appends a list predicates to the ProxyCredentialUpdate builder.
func (_u *ProxyCredentialUpdateOne) Where(ps ...predicate.ProxyCredential) *ProxyCredentialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyCredentialUpdateOne) Select(field string, fields ...string) *ProxyCredentialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxyCredential entity.
func (_u *ProxyCredentialUpdateOne) Save(ctx context.Context) (*ProxyCredential, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyCredentialUpdateOne) SaveX(ctx context.Context) *ProxyCredential {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxyCredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyCredentialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyCredentialUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxycredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyCredentialUpdateOne) check() error {
	if v, ok := _u.mutation.HTTPUsername(); ok {
		if err := proxycredential.HTTPUsernameValidator(v); err != nil {
			return &ValidationError{Name: "http_username", err: fmt.Errorf(`ent: validator failed for field "ProxyCredential.http_username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HTTPPassword(); ok {
		if err := proxycredential.HTTPPasswordValidator(v); err != nil {
			return &ValidationError{Name: "http_password", err: fmt.Errorf(`ent: validator failed for field "ProxyCredential.http_password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VlessUUID(); ok {
		if err := proxycredential.VlessUUIDValidator(v); err != nil {
			return &ValidationError{Name: "vless_uuid", err: fmt.Errorf(`ent: validator failed for field "ProxyCredential.vless_uuid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VlessLink(); ok {
		if err := proxycredential.VlessLinkValidator(v); err != nil {
			return &ValidationError{Name: "vless_link", err: fmt.Errorf(`ent: validator failed for field "ProxyCredential.vless_link": %w`, err)}
		}
	}
	if _u.mutation.RentalCleared() && len(_u.mutation.RentalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProxyCredential.rental"`)
	}
	return nil
}

func (_u *ProxyCredentialUpdateOne) sqlSave(ctx context.Context) (_node *ProxyCredential, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxycredential.Table, proxycredential.Columns, sqlgraph.NewFieldSpec(proxycredential.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxyCredential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxycredential.FieldID)
		for _, f := range fields {
			if !proxycredential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxycredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxycredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HTTPUsername(); ok {
		_spec.SetField(proxycredential.FieldHTTPUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.HTTPPassword(); ok {
		_spec.SetField(proxycredential.FieldHTTPPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.VlessUUID(); ok {
		_spec.SetField(proxycredential.FieldVlessUUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.VlessLink(); ok {
		_spec.SetField(proxycredential.FieldVlessLink, field.TypeString, value)
	}
	if _u.mutation.RentalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   proxycredential.RentalTable,
			Columns: []string{proxycredential.RentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RentalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   proxycredential.RentalTable,
			Columns: []string{proxycredential.RentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProxyCredential{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxycredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
