// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/meitianwang/fast-frame/ent/predicate"
	"github.com/meitianwang/fast-frame/ent/proxyrental"
)

// ProxyRentalDelete is the builder for deleting a ProxyRental entity.
type ProxyRentalDelete struct {
	config
	hooks    []Hook
	mutation *ProxyRentalMutation
}

// Where appends a list predicates to the ProxyRentalDelete builder.
func (_d *ProxyRentalDelete) Where(ps ...predicate.ProxyRental) *ProxyRentalDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProxyRentalDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProxyRentalDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProxyRentalDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(proxyrental.Table, sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProxyRentalDeleteOne is the builder for deleting a single ProxyRental entity.
type ProxyRentalDeleteOne struct {
	_d *ProxyRentalDelete
}

// Where appends a list predicates to the ProxyRentalDelete builder.
func (_d *ProxyRentalDeleteOne) Where(ps ...predicate.ProxyRental) *ProxyRentalDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProxyRentalDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{proxyrental.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProxyRentalDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
