// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/meitianwang/fast-frame/ent/proxynode"
	"github.com/meitianwang/fast-frame/ent/proxyrental"
)

// ProxyNodeCreate is the builder for creating a ProxyNode entity.
type ProxyNodeCreate struct {
	config
	mutation *ProxyNodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxyNodeCreate) SetCreatedAt(v time.Time) *ProxyNodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxyNodeCreate) SetNillableCreatedAt(v *time.Time) *ProxyNodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxyNodeCreate) SetUpdatedAt(v time.Time) *ProxyNodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxyNodeCreate) SetNillableUpdatedAt(v *time.Time) *ProxyNodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ProxyNodeCreate) SetDeletedAt(v time.Time) *ProxyNodeCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ProxyNodeCreate) SetNillableDeletedAt(v *time.Time) *ProxyNodeCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *ProxyNodeCreate) SetIPAddress(v string) *ProxyNodeCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetCountry sets the "country" field.
func (_c *ProxyNodeCreate) SetCountry(v string) *ProxyNodeCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_c *ProxyNodeCreate) SetNillableCountry(v *string) *ProxyNodeCreate {
	if v != nil {
		_c.SetCountry(*v)
	}
	return _c
}

// SetCountryCode sets the "country_code" field.
func (_c *ProxyNodeCreate) SetCountryCode(v string) *ProxyNodeCreate {
	_c.mutation.SetCountryCode(v)
	return _c
}

// SetNillableCountryCode sets the "country_code" field if the given value is not nil.
func (_c *ProxyNodeCreate) SetNillableCountryCode(v *string) *ProxyNodeCreate {
	if v != nil {
		_c.SetCountryCode(*v)
	}
	return _c
}

// SetCity sets the "city" field.
func (_c *ProxyNodeCreate) SetCity(v string) *ProxyNodeCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_c *ProxyNodeCreate) SetNillableCity(v *string) *ProxyNodeCreate {
	if v != nil {
		_c.SetCity(*v)
	}
	return _c
}

// SetIsp sets the "isp" field.
func (_c *ProxyNodeCreate) SetIsp(v string) *ProxyNodeCreate {
	_c.mutation.SetIsp(v)
	return _c
}

// SetNillableIsp sets the "isp" field if the given value is not nil.
func (_c *ProxyNodeCreate) SetNillableIsp(v *string) *ProxyNodeCreate {
	if v != nil {
		_c.SetIsp(*v)
	}
	return _c
}

// SetHTTPPort sets the "http_port" field.
func (_c *ProxyNodeCreate) SetHTTPPort(v int) *ProxyNodeCreate {
	_c.mutation.SetHTTPPort(v)
	return _c
}

// SetNillableHTTPPort sets the "http_port" field if the given value is not nil.
func (_c *ProxyNodeCreate) SetNillableHTTPPort(v *int) *ProxyNodeCreate {
	if v != nil {
		_c.SetHTTPPort(*v)
	}
	return _c
}

// SetVlessPort sets the "vless_port" field.
func (_c *ProxyNodeCreate) SetVlessPort(v int) *ProxyNodeCreate {
	_c.mutation.SetVlessPort(v)
	return _c
}

// SetNillableVlessPort sets the "vless_port" field if the given value is not nil.
func (_c *ProxyNodeCreate) SetNillableVlessPort(v *int) *ProxyNodeCreate {
	if v != nil {
		_c.SetVlessPort(*v)
	}
	return _c
}

// SetVlessNetwork sets the "vless_network" field.
func (_c *ProxyNodeCreate) SetVlessNetwork(v string) *ProxyNodeCreate {
	_c.mutation.SetVlessNetwork(v)
	return _c
}

// SetNillableVlessNetwork sets the "vless_network" field if the given value is not nil.
func (_c *ProxyNodeCreate) SetNillableVlessNetwork(v *string) *ProxyNodeCreate {
	if v != nil {
		_c.SetVlessNetwork(*v)
	}
	return _c
}

// SetVlessTLS sets the "vless_tls" field.
func (_c *ProxyNodeCreate) SetVlessTLS(v bool) *ProxyNodeCreate {
	_c.mutation.SetVlessTLS(v)
	return _c
}

// SetNillableVlessTLS sets the "vless_tls" field if the given value is not nil.
func (_c *ProxyNodeCreate) SetNillableVlessTLS(v *bool) *ProxyNodeCreate {
	if v != nil {
		_c.SetVlessTLS(*v)
	}
	return _c
}

// SetVlessSni sets the "vless_sni" field.
func (_c *ProxyNodeCreate) SetVlessSni(v string) *ProxyNodeCreate {
	_c.mutation.SetVlessSni(v)
	return _c
}

// SetNillableVlessSni sets the "vless_sni" field if the given value is not nil.
func (_c *ProxyNodeCreate) SetNillableVlessSni(v *string) *ProxyNodeCreate {
	if v != nil {
		_c.SetVlessSni(*v)
	}
	return _c
}

// SetVlessWsPath sets the "vless_ws_path" field.
func (_c *ProxyNodeCreate) SetVlessWsPath(v string) *ProxyNodeCreate {
	_c.mutation.SetVlessWsPath(v)
	return _c
}

// SetNillableVlessWsPath sets the "vless_ws_path" field if the given value is not nil.
func (_c *ProxyNodeCreate) SetNillableVlessWsPath(v *string) *ProxyNodeCreate {
	if v != nil {
		_c.SetVlessWsPath(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *ProxyNodeCreate) SetTags(v []string) *ProxyNodeCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProxyNodeCreate) SetStatus(v string) *ProxyNodeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProxyNodeCreate) SetNillableStatus(v *string) *ProxyNodeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ProxyNodeCreate) SetDescription(v string) *ProxyNodeCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ProxyNodeCreate) SetNillableDescription(v *string) *ProxyNodeCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// AddRentalIDs adds the "rentals" edge to the ProxyRental entity by IDs.
func (_c *ProxyNodeCreate) AddRentalIDs(ids ...int64) *ProxyNodeCreate {
	_c.mutation.AddRentalIDs(ids...)
	return _c
}

// AddRentals adds the "rentals" edges to the ProxyRental entity.
func (_c *ProxyNodeCreate) AddRentals(v ...*ProxyRental) *ProxyNodeCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRentalIDs(ids...)
}

// Mutation returns the ProxyNodeMutation object of the builder.
func (_c *ProxyNodeCreate) Mutation() *ProxyNodeMutation {
	return _c.mutation
}

// Save creates the ProxyNode in the database.
func (_c *ProxyNodeCreate) Save(ctx context.Context) (*ProxyNode, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxyNodeCreate) SaveX(ctx context.Context) *ProxyNode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyNodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyNodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxyNodeCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if proxynode.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxynode.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := proxynode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if proxynode.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxynode.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proxynode.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Country(); !ok {
		v := proxynode.DefaultCountry
		_c.mutation.SetCountry(v)
	}
	if _, ok := _c.mutation.CountryCode(); !ok {
		v := proxynode.DefaultCountryCode
		_c.mutation.SetCountryCode(v)
	}
	if _, ok := _c.mutation.City(); !ok {
		v := proxynode.DefaultCity
		_c.mutation.SetCity(v)
	}
	if _, ok := _c.mutation.Isp(); !ok {
		v := proxynode.DefaultIsp
		_c.mutation.SetIsp(v)
	}
	if _, ok := _c.mutation.HTTPPort(); !ok {
		v := proxynode.DefaultHTTPPort
		_c.mutation.SetHTTPPort(v)
	}
	if _, ok := _c.mutation.VlessPort(); !ok {
		v := proxynode.DefaultVlessPort
		_c.mutation.SetVlessPort(v)
	}
	if _, ok := _c.mutation.VlessNetwork(); !ok {
		v := proxynode.DefaultVlessNetwork
		_c.mutation.SetVlessNetwork(v)
	}
	if _, ok := _c.mutation.VlessTLS(); !ok {
		v := proxynode.DefaultVlessTLS
		_c.mutation.SetVlessTLS(v)
	}
	if _, ok := _c.mutation.VlessSni(); !ok {
		v := proxynode.DefaultVlessSni
		_c.mutation.SetVlessSni(v)
	}
	if _, ok := _c.mutation.VlessWsPath(); !ok {
		v := proxynode.DefaultVlessWsPath
		_c.mutation.SetVlessWsPath(v)
	}
	if _, ok := _c.mutation.Tags(); !ok {
		v := proxynode.DefaultTags
		_c.mutation.SetTags(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := proxynode.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := proxynode.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxyNodeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxyNode.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxyNode.updated_at"`)}
	}
	if _, ok := _c.mutation.IPAddress(); !ok {
		return &ValidationError{Name: "ip_address", err: errors.New(`ent: missing required field "ProxyNode.ip_address"`)}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := proxynode.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.ip_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Country(); !ok {
		return &ValidationError{Name: "country", err: errors.New(`ent: missing required field "ProxyNode.country"`)}
	}
	if v, ok := _c.mutation.Country(); ok {
		if err := proxynode.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.country": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CountryCode(); !ok {
		return &ValidationError{Name: "country_code", err: errors.New(`ent: missing required field "ProxyNode.country_code"`)}
	}
	if v, ok := _c.mutation.CountryCode(); ok {
		if err := proxynode.CountryCodeValidator(v); err != nil {
			return &ValidationError{Name: "country_code", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.country_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.City(); !ok {
		return &ValidationError{Name: "city", err: errors.New(`ent: missing required field "ProxyNode.city"`)}
	}
	if v, ok := _c.mutation.City(); ok {
		if err := proxynode.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.city": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Isp(); !ok {
		return &ValidationError{Name: "isp", err: errors.New(`ent: missing required field "ProxyNode.isp"`)}
	}
	if v, ok := _c.mutation.Isp(); ok {
		if err := proxynode.IspValidator(v); err != nil {
			return &ValidationError{Name: "isp", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.isp": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HTTPPort(); !ok {
		return &ValidationError{Name: "http_port", err: errors.New(`ent: missing required field "ProxyNode.http_port"`)}
	}
	if _, ok := _c.mutation.VlessPort(); !ok {
		return &ValidationError{Name: "vless_port", err: errors.New(`ent: missing required field "ProxyNode.vless_port"`)}
	}
	if _, ok := _c.mutation.VlessNetwork(); !ok {
		return &ValidationError{Name: "vless_network", err: errors.New(`ent: missing required field "ProxyNode.vless_network"`)}
	}
	if v, ok := _c.mutation.VlessNetwork(); ok {
		if err := proxynode.VlessNetworkValidator(v); err != nil {
			return &ValidationError{Name: "vless_network", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.vless_network": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VlessTLS(); !ok {
		return &ValidationError{Name: "vless_tls", err: errors.New(`ent: missing required field "ProxyNode.vless_tls"`)}
	}
	if _, ok := _c.mutation.VlessSni(); !ok {
		return &ValidationError{Name: "vless_sni", err: errors.New(`ent: missing required field "ProxyNode.vless_sni"`)}
	}
	if v, ok := _c.mutation.VlessSni(); ok {
		if err := proxynode.VlessSniValidator(v); err != nil {
			return &ValidationError{Name: "vless_sni", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.vless_sni": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VlessWsPath(); !ok {
		return &ValidationError{Name: "vless_ws_path", err: errors.New(`ent: missing required field "ProxyNode.vless_ws_path"`)}
	}
	if v, ok := _c.mutation.VlessWsPath(); ok {
		if err := proxynode.VlessWsPathValidator(v); err != nil {
			return &ValidationError{Name: "vless_ws_path", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.vless_ws_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "ProxyNode.tags"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ProxyNode.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := proxynode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProxyNode.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "ProxyNode.description"`)}
	}
	return nil
}

func (_c *ProxyNodeCreate) sqlSave(ctx context.Context) (*ProxyNode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxyNodeCreate) createSpec() (*ProxyNode, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxyNode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxynode.Table, sqlgraph.NewFieldSpec(proxynode.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxynode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxynode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(proxynode.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(proxynode.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(proxynode.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := _c.mutation.CountryCode(); ok {
		_spec.SetField(proxynode.FieldCountryCode, field.TypeString, value)
		_node.CountryCode = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(proxynode.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.Isp(); ok {
		_spec.SetField(proxynode.FieldIsp, field.TypeString, value)
		_node.Isp = value
	}
	if value, ok := _c.mutation.HTTPPort(); ok {
		_spec.SetField(proxynode.FieldHTTPPort, field.TypeInt, value)
		_node.HTTPPort = value
	}
	if value, ok := _c.mutation.VlessPort(); ok {
		_spec.SetField(proxynode.FieldVlessPort, field.TypeInt, value)
		_node.VlessPort = value
	}
	if value, ok := _c.mutation.VlessNetwork(); ok {
		_spec.SetField(proxynode.FieldVlessNetwork, field.TypeString, value)
		_node.VlessNetwork = value
	}
	if value, ok := _c.mutation.VlessTLS(); ok {
		_spec.SetField(proxynode.FieldVlessTLS, field.TypeBool, value)
		_node.VlessTLS = value
	}
	if value, ok := _c.mutation.VlessSni(); ok {
		_spec.SetField(proxynode.FieldVlessSni, field.TypeString, value)
		_node.VlessSni = value
	}
	if value, ok := _c.mutation.VlessWsPath(); ok {
		_spec.SetField(proxynode.FieldVlessWsPath, field.TypeString, value)
		_node.VlessWsPath = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(proxynode.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(proxynode.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(proxynode.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := _c.mutation.RentalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxynode.RentalsTable,
			Columns: []string{proxynode.RentalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxyNode.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyNodeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyNodeCreate) OnConflict(opts ...sql.ConflictOption) *ProxyNodeUpsertOne {
	_c.conflict = opts
	return &ProxyNodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxyNode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyNodeCreate) OnConflictColumns(columns ...string) *ProxyNodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyNodeUpsertOne{
		create: _c,
	}
}

type (
	// ProxyNodeUpsertOne is the builder for "upsert"-ing
	//  one ProxyNode node.
	ProxyNodeUpsertOne struct {
		create *ProxyNodeCreate
	}

	// ProxyNodeUpsert is the "OnConflict" setter.
	ProxyNodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyNodeUpsert) SetUpdatedAt(v time.Time) *ProxyNodeUpsert {
	u.Set(proxynode.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyNodeUpsert) UpdateUpdatedAt() *ProxyNodeUpsert {
	u.SetExcluded(proxynode.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProxyNodeUpsert) SetDeletedAt(v time.Time) *ProxyNodeUpsert {
	u.Set(proxynode.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProxyNodeUpsert) UpdateDeletedAt() *ProxyNodeUpsert {
	u.SetExcluded(proxynode.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProxyNodeUpsert) ClearDeletedAt() *ProxyNodeUpsert {
	u.SetNull(proxynode.FieldDeletedAt)
	return u
}

// SetIPAddress sets the "ip_address" field.
func (u *ProxyNodeUpsert) SetIPAddress(v string) *ProxyNodeUpsert {
	u.Set(proxynode.FieldIPAddress, v)
	return u
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *ProxyNodeUpsert) UpdateIPAddress() *ProxyNodeUpsert {
	u.SetExcluded(proxynode.FieldIPAddress)
	return u
}

// SetCountry sets the "country" field.
func (u *ProxyNodeUpsert) SetCountry(v string) *ProxyNodeUpsert {
	u.Set(proxynode.FieldCountry, v)
	return u
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *ProxyNodeUpsert) UpdateCountry() *ProxyNodeUpsert {
	u.SetExcluded(proxynode.FieldCountry)
	return u
}

// SetCountryCode sets the "country_code" field.
func (u *ProxyNodeUpsert) SetCountryCode(v string) *ProxyNodeUpsert {
	u.Set(proxynode.FieldCountryCode, v)
	return u
}

// UpdateCountryCode sets the "country_code" field to the value that was provided on create.
func (u *ProxyNodeUpsert) UpdateCountryCode() *ProxyNodeUpsert {
	u.SetExcluded(proxynode.FieldCountryCode)
	return u
}

// SetCity sets the "city" field.
func (u *ProxyNodeUpsert) SetCity(v string) *ProxyNodeUpsert {
	u.Set(proxynode.FieldCity, v)
	return u
}

// UpdateCity sets the "city" field to the value that was provided on create.
func (u *ProxyNodeUpsert) UpdateCity() *ProxyNodeUpsert {
	u.SetExcluded(proxynode.FieldCity)
	return u
}

// SetIsp sets the "isp" field.
func (u *ProxyNodeUpsert) SetIsp(v string) *ProxyNodeUpsert {
	u.Set(proxynode.FieldIsp, v)
	return u
}

// UpdateIsp sets the "isp" field to the value that was provided on create.
func (u *ProxyNodeUpsert) UpdateIsp() *ProxyNodeUpsert {
	u.SetExcluded(proxynode.FieldIsp)
	return u
}

// SetHTTPPort sets the "http_port" field.
func (u *ProxyNodeUpsert) SetHTTPPort(v int) *ProxyNodeUpsert {
	u.Set(proxynode.FieldHTTPPort, v)
	return u
}

// UpdateHTTPPort sets the "http_port" field to the value that was provided on create.
func (u *ProxyNodeUpsert) UpdateHTTPPort() *ProxyNodeUpsert {
	u.SetExcluded(proxynode.FieldHTTPPort)
	return u
}

// AddHTTPPort adds v to the "http_port" field.
func (u *ProxyNodeUpsert) AddHTTPPort(v int) *ProxyNodeUpsert {
	u.Add(proxynode.FieldHTTPPort, v)
	return u
}

// SetVlessPort sets the "vless_port" field.
func (u *ProxyNodeUpsert) SetVlessPort(v int) *ProxyNodeUpsert {
	u.Set(proxynode.FieldVlessPort, v)
	return u
}

// UpdateVlessPort sets the "vless_port" field to the value that was provided on create.
func (u *ProxyNodeUpsert) UpdateVlessPort() *ProxyNodeUpsert {
	u.SetExcluded(proxynode.FieldVlessPort)
	return u
}

// AddVlessPort adds v to the "vless_port" field.
func (u *ProxyNodeUpsert) AddVlessPort(v int) *ProxyNodeUpsert {
	u.Add(proxynode.FieldVlessPort, v)
	return u
}

// SetVlessNetwork sets the "vless_network" field.
func (u *ProxyNodeUpsert) SetVlessNetwork(v string) *ProxyNodeUpsert {
	u.Set(proxynode.FieldVlessNetwork, v)
	return u
}

// UpdateVlessNetwork sets the "vless_network" field to the value that was provided on create.
func (u *ProxyNodeUpsert) UpdateVlessNetwork() *ProxyNodeUpsert {
	u.SetExcluded(proxynode.FieldVlessNetwork)
	return u
}

// SetVlessTLS sets the "vless_tls" field.
func (u *ProxyNodeUpsert) SetVlessTLS(v bool) *ProxyNodeUpsert {
	u.Set(proxynode.FieldVlessTLS, v)
	return u
}

// UpdateVlessTLS sets the "vless_tls" field to the value that was provided on create.
func (u *ProxyNodeUpsert) UpdateVlessTLS() *ProxyNodeUpsert {
	u.SetExcluded(proxynode.FieldVlessTLS)
	return u
}

// SetVlessSni sets the "vless_sni" field.
func (u *ProxyNodeUpsert) SetVlessSni(v string) *ProxyNodeUpsert {
	u.Set(proxynode.FieldVlessSni, v)
	return u
}

// UpdateVlessSni sets the "vless_sni" field to the value that was provided on create.
func (u *ProxyNodeUpsert) UpdateVlessSni() *ProxyNodeUpsert {
	u.SetExcluded(proxynode.FieldVlessSni)
	return u
}

// SetVlessWsPath sets the "vless_ws_path" field.
func (u *ProxyNodeUpsert) SetVlessWsPath(v string) *ProxyNodeUpsert {
	u.Set(proxynode.FieldVlessWsPath, v)
	return u
}

// UpdateVlessWsPath sets the "vless_ws_path" field to the value that was provided on create.
func (u *ProxyNodeUpsert) UpdateVlessWsPath() *ProxyNodeUpsert {
	u.SetExcluded(proxynode.FieldVlessWsPath)
	return u
}

// SetTags sets the "tags" field.
func (u *ProxyNodeUpsert) SetTags(v []string) *ProxyNodeUpsert {
	u.Set(proxynode.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *ProxyNodeUpsert) UpdateTags() *ProxyNodeUpsert {
	u.SetExcluded(proxynode.FieldTags)
	return u
}

// SetStatus sets the "status" field.
func (u *ProxyNodeUpsert) SetStatus(v string) *ProxyNodeUpsert {
	u.Set(proxynode.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProxyNodeUpsert) UpdateStatus() *ProxyNodeUpsert {
	u.SetExcluded(proxynode.FieldStatus)
	return u
}

// SetDescription sets the "description" field.
func (u *ProxyNodeUpsert) SetDescription(v string) *ProxyNodeUpsert {
	u.Set(proxynode.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ProxyNodeUpsert) UpdateDescription() *ProxyNodeUpsert {
	u.SetExcluded(proxynode.FieldDescription)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProxyNode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxyNodeUpsertOne) UpdateNewValues() *ProxyNodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(proxynode.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxyNode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProxyNodeUpsertOne) Ignore() *ProxyNodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyNodeUpsertOne) DoNothing() *ProxyNodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyNodeCreate.OnConflict
// documentation for more info.
func (u *ProxyNodeUpsertOne) Update(set func(*ProxyNodeUpsert)) *ProxyNodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyNodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyNodeUpsertOne) SetUpdatedAt(v time.Time) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyNodeUpsertOne) UpdateUpdatedAt() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProxyNodeUpsertOne) SetDeletedAt(v time.Time) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProxyNodeUpsertOne) UpdateDeletedAt() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProxyNodeUpsertOne) ClearDeletedAt() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.ClearDeletedAt()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *ProxyNodeUpsertOne) SetIPAddress(v string) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *ProxyNodeUpsertOne) UpdateIPAddress() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateIPAddress()
	})
}

// SetCountry sets the "country" field.
func (u *ProxyNodeUpsertOne) SetCountry(v string) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetCountry(v)
	})
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *ProxyNodeUpsertOne) UpdateCountry() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateCountry()
	})
}

// SetCountryCode sets the "country_code" field.
func (u *ProxyNodeUpsertOne) SetCountryCode(v string) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetCountryCode(v)
	})
}

// UpdateCountryCode sets the "country_code" field to the value that was provided on create.
func (u *ProxyNodeUpsertOne) UpdateCountryCode() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateCountryCode()
	})
}

// SetCity sets the "city" field.
func (u *ProxyNodeUpsertOne) SetCity(v string) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetCity(v)
	})
}

// UpdateCity sets the "city" field to the value that was provided on create.
func (u *ProxyNodeUpsertOne) UpdateCity() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateCity()
	})
}

// SetIsp sets the "isp" field.
func (u *ProxyNodeUpsertOne) SetIsp(v string) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetIsp(v)
	})
}

// UpdateIsp sets the "isp" field to the value that was provided on create.
func (u *ProxyNodeUpsertOne) UpdateIsp() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateIsp()
	})
}

// SetHTTPPort sets the "http_port" field.
func (u *ProxyNodeUpsertOne) SetHTTPPort(v int) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetHTTPPort(v)
	})
}

// AddHTTPPort adds v to the "http_port" field.
func (u *ProxyNodeUpsertOne) AddHTTPPort(v int) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.AddHTTPPort(v)
	})
}

// UpdateHTTPPort sets the "http_port" field to the value that was provided on create.
func (u *ProxyNodeUpsertOne) UpdateHTTPPort() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateHTTPPort()
	})
}

// SetVlessPort sets the "vless_port" field.
func (u *ProxyNodeUpsertOne) SetVlessPort(v int) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetVlessPort(v)
	})
}

// AddVlessPort adds v to the "vless_port" field.
func (u *ProxyNodeUpsertOne) AddVlessPort(v int) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.AddVlessPort(v)
	})
}

// UpdateVlessPort sets the "vless_port" field to the value that was provided on create.
func (u *ProxyNodeUpsertOne) UpdateVlessPort() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateVlessPort()
	})
}

// SetVlessNetwork sets the "vless_network" field.
func (u *ProxyNodeUpsertOne) SetVlessNetwork(v string) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetVlessNetwork(v)
	})
}

// UpdateVlessNetwork sets the "vless_network" field to the value that was provided on create.
func (u *ProxyNodeUpsertOne) UpdateVlessNetwork() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateVlessNetwork()
	})
}

// SetVlessTLS sets the "vless_tls" field.
func (u *ProxyNodeUpsertOne) SetVlessTLS(v bool) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetVlessTLS(v)
	})
}

// UpdateVlessTLS sets the "vless_tls" field to the value that was provided on create.
func (u *ProxyNodeUpsertOne) UpdateVlessTLS() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateVlessTLS()
	})
}

// SetVlessSni sets the "vless_sni" field.
func (u *ProxyNodeUpsertOne) SetVlessSni(v string) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetVlessSni(v)
	})
}

// UpdateVlessSni sets the "vless_sni" field to the value that was provided on create.
func (u *ProxyNodeUpsertOne) UpdateVlessSni() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateVlessSni()
	})
}

// SetVlessWsPath sets the "vless_ws_path" field.
func (u *ProxyNodeUpsertOne) SetVlessWsPath(v string) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetVlessWsPath(v)
	})
}

// UpdateVlessWsPath sets the "vless_ws_path" field to the value that was provided on create.
func (u *ProxyNodeUpsertOne) UpdateVlessWsPath() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateVlessWsPath()
	})
}

// SetTags sets the "tags" field.
func (u *ProxyNodeUpsertOne) SetTags(v []string) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *ProxyNodeUpsertOne) UpdateTags() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateTags()
	})
}

// SetStatus sets the "status" field.
func (u *ProxyNodeUpsertOne) SetStatus(v string) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProxyNodeUpsertOne) UpdateStatus() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateStatus()
	})
}

// SetDescription sets the "description" field.
func (u *ProxyNodeUpsertOne) SetDescription(v string) *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ProxyNodeUpsertOne) UpdateDescription() *ProxyNodeUpsertOne {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateDescription()
	})
}

// Exec executes the query.
func (u *ProxyNodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyNodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyNodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProxyNodeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProxyNodeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProxyNodeCreateBulk is the builder for creating many ProxyNode entities in bulk.
type ProxyNodeCreateBulk struct {
	config
	err      error
	builders []*ProxyNodeCreate
	conflict []sql.ConflictOption
}

// Save creates the ProxyNode entities in the database.
func (_c *ProxyNodeCreateBulk) Save(ctx context.Context) ([]*ProxyNode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxyNode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxyNodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxyNodeCreateBulk) SaveX(ctx context.Context) []*ProxyNode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyNodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyNodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxyNode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyNodeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyNodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProxyNodeUpsertBulk {
	_c.conflict = opts
	return &ProxyNodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxyNode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyNodeCreateBulk) OnConflictColumns(columns ...string) *ProxyNodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyNodeUpsertBulk{
		create: _c,
	}
}

// ProxyNodeUpsertBulk is the builder for "upsert"-ing
// a bulk of ProxyNode nodes.
type ProxyNodeUpsertBulk struct {
	create *ProxyNodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProxyNode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxyNodeUpsertBulk) UpdateNewValues() *ProxyNodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(proxynode.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxyNode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProxyNodeUpsertBulk) Ignore() *ProxyNodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyNodeUpsertBulk) DoNothing() *ProxyNodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyNodeCreateBulk.OnConflict
// documentation for more info.
func (u *ProxyNodeUpsertBulk) Update(set func(*ProxyNodeUpsert)) *ProxyNodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyNodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyNodeUpsertBulk) SetUpdatedAt(v time.Time) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyNodeUpsertBulk) UpdateUpdatedAt() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProxyNodeUpsertBulk) SetDeletedAt(v time.Time) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProxyNodeUpsertBulk) UpdateDeletedAt() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProxyNodeUpsertBulk) ClearDeletedAt() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.ClearDeletedAt()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *ProxyNodeUpsertBulk) SetIPAddress(v string) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *ProxyNodeUpsertBulk) UpdateIPAddress() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateIPAddress()
	})
}

// SetCountry sets the "country" field.
func (u *ProxyNodeUpsertBulk) SetCountry(v string) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetCountry(v)
	})
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *ProxyNodeUpsertBulk) UpdateCountry() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateCountry()
	})
}

// SetCountryCode sets the "country_code" field.
func (u *ProxyNodeUpsertBulk) SetCountryCode(v string) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetCountryCode(v)
	})
}

// UpdateCountryCode sets the "country_code" field to the value that was provided on create.
func (u *ProxyNodeUpsertBulk) UpdateCountryCode() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateCountryCode()
	})
}

// SetCity sets the "city" field.
func (u *ProxyNodeUpsertBulk) SetCity(v string) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetCity(v)
	})
}

// UpdateCity sets the "city" field to the value that was provided on create.
func (u *ProxyNodeUpsertBulk) UpdateCity() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateCity()
	})
}

// SetIsp sets the "isp" field.
func (u *ProxyNodeUpsertBulk) SetIsp(v string) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetIsp(v)
	})
}

// UpdateIsp sets the "isp" field to the value that was provided on create.
func (u *ProxyNodeUpsertBulk) UpdateIsp() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateIsp()
	})
}

// SetHTTPPort sets the "http_port" field.
func (u *ProxyNodeUpsertBulk) SetHTTPPort(v int) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetHTTPPort(v)
	})
}

// AddHTTPPort adds v to the "http_port" field.
func (u *ProxyNodeUpsertBulk) AddHTTPPort(v int) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.AddHTTPPort(v)
	})
}

// UpdateHTTPPort sets the "http_port" field to the value that was provided on create.
func (u *ProxyNodeUpsertBulk) UpdateHTTPPort() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateHTTPPort()
	})
}

// SetVlessPort sets the "vless_port" field.
func (u *ProxyNodeUpsertBulk) SetVlessPort(v int) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetVlessPort(v)
	})
}

// AddVlessPort adds v to the "vless_port" field.
func (u *ProxyNodeUpsertBulk) AddVlessPort(v int) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.AddVlessPort(v)
	})
}

// UpdateVlessPort sets the "vless_port" field to the value that was provided on create.
func (u *ProxyNodeUpsertBulk) UpdateVlessPort() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateVlessPort()
	})
}

// SetVlessNetwork sets the "vless_network" field.
func (u *ProxyNodeUpsertBulk) SetVlessNetwork(v string) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetVlessNetwork(v)
	})
}

// UpdateVlessNetwork sets the "vless_network" field to the value that was provided on create.
func (u *ProxyNodeUpsertBulk) UpdateVlessNetwork() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateVlessNetwork()
	})
}

// SetVlessTLS sets the "vless_tls" field.
func (u *ProxyNodeUpsertBulk) SetVlessTLS(v bool) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetVlessTLS(v)
	})
}

// UpdateVlessTLS sets the "vless_tls" field to the value that was provided on create.
func (u *ProxyNodeUpsertBulk) UpdateVlessTLS() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateVlessTLS()
	})
}

// SetVlessSni sets the "vless_sni" field.
func (u *ProxyNodeUpsertBulk) SetVlessSni(v string) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetVlessSni(v)
	})
}

// UpdateVlessSni sets the "vless_sni" field to the value that was provided on create.
func (u *ProxyNodeUpsertBulk) UpdateVlessSni() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateVlessSni()
	})
}

// SetVlessWsPath sets the "vless_ws_path" field.
func (u *ProxyNodeUpsertBulk) SetVlessWsPath(v string) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetVlessWsPath(v)
	})
}

// UpdateVlessWsPath sets the "vless_ws_path" field to the value that was provided on create.
func (u *ProxyNodeUpsertBulk) UpdateVlessWsPath() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateVlessWsPath()
	})
}

// SetTags sets the "tags" field.
func (u *ProxyNodeUpsertBulk) SetTags(v []string) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *ProxyNodeUpsertBulk) UpdateTags() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateTags()
	})
}

// SetStatus sets the "status" field.
func (u *ProxyNodeUpsertBulk) SetStatus(v string) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProxyNodeUpsertBulk) UpdateStatus() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateStatus()
	})
}

// SetDescription sets the "description" field.
func (u *ProxyNodeUpsertBulk) SetDescription(v string) *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ProxyNodeUpsertBulk) UpdateDescription() *ProxyNodeUpsertBulk {
	return u.Update(func(s *ProxyNodeUpsert) {
		s.UpdateDescription()
	})
}

// Exec executes the query.
func (u *ProxyNodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProxyNodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyNodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyNodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
