// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/meitianwang/fast-frame/ent/proxycredential"
	"github.com/meitianwang/fast-frame/ent/proxynode"
	"github.com/meitianwang/fast-frame/ent/proxyproduct"
	"github.com/meitianwang/fast-frame/ent/proxyrental"
	"github.com/meitianwang/fast-frame/ent/proxytrafficlog"
	"github.com/meitianwang/fast-frame/ent/user"
)

// ProxyRentalCreate is the builder for creating a ProxyRental entity.
type ProxyRentalCreate struct {
	config
	mutation *ProxyRentalMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxyRentalCreate) SetCreatedAt(v time.Time) *ProxyRentalCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxyRentalCreate) SetNillableCreatedAt(v *time.Time) *ProxyRentalCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxyRentalCreate) SetUpdatedAt(v time.Time) *ProxyRentalCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxyRentalCreate) SetNillableUpdatedAt(v *time.Time) *ProxyRentalCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ProxyRentalCreate) SetUserID(v int64) *ProxyRentalCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNodeID sets the "node_id" field.
func (_c *ProxyRentalCreate) SetNodeID(v int64) *ProxyRentalCreate {
	_c.mutation.SetNodeID(v)
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *ProxyRentalCreate) SetProductID(v int64) *ProxyRentalCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_c *ProxyRentalCreate) SetPaymentOrderID(v int64) *ProxyRentalCreate {
	_c.mutation.SetPaymentOrderID(v)
	return _c
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_c *ProxyRentalCreate) SetNillablePaymentOrderID(v *int64) *ProxyRentalCreate {
	if v != nil {
		_c.SetPaymentOrderID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProxyRentalCreate) SetStatus(v string) *ProxyRentalCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProxyRentalCreate) SetNillableStatus(v *string) *ProxyRentalCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *ProxyRentalCreate) SetStartedAt(v time.Time) *ProxyRentalCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *ProxyRentalCreate) SetNillableStartedAt(v *time.Time) *ProxyRentalCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ProxyRentalCreate) SetExpiresAt(v time.Time) *ProxyRentalCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ProxyRentalCreate) SetNillableExpiresAt(v *time.Time) *ProxyRentalCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetTrafficUsedBytes sets the "traffic_used_bytes" field.
func (_c *ProxyRentalCreate) SetTrafficUsedBytes(v int64) *ProxyRentalCreate {
	_c.mutation.SetTrafficUsedBytes(v)
	return _c
}

// SetNillableTrafficUsedBytes sets the "traffic_used_bytes" field if the given value is not nil.
func (_c *ProxyRentalCreate) SetNillableTrafficUsedBytes(v *int64) *ProxyRentalCreate {
	if v != nil {
		_c.SetTrafficUsedBytes(*v)
	}
	return _c
}

// SetTrafficLimitBytes sets the "traffic_limit_bytes" field.
func (_c *ProxyRentalCreate) SetTrafficLimitBytes(v int64) *ProxyRentalCreate {
	_c.mutation.SetTrafficLimitBytes(v)
	return _c
}

// SetNillableTrafficLimitBytes sets the "traffic_limit_bytes" field if the given value is not nil.
func (_c *ProxyRentalCreate) SetNillableTrafficLimitBytes(v *int64) *ProxyRentalCreate {
	if v != nil {
		_c.SetTrafficLimitBytes(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ProxyRentalCreate) SetUser(v *User) *ProxyRentalCreate {
	return _c.SetUserID(v.ID)
}

// SetNode sets the "node" edge to the ProxyNode entity.
func (_c *ProxyRentalCreate) SetNode(v *ProxyNode) *ProxyRentalCreate {
	return _c.SetNodeID(v.ID)
}

// SetProduct sets the "product" edge to the ProxyProduct entity.
func (_c *ProxyRentalCreate) SetProduct(v *ProxyProduct) *ProxyRentalCreate {
	return _c.SetProductID(v.ID)
}

// SetCredentialID sets the "credential" edge to the ProxyCredential entity by ID.
func (_c *ProxyRentalCreate) SetCredentialID(id int64) *ProxyRentalCreate {
	_c.mutation.SetCredentialID(id)
	return _c
}

// SetNillableCredentialID sets the "credential" edge to the ProxyCredential entity by ID if the given value is not nil.
func (_c *ProxyRentalCreate) SetNillableCredentialID(id *int64) *ProxyRentalCreate {
	if id != nil {
		_c = _c.SetCredentialID(*id)
	}
	return _c
}

// SetCredential sets the "credential" edge to the ProxyCredential entity.
func (_c *ProxyRentalCreate) SetCredential(v *ProxyCredential) *ProxyRentalCreate {
	return _c.SetCredentialID(v.ID)
}

// AddTrafficLogIDs adds the "traffic_logs" edge to the ProxyTrafficLog entity by IDs.
func (_c *ProxyRentalCreate) AddTrafficLogIDs(ids ...int64) *ProxyRentalCreate {
	_c.mutation.AddTrafficLogIDs(ids...)
	return _c
}

// AddTrafficLogs adds the "traffic_logs" edges to the ProxyTrafficLog entity.
func (_c *ProxyRentalCreate) AddTrafficLogs(v ...*ProxyTrafficLog) *ProxyRentalCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTrafficLogIDs(ids...)
}

// Mutation returns the ProxyRentalMutation object of the builder.
func (_c *ProxyRentalCreate) Mutation() *ProxyRentalMutation {
	return _c.mutation
}

// Save creates the ProxyRental in the database.
func (_c *ProxyRentalCreate) Save(ctx context.Context) (*ProxyRental, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxyRentalCreate) SaveX(ctx context.Context) *ProxyRental {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyRentalCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyRentalCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxyRentalCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := proxyrental.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := proxyrental.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := proxyrental.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TrafficUsedBytes(); !ok {
		v := proxyrental.DefaultTrafficUsedBytes
		_c.mutation.SetTrafficUsedBytes(v)
	}
	if _, ok := _c.mutation.TrafficLimitBytes(); !ok {
		v := proxyrental.DefaultTrafficLimitBytes
		_c.mutation.SetTrafficLimitBytes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxyRentalCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxyRental.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxyRental.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ProxyRental.user_id"`)}
	}
	if _, ok := _c.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`ent: missing required field "ProxyRental.node_id"`)}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "ProxyRental.product_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ProxyRental.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := proxyrental.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProxyRental.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TrafficUsedBytes(); !ok {
		return &ValidationError{Name: "traffic_used_bytes", err: errors.New(`ent: missing required field "ProxyRental.traffic_used_bytes"`)}
	}
	if _, ok := _c.mutation.TrafficLimitBytes(); !ok {
		return &ValidationError{Name: "traffic_limit_bytes", err: errors.New(`ent: missing required field "ProxyRental.traffic_limit_bytes"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ProxyRental.user"`)}
	}
	if len(_c.mutation.NodeIDs()) == 0 {
		return &ValidationError{Name: "node", err: errors.New(`ent: missing required edge "ProxyRental.node"`)}
	}
	if len(_c.mutation.ProductIDs()) == 0 {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required edge "ProxyRental.product"`)}
	}
	return nil
}

func (_c *ProxyRentalCreate) sqlSave(ctx context.Context) (*ProxyRental, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxyRentalCreate) createSpec() (*ProxyRental, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxyRental{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxyrental.Table, sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxyrental.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyrental.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PaymentOrderID(); ok {
		_spec.SetField(proxyrental.FieldPaymentOrderID, field.TypeInt64, value)
		_node.PaymentOrderID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(proxyrental.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(proxyrental.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(proxyrental.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.TrafficUsedBytes(); ok {
		_spec.SetField(proxyrental.FieldTrafficUsedBytes, field.TypeInt64, value)
		_node.TrafficUsedBytes = value
	}
	if value, ok := _c.mutation.TrafficLimitBytes(); ok {
		_spec.SetField(proxyrental.FieldTrafficLimitBytes, field.TypeInt64, value)
		_node.TrafficLimitBytes = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxyrental.UserTable,
			Columns: []string{proxyrental.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxyrental.NodeTable,
			Columns: []string{proxyrental.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxynode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NodeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxyrental.ProductTable,
			Columns: []string{proxyrental.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CredentialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   proxyrental.CredentialTable,
			Columns: []string{proxyrental.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxycredential.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TrafficLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyrental.TrafficLogsTable,
			Columns: []string{proxyrental.TrafficLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxytrafficlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxyRental.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyRentalUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyRentalCreate) OnConflict(opts ...sql.ConflictOption) *ProxyRentalUpsertOne {
	_c.conflict = opts
	return &ProxyRentalUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxyRental.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyRentalCreate) OnConflictColumns(columns ...string) *ProxyRentalUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyRentalUpsertOne{
		create: _c,
	}
}

type (
	// ProxyRentalUpsertOne is the builder for "upsert"-ing
	//  one ProxyRental node.
	ProxyRentalUpsertOne struct {
		create *ProxyRentalCreate
	}

	// ProxyRentalUpsert is the "OnConflict" setter.
	ProxyRentalUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyRentalUpsert) SetUpdatedAt(v time.Time) *ProxyRentalUpsert {
	u.Set(proxyrental.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyRentalUpsert) UpdateUpdatedAt() *ProxyRentalUpsert {
	u.SetExcluded(proxyrental.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ProxyRentalUpsert) SetUserID(v int64) *ProxyRentalUpsert {
	u.Set(proxyrental.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ProxyRentalUpsert) UpdateUserID() *ProxyRentalUpsert {
	u.SetExcluded(proxyrental.FieldUserID)
	return u
}

// SetNodeID sets the "node_id" field.
func (u *ProxyRentalUpsert) SetNodeID(v int64) *ProxyRentalUpsert {
	u.Set(proxyrental.FieldNodeID, v)
	return u
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *ProxyRentalUpsert) UpdateNodeID() *ProxyRentalUpsert {
	u.SetExcluded(proxyrental.FieldNodeID)
	return u
}

// SetProductID sets the "product_id" field.
func (u *ProxyRentalUpsert) SetProductID(v int64) *ProxyRentalUpsert {
	u.Set(proxyrental.FieldProductID, v)
	return u
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *ProxyRentalUpsert) UpdateProductID() *ProxyRentalUpsert {
	u.SetExcluded(proxyrental.FieldProductID)
	return u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *ProxyRentalUpsert) SetPaymentOrderID(v int64) *ProxyRentalUpsert {
	u.Set(proxyrental.FieldPaymentOrderID, v)
	return u
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *ProxyRentalUpsert) UpdatePaymentOrderID() *ProxyRentalUpsert {
	u.SetExcluded(proxyrental.FieldPaymentOrderID)
	return u
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *ProxyRentalUpsert) AddPaymentOrderID(v int64) *ProxyRentalUpsert {
	u.Add(proxyrental.FieldPaymentOrderID, v)
	return u
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *ProxyRentalUpsert) ClearPaymentOrderID() *ProxyRentalUpsert {
	u.SetNull(proxyrental.FieldPaymentOrderID)
	return u
}

// SetStatus sets the "status" field.
func (u *ProxyRentalUpsert) SetStatus(v string) *ProxyRentalUpsert {
	u.Set(proxyrental.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProxyRentalUpsert) UpdateStatus() *ProxyRentalUpsert {
	u.SetExcluded(proxyrental.FieldStatus)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *ProxyRentalUpsert) SetStartedAt(v time.Time) *ProxyRentalUpsert {
	u.Set(proxyrental.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ProxyRentalUpsert) UpdateStartedAt() *ProxyRentalUpsert {
	u.SetExcluded(proxyrental.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ProxyRentalUpsert) ClearStartedAt() *ProxyRentalUpsert {
	u.SetNull(proxyrental.FieldStartedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ProxyRentalUpsert) SetExpiresAt(v time.Time) *ProxyRentalUpsert {
	u.Set(proxyrental.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ProxyRentalUpsert) UpdateExpiresAt() *ProxyRentalUpsert {
	u.SetExcluded(proxyrental.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ProxyRentalUpsert) ClearExpiresAt() *ProxyRentalUpsert {
	u.SetNull(proxyrental.FieldExpiresAt)
	return u
}

// SetTrafficUsedBytes sets the "traffic_used_bytes" field.
func (u *ProxyRentalUpsert) SetTrafficUsedBytes(v int64) *ProxyRentalUpsert {
	u.Set(proxyrental.FieldTrafficUsedBytes, v)
	return u
}

// UpdateTrafficUsedBytes sets the "traffic_used_bytes" field to the value that was provided on create.
func (u *ProxyRentalUpsert) UpdateTrafficUsedBytes() *ProxyRentalUpsert {
	u.SetExcluded(proxyrental.FieldTrafficUsedBytes)
	return u
}

// AddTrafficUsedBytes adds v to the "traffic_used_bytes" field.
func (u *ProxyRentalUpsert) AddTrafficUsedBytes(v int64) *ProxyRentalUpsert {
	u.Add(proxyrental.FieldTrafficUsedBytes, v)
	return u
}

// SetTrafficLimitBytes sets the "traffic_limit_bytes" field.
func (u *ProxyRentalUpsert) SetTrafficLimitBytes(v int64) *ProxyRentalUpsert {
	u.Set(proxyrental.FieldTrafficLimitBytes, v)
	return u
}

// UpdateTrafficLimitBytes sets the "traffic_limit_bytes" field to the value that was provided on create.
func (u *ProxyRentalUpsert) UpdateTrafficLimitBytes() *ProxyRentalUpsert {
	u.SetExcluded(proxyrental.FieldTrafficLimitBytes)
	return u
}

// AddTrafficLimitBytes adds v to the "traffic_limit_bytes" field.
func (u *ProxyRentalUpsert) AddTrafficLimitBytes(v int64) *ProxyRentalUpsert {
	u.Add(proxyrental.FieldTrafficLimitBytes, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProxyRental.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxyRentalUpsertOne) UpdateNewValues() *ProxyRentalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(proxyrental.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxyRental.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProxyRentalUpsertOne) Ignore() *ProxyRentalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyRentalUpsertOne) DoNothing() *ProxyRentalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyRentalCreate.OnConflict
// documentation for more info.
func (u *ProxyRentalUpsertOne) Update(set func(*ProxyRentalUpsert)) *ProxyRentalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyRentalUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyRentalUpsertOne) SetUpdatedAt(v time.Time) *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyRentalUpsertOne) UpdateUpdatedAt() *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ProxyRentalUpsertOne) SetUserID(v int64) *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ProxyRentalUpsertOne) UpdateUserID() *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateUserID()
	})
}

// SetNodeID sets the "node_id" field.
func (u *ProxyRentalUpsertOne) SetNodeID(v int64) *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetNodeID(v)
	})
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *ProxyRentalUpsertOne) UpdateNodeID() *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateNodeID()
	})
}

// SetProductID sets the "product_id" field.
func (u *ProxyRentalUpsertOne) SetProductID(v int64) *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *ProxyRentalUpsertOne) UpdateProductID() *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateProductID()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *ProxyRentalUpsertOne) SetPaymentOrderID(v int64) *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *ProxyRentalUpsertOne) AddPaymentOrderID(v int64) *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.AddPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *ProxyRentalUpsertOne) UpdatePaymentOrderID() *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *ProxyRentalUpsertOne) ClearPaymentOrderID() *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.ClearPaymentOrderID()
	})
}

// SetStatus sets the "status" field.
func (u *ProxyRentalUpsertOne) SetStatus(v string) *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProxyRentalUpsertOne) UpdateStatus() *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateStatus()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *ProxyRentalUpsertOne) SetStartedAt(v time.Time) *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ProxyRentalUpsertOne) UpdateStartedAt() *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ProxyRentalUpsertOne) ClearStartedAt() *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.ClearStartedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ProxyRentalUpsertOne) SetExpiresAt(v time.Time) *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ProxyRentalUpsertOne) UpdateExpiresAt() *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ProxyRentalUpsertOne) ClearExpiresAt() *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.ClearExpiresAt()
	})
}

// SetTrafficUsedBytes sets the "traffic_used_bytes" field.
func (u *ProxyRentalUpsertOne) SetTrafficUsedBytes(v int64) *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetTrafficUsedBytes(v)
	})
}

// AddTrafficUsedBytes adds v to the "traffic_used_bytes" field.
func (u *ProxyRentalUpsertOne) AddTrafficUsedBytes(v int64) *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.AddTrafficUsedBytes(v)
	})
}

// UpdateTrafficUsedBytes sets the "traffic_used_bytes" field to the value that was provided on create.
func (u *ProxyRentalUpsertOne) UpdateTrafficUsedBytes() *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateTrafficUsedBytes()
	})
}

// SetTrafficLimitBytes sets the "traffic_limit_bytes" field.
func (u *ProxyRentalUpsertOne) SetTrafficLimitBytes(v int64) *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetTrafficLimitBytes(v)
	})
}

// AddTrafficLimitBytes adds v to the "traffic_limit_bytes" field.
func (u *ProxyRentalUpsertOne) AddTrafficLimitBytes(v int64) *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.AddTrafficLimitBytes(v)
	})
}

// UpdateTrafficLimitBytes sets the "traffic_limit_bytes" field to the value that was provided on create.
func (u *ProxyRentalUpsertOne) UpdateTrafficLimitBytes() *ProxyRentalUpsertOne {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateTrafficLimitBytes()
	})
}

// Exec executes the query.
func (u *ProxyRentalUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyRentalCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyRentalUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProxyRentalUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProxyRentalUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProxyRentalCreateBulk is the builder for creating many ProxyRental entities in bulk.
type ProxyRentalCreateBulk struct {
	config
	err      error
	builders []*ProxyRentalCreate
	conflict []sql.ConflictOption
}

// Save creates the ProxyRental entities in the database.
func (_c *ProxyRentalCreateBulk) Save(ctx context.Context) ([]*ProxyRental, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxyRental, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxyRentalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxyRentalCreateBulk) SaveX(ctx context.Context) []*ProxyRental {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyRentalCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyRentalCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxyRental.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyRentalUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyRentalCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProxyRentalUpsertBulk {
	_c.conflict = opts
	return &ProxyRentalUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxyRental.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyRentalCreateBulk) OnConflictColumns(columns ...string) *ProxyRentalUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyRentalUpsertBulk{
		create: _c,
	}
}

// ProxyRentalUpsertBulk is the builder for "upsert"-ing
// a bulk of ProxyRental nodes.
type ProxyRentalUpsertBulk struct {
	create *ProxyRentalCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProxyRental.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxyRentalUpsertBulk) UpdateNewValues() *ProxyRentalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(proxyrental.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxyRental.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProxyRentalUpsertBulk) Ignore() *ProxyRentalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyRentalUpsertBulk) DoNothing() *ProxyRentalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyRentalCreateBulk.OnConflict
// documentation for more info.
func (u *ProxyRentalUpsertBulk) Update(set func(*ProxyRentalUpsert)) *ProxyRentalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyRentalUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyRentalUpsertBulk) SetUpdatedAt(v time.Time) *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyRentalUpsertBulk) UpdateUpdatedAt() *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ProxyRentalUpsertBulk) SetUserID(v int64) *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ProxyRentalUpsertBulk) UpdateUserID() *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateUserID()
	})
}

// SetNodeID sets the "node_id" field.
func (u *ProxyRentalUpsertBulk) SetNodeID(v int64) *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetNodeID(v)
	})
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *ProxyRentalUpsertBulk) UpdateNodeID() *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateNodeID()
	})
}

// SetProductID sets the "product_id" field.
func (u *ProxyRentalUpsertBulk) SetProductID(v int64) *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *ProxyRentalUpsertBulk) UpdateProductID() *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateProductID()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *ProxyRentalUpsertBulk) SetPaymentOrderID(v int64) *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *ProxyRentalUpsertBulk) AddPaymentOrderID(v int64) *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.AddPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *ProxyRentalUpsertBulk) UpdatePaymentOrderID() *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *ProxyRentalUpsertBulk) ClearPaymentOrderID() *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.ClearPaymentOrderID()
	})
}

// SetStatus sets the "status" field.
func (u *ProxyRentalUpsertBulk) SetStatus(v string) *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProxyRentalUpsertBulk) UpdateStatus() *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateStatus()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *ProxyRentalUpsertBulk) SetStartedAt(v time.Time) *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ProxyRentalUpsertBulk) UpdateStartedAt() *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ProxyRentalUpsertBulk) ClearStartedAt() *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.ClearStartedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ProxyRentalUpsertBulk) SetExpiresAt(v time.Time) *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ProxyRentalUpsertBulk) UpdateExpiresAt() *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ProxyRentalUpsertBulk) ClearExpiresAt() *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.ClearExpiresAt()
	})
}

// SetTrafficUsedBytes sets the "traffic_used_bytes" field.
func (u *ProxyRentalUpsertBulk) SetTrafficUsedBytes(v int64) *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetTrafficUsedBytes(v)
	})
}

// AddTrafficUsedBytes adds v to the "traffic_used_bytes" field.
func (u *ProxyRentalUpsertBulk) AddTrafficUsedBytes(v int64) *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.AddTrafficUsedBytes(v)
	})
}

// UpdateTrafficUsedBytes sets the "traffic_used_bytes" field to the value that was provided on create.
func (u *ProxyRentalUpsertBulk) UpdateTrafficUsedBytes() *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateTrafficUsedBytes()
	})
}

// SetTrafficLimitBytes sets the "traffic_limit_bytes" field.
func (u *ProxyRentalUpsertBulk) SetTrafficLimitBytes(v int64) *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.SetTrafficLimitBytes(v)
	})
}

// AddTrafficLimitBytes adds v to the "traffic_limit_bytes" field.
func (u *ProxyRentalUpsertBulk) AddTrafficLimitBytes(v int64) *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.AddTrafficLimitBytes(v)
	})
}

// UpdateTrafficLimitBytes sets the "traffic_limit_bytes" field to the value that was provided on create.
func (u *ProxyRentalUpsertBulk) UpdateTrafficLimitBytes() *ProxyRentalUpsertBulk {
	return u.Update(func(s *ProxyRentalUpsert) {
		s.UpdateTrafficLimitBytes()
	})
}

// Exec executes the query.
func (u *ProxyRentalUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProxyRentalCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyRentalCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyRentalUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
