// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/meitianwang/fast-frame/ent/proxyrental"
	"github.com/meitianwang/fast-frame/ent/proxytrafficlog"
	"github.com/meitianwang/fast-frame/ent/user"
)

// ProxyTrafficLog is the model entity for the ProxyTrafficLog schema.
type ProxyTrafficLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RentalID holds the value of the "rental_id" field.
	RentalID int64 `json:"rental_id,omitempty"`
	// DeltaBytes holds the value of the "delta_bytes" field.
	DeltaBytes int64 `json:"delta_bytes,omitempty"`
	// OperatorID holds the value of the "operator_id" field.
	OperatorID int64 `json:"operator_id,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProxyTrafficLogQuery when eager-loading is set.
	Edges        ProxyTrafficLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProxyTrafficLogEdges holds the relations/edges for other nodes in the graph.
type ProxyTrafficLogEdges struct {
	// Rental holds the value of the rental edge.
	Rental *ProxyRental `json:"rental,omitempty"`
	// Operator holds the value of the operator edge.
	Operator *User `json:"operator,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RentalOrErr returns the Rental value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProxyTrafficLogEdges) RentalOrErr() (*ProxyRental, error) {
	if e.Rental != nil {
		return e.Rental, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: proxyrental.Label}
	}
	return nil, &NotLoadedError{edge: "rental"}
}

// OperatorOrErr returns the Operator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProxyTrafficLogEdges) OperatorOrErr() (*User, error) {
	if e.Operator != nil {
		return e.Operator, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "operator"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProxyTrafficLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxytrafficlog.FieldID, proxytrafficlog.FieldRentalID, proxytrafficlog.FieldDeltaBytes, proxytrafficlog.FieldOperatorID:
			values[i] = new(sql.NullInt64)
		case proxytrafficlog.FieldNote:
			values[i] = new(sql.NullString)
		case proxytrafficlog.FieldCreatedAt, proxytrafficlog.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProxyTrafficLog fields.
func (_m *ProxyTrafficLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxytrafficlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case proxytrafficlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxytrafficlog.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case proxytrafficlog.FieldRentalID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rental_id", values[i])
			} else if value.Valid {
				_m.RentalID = value.Int64
			}
		case proxytrafficlog.FieldDeltaBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delta_bytes", values[i])
			} else if value.Valid {
				_m.DeltaBytes = value.Int64
			}
		case proxytrafficlog.FieldOperatorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_id", values[i])
			} else if value.Valid {
				_m.OperatorID = value.Int64
			}
		case proxytrafficlog.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProxyTrafficLog.
// This includes values selected through modifiers, order, etc.
func (_m *ProxyTrafficLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRental queries the "rental" edge of the ProxyTrafficLog entity.
func (_m *ProxyTrafficLog) QueryRental() *ProxyRentalQuery {
	return NewProxyTrafficLogClient(_m.config).QueryRental(_m)
}

// QueryOperator queries the "operator" edge of the ProxyTrafficLog entity.
func (_m *ProxyTrafficLog) QueryOperator() *UserQuery {
	return NewProxyTrafficLogClient(_m.config).QueryOperator(_m)
}

// Update returns a builder for updating this ProxyTrafficLog.
// Note that you need to call ProxyTrafficLog.Unwrap() before calling this method if this ProxyTrafficLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProxyTrafficLog) Update() *ProxyTrafficLogUpdateOne {
	return NewProxyTrafficLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProxyTrafficLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProxyTrafficLog) Unwrap() *ProxyTrafficLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProxyTrafficLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProxyTrafficLog) String() string {
	var builder strings.Builder
	builder.WriteString("ProxyTrafficLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("rental_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RentalID))
	builder.WriteString(", ")
	builder.WriteString("delta_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeltaBytes))
	builder.WriteString(", ")
	builder.WriteString("operator_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OperatorID))
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteByte(')')
	return builder.String()
}

// ProxyTrafficLogs is a parsable slice of ProxyTrafficLog.
type ProxyTrafficLogs []*ProxyTrafficLog
