// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/meitianwang/fast-frame/ent/predicate"
	"github.com/meitianwang/fast-frame/ent/proxyrental"
	"github.com/meitianwang/fast-frame/ent/proxytrafficlog"
	"github.com/meitianwang/fast-frame/ent/user"
)

// ProxyTrafficLogQuery is the builder for querying ProxyTrafficLog entities.
type ProxyTrafficLogQuery struct {
	config
	ctx          *QueryContext
	order        []proxytrafficlog.OrderOption
	inters       []Interceptor
	predicates   []predicate.ProxyTrafficLog
	withRental   *ProxyRentalQuery
	withOperator *UserQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProxyTrafficLogQuery builder.
func (_q *ProxyTrafficLogQuery) Where(ps ...predicate.ProxyTrafficLog) *ProxyTrafficLogQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ProxyTrafficLogQuery) Limit(limit int) *ProxyTrafficLogQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ProxyTrafficLogQuery) Offset(offset int) *ProxyTrafficLogQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ProxyTrafficLogQuery) Unique(unique bool) *ProxyTrafficLogQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ProxyTrafficLogQuery) Order(o ...proxytrafficlog.OrderOption) *ProxyTrafficLogQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRental chains the current query on the "rental" edge.
func (_q *ProxyTrafficLogQuery) QueryRental() *ProxyRentalQuery {
	query := (&ProxyRentalClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(proxytrafficlog.Table, proxytrafficlog.FieldID, selector),
			sqlgraph.To(proxyrental.Table, proxyrental.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, proxytrafficlog.RentalTable, proxytrafficlog.RentalColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOperator chains the current query on the "operator" edge.
func (_q *ProxyTrafficLogQuery) QueryOperator() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(proxytrafficlog.Table, proxytrafficlog.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, proxytrafficlog.OperatorTable, proxytrafficlog.OperatorColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProxyTrafficLog entity from the query.
// Returns a *NotFoundError when no ProxyTrafficLog was found.
func (_q *ProxyTrafficLogQuery) First(ctx context.Context) (*ProxyTrafficLog, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{proxytrafficlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ProxyTrafficLogQuery) FirstX(ctx context.Context) *ProxyTrafficLog {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProxyTrafficLog ID from the query.
// Returns a *NotFoundError when no ProxyTrafficLog ID was found.
func (_q *ProxyTrafficLogQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{proxytrafficlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ProxyTrafficLogQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProxyTrafficLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProxyTrafficLog entity is found.
// Returns a *NotFoundError when no ProxyTrafficLog entities are found.
func (_q *ProxyTrafficLogQuery) Only(ctx context.Context) (*ProxyTrafficLog, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{proxytrafficlog.Label}
	default:
		return nil, &NotSingularError{proxytrafficlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ProxyTrafficLogQuery) OnlyX(ctx context.Context) *ProxyTrafficLog {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProxyTrafficLog ID in the query.
// Returns a *NotSingularError when more than one ProxyTrafficLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ProxyTrafficLogQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{proxytrafficlog.Label}
	default:
		err = &NotSingularError{proxytrafficlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ProxyTrafficLogQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProxyTrafficLogs.
func (_q *ProxyTrafficLogQuery) All(ctx context.Context) ([]*ProxyTrafficLog, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProxyTrafficLog, *ProxyTrafficLogQuery]()
	return withInterceptors[[]*ProxyTrafficLog](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ProxyTrafficLogQuery) AllX(ctx context.Context) []*ProxyTrafficLog {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProxyTrafficLog IDs.
func (_q *ProxyTrafficLogQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(proxytrafficlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ProxyTrafficLogQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ProxyTrafficLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ProxyTrafficLogQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ProxyTrafficLogQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ProxyTrafficLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ProxyTrafficLogQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProxyTrafficLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ProxyTrafficLogQuery) Clone() *ProxyTrafficLogQuery {
	if _q == nil {
		return nil
	}
	return &ProxyTrafficLogQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]proxytrafficlog.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.ProxyTrafficLog{}, _q.predicates...),
		withRental:   _q.withRental.Clone(),
		withOperator: _q.withOperator.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithRental tells the query-builder to eager-load the nodes that are connected to
// the "rental" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProxyTrafficLogQuery) WithRental(opts ...func(*ProxyRentalQuery)) *ProxyTrafficLogQuery {
	query := (&ProxyRentalClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRental = query
	return _q
}

// WithOperator tells the query-builder to eager-load the nodes that are connected to
// the "operator" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProxyTrafficLogQuery) WithOperator(opts ...func(*UserQuery)) *ProxyTrafficLogQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOperator = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProxyTrafficLog.Query().
//		GroupBy(proxytrafficlog.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ProxyTrafficLogQuery) GroupBy(field string, fields ...string) *ProxyTrafficLogGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProxyTrafficLogGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = proxytrafficlog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ProxyTrafficLog.Query().
//		Select(proxytrafficlog.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ProxyTrafficLogQuery) Select(fields ...string) *ProxyTrafficLogSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ProxyTrafficLogSelect{ProxyTrafficLogQuery: _q}
	sbuild.label = proxytrafficlog.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProxyTrafficLogSelect configured with the given aggregations.
func (_q *ProxyTrafficLogQuery) Aggregate(fns ...AggregateFunc) *ProxyTrafficLogSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ProxyTrafficLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !proxytrafficlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ProxyTrafficLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProxyTrafficLog, error) {
	var (
		nodes       = []*ProxyTrafficLog{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withRental != nil,
			_q.withOperator != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProxyTrafficLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProxyTrafficLog{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRental; query != nil {
		if err := _q.loadRental(ctx, query, nodes, nil,
			func(n *ProxyTrafficLog, e *ProxyRental) { n.Edges.Rental = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOperator; query != nil {
		if err := _q.loadOperator(ctx, query, nodes, nil,
			func(n *ProxyTrafficLog, e *User) { n.Edges.Operator = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ProxyTrafficLogQuery) loadRental(ctx context.Context, query *ProxyRentalQuery, nodes []*ProxyTrafficLog, init func(*ProxyTrafficLog), assign func(*ProxyTrafficLog, *ProxyRental)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ProxyTrafficLog)
	for i := range nodes {
		fk := nodes[i].RentalID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(proxyrental.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "rental_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProxyTrafficLogQuery) loadOperator(ctx context.Context, query *UserQuery, nodes []*ProxyTrafficLog, init func(*ProxyTrafficLog), assign func(*ProxyTrafficLog, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ProxyTrafficLog)
	for i := range nodes {
		fk := nodes[i].OperatorID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "operator_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ProxyTrafficLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ProxyTrafficLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(proxytrafficlog.Table, proxytrafficlog.Columns, sqlgraph.NewFieldSpec(proxytrafficlog.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxytrafficlog.FieldID)
		for i := range fields {
			if fields[i] != proxytrafficlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withRental != nil {
			_spec.Node.AddColumnOnce(proxytrafficlog.FieldRentalID)
		}
		if _q.withOperator != nil {
			_spec.Node.AddColumnOnce(proxytrafficlog.FieldOperatorID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ProxyTrafficLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(proxytrafficlog.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = proxytrafficlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *ProxyTrafficLogQuery) ForUpdate(opts ...sql.LockOption) *ProxyTrafficLogQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *ProxyTrafficLogQuery) ForShare(opts ...sql.LockOption) *ProxyTrafficLogQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// ProxyTrafficLogGroupBy is the group-by builder for ProxyTrafficLog entities.
type ProxyTrafficLogGroupBy struct {
	selector
	build *ProxyTrafficLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ProxyTrafficLogGroupBy) Aggregate(fns ...AggregateFunc) *ProxyTrafficLogGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ProxyTrafficLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProxyTrafficLogQuery, *ProxyTrafficLogGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ProxyTrafficLogGroupBy) sqlScan(ctx context.Context, root *ProxyTrafficLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProxyTrafficLogSelect is the builder for selecting fields of ProxyTrafficLog entities.
type ProxyTrafficLogSelect struct {
	*ProxyTrafficLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ProxyTrafficLogSelect) Aggregate(fns ...AggregateFunc) *ProxyTrafficLogSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ProxyTrafficLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProxyTrafficLogQuery, *ProxyTrafficLogSelect](ctx, _s.ProxyTrafficLogQuery, _s, _s.inters, v)
}

func (_s *ProxyTrafficLogSelect) sqlScan(ctx context.Context, root *ProxyTrafficLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
