// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/meitianwang/fast-frame/ent/predicate"
	"github.com/meitianwang/fast-frame/ent/proxyproduct"
	"github.com/meitianwang/fast-frame/ent/proxyrental"
	"github.com/shopspring/decimal"
)

// ProxyProductUpdate is the builder for updating ProxyProduct entities.
type ProxyProductUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyProductMutation
}

// Where appends a list predicates to the ProxyProductUpdate builder.
func (_u *ProxyProductUpdate) Where(ps ...predicate.ProxyProduct) *ProxyProductUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyProductUpdate) SetUpdatedAt(v time.Time) *ProxyProductUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ProxyProductUpdate) SetName(v string) *ProxyProductUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxyProductUpdate) SetNillableName(v *string) *ProxyProductUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProxyProductUpdate) SetDescription(v string) *ProxyProductUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProxyProductUpdate) SetNillableDescription(v *string) *ProxyProductUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDurationDays sets the "duration_days" field.
func (_u *ProxyProductUpdate) SetDurationDays(v int) *ProxyProductUpdate {
	_u.mutation.ResetDurationDays()
	_u.mutation.SetDurationDays(v)
	return _u
}

// SetNillableDurationDays sets the "duration_days" field if the given value is not nil.
func (_u *ProxyProductUpdate) SetNillableDurationDays(v *int) *ProxyProductUpdate {
	if v != nil {
		_u.SetDurationDays(*v)
	}
	return _u
}

// AddDurationDays adds value to the "duration_days" field.
func (_u *ProxyProductUpdate) AddDurationDays(v int) *ProxyProductUpdate {
	_u.mutation.AddDurationDays(v)
	return _u
}

// SetTrafficLimitGB sets the "traffic_limit_gb" field.
func (_u *ProxyProductUpdate) SetTrafficLimitGB(v int) *ProxyProductUpdate {
	_u.mutation.ResetTrafficLimitGB()
	_u.mutation.SetTrafficLimitGB(v)
	return _u
}

// SetNillableTrafficLimitGB sets the "traffic_limit_gb" field if the given value is not nil.
func (_u *ProxyProductUpdate) SetNillableTrafficLimitGB(v *int) *ProxyProductUpdate {
	if v != nil {
		_u.SetTrafficLimitGB(*v)
	}
	return _u
}

// AddTrafficLimitGB adds value to the "traffic_limit_gb" field.
func (_u *ProxyProductUpdate) AddTrafficLimitGB(v int) *ProxyProductUpdate {
	_u.mutation.AddTrafficLimitGB(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *ProxyProductUpdate) SetPrice(v decimal.Decimal) *ProxyProductUpdate {
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *ProxyProductUpdate) SetNillablePrice(v *decimal.Decimal) *ProxyProductUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ProxyProductUpdate) SetSortOrder(v int) *ProxyProductUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ProxyProductUpdate) SetNillableSortOrder(v *int) *ProxyProductUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ProxyProductUpdate) AddSortOrder(v int) *ProxyProductUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ProxyProductUpdate) SetIsActive(v bool) *ProxyProductUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ProxyProductUpdate) SetNillableIsActive(v *bool) *ProxyProductUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// AddRentalIDs adds the "rentals" edge to the ProxyRental entity by IDs.
func (_u *ProxyProductUpdate) AddRentalIDs(ids ...int64) *ProxyProductUpdate {
	_u.mutation.AddRentalIDs(ids...)
	return _u
}

// AddRentals adds the "rentals" edges to the ProxyRental entity.
func (_u *ProxyProductUpdate) AddRentals(v ...*ProxyRental) *ProxyProductUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRentalIDs(ids...)
}

// Mutation returns the ProxyProductMutation object of the builder.
func (_u *ProxyProductUpdate) Mutation() *ProxyProductMutation {
	return _u.mutation
}

// ClearRentals clears all "rentals" edges to the ProxyRental entity.
func (_u *ProxyProductUpdate) ClearRentals() *ProxyProductUpdate {
	_u.mutation.ClearRentals()
	return _u
}

// RemoveRentalIDs removes the "rentals" edge to ProxyRental entities by IDs.
func (_u *ProxyProductUpdate) RemoveRentalIDs(ids ...int64) *ProxyProductUpdate {
	_u.mutation.RemoveRentalIDs(ids...)
	return _u
}

// RemoveRentals removes "rentals" edges to ProxyRental entities.
func (_u *ProxyProductUpdate) RemoveRentals(v ...*ProxyRental) *ProxyProductUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRentalIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyProductUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyProductUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxyProductUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyProductUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyProductUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxyproduct.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyProductUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxyproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxyProduct.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationDays(); ok {
		if err := proxyproduct.DurationDaysValidator(v); err != nil {
			return &ValidationError{Name: "duration_days", err: fmt.Errorf(`ent: validator failed for field "ProxyProduct.duration_days": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyProductUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxyproduct.Table, proxyproduct.Columns, sqlgraph.NewFieldSpec(proxyproduct.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyproduct.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxyproduct.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(proxyproduct.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.DurationDays(); ok {
		_spec.SetField(proxyproduct.FieldDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationDays(); ok {
		_spec.AddField(proxyproduct.FieldDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TrafficLimitGB(); ok {
		_spec.SetField(proxyproduct.FieldTrafficLimitGB, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTrafficLimitGB(); ok {
		_spec.AddField(proxyproduct.FieldTrafficLimitGB, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(proxyproduct.FieldPrice, field.TypeOther, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(proxyproduct.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(proxyproduct.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(proxyproduct.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.RentalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyproduct.RentalsTable,
			Columns: []string{proxyproduct.RentalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRentalsIDs(); len(nodes) > 0 && !_u.mutation.RentalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyproduct.RentalsTable,
			Columns: []string{proxyproduct.RentalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RentalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyproduct.RentalsTable,
			Columns: []string{proxyproduct.RentalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxyproduct.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxyProductUpdateOne is the builder for updating a single ProxyProduct entity.
type ProxyProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyProductMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyProductUpdateOne) SetUpdatedAt(v time.Time) *ProxyProductUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ProxyProductUpdateOne) SetName(v string) *ProxyProductUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxyProductUpdateOne) SetNillableName(v *string) *ProxyProductUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProxyProductUpdateOne) SetDescription(v string) *ProxyProductUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProxyProductUpdateOne) SetNillableDescription(v *string) *ProxyProductUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDurationDays sets the "duration_days" field.
func (_u *ProxyProductUpdateOne) SetDurationDays(v int) *ProxyProductUpdateOne {
	_u.mutation.ResetDurationDays()
	_u.mutation.SetDurationDays(v)
	return _u
}

// SetNillableDurationDays sets the "duration_days" field if the given value is not nil.
func (_u *ProxyProductUpdateOne) SetNillableDurationDays(v *int) *ProxyProductUpdateOne {
	if v != nil {
		_u.SetDurationDays(*v)
	}
	return _u
}

// AddDurationDays adds value to the "duration_days" field.
func (_u *ProxyProductUpdateOne) AddDurationDays(v int) *ProxyProductUpdateOne {
	_u.mutation.AddDurationDays(v)
	return _u
}

// SetTrafficLimitGB sets the "traffic_limit_gb" field.
func (_u *ProxyProductUpdateOne) SetTrafficLimitGB(v int) *ProxyProductUpdateOne {
	_u.mutation.ResetTrafficLimitGB()
	_u.mutation.SetTrafficLimitGB(v)
	return _u
}

// SetNillableTrafficLimitGB sets the "traffic_limit_gb" field if the given value is not nil.
func (_u *ProxyProductUpdateOne) SetNillableTrafficLimitGB(v *int) *ProxyProductUpdateOne {
	if v != nil {
		_u.SetTrafficLimitGB(*v)
	}
	return _u
}

// AddTrafficLimitGB adds value to the "traffic_limit_gb" field.
func (_u *ProxyProductUpdateOne) AddTrafficLimitGB(v int) *ProxyProductUpdateOne {
	_u.mutation.AddTrafficLimitGB(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *ProxyProductUpdateOne) SetPrice(v decimal.Decimal) *ProxyProductUpdateOne {
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *ProxyProductUpdateOne) SetNillablePrice(v *decimal.Decimal) *ProxyProductUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ProxyProductUpdateOne) SetSortOrder(v int) *ProxyProductUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ProxyProductUpdateOne) SetNillableSortOrder(v *int) *ProxyProductUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ProxyProductUpdateOne) AddSortOrder(v int) *ProxyProductUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ProxyProductUpdateOne) SetIsActive(v bool) *ProxyProductUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ProxyProductUpdateOne) SetNillableIsActive(v *bool) *ProxyProductUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// AddRentalIDs adds the "rentals" edge to the ProxyRental entity by IDs.
func (_u *ProxyProductUpdateOne) AddRentalIDs(ids ...int64) *ProxyProductUpdateOne {
	_u.mutation.AddRentalIDs(ids...)
	return _u
}

// AddRentals adds the "rentals" edges to the ProxyRental entity.
func (_u *ProxyProductUpdateOne) AddRentals(v ...*ProxyRental) *ProxyProductUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRentalIDs(ids...)
}

// Mutation returns the ProxyProductMutation object of the builder.
func (_u *ProxyProductUpdateOne) Mutation() *ProxyProductMutation {
	return _u.mutation
}

// ClearRentals clears all "rentals" edges to the ProxyRental entity.
func (_u *ProxyProductUpdateOne) ClearRentals() *ProxyProductUpdateOne {
	_u.mutation.ClearRentals()
	return _u
}

// RemoveRentalIDs removes the "rentals" edge to ProxyRental entities by IDs.
func (_u *ProxyProductUpdateOne) RemoveRentalIDs(ids ...int64) *ProxyProductUpdateOne {
	_u.mutation.RemoveRentalIDs(ids...)
	return _u
}

// RemoveRentals removes "rentals" edges to ProxyRental entities.
func (_u *ProxyProductUpdateOne) RemoveRentals(v ...*ProxyRental) *ProxyProductUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRentalIDs(ids...)
}

// Where appends a list predicates to the ProxyProductUpdate builder.
func (_u *ProxyProductUpdateOne) Where(ps ...predicate.ProxyProduct) *ProxyProductUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyProductUpdateOne) Select(field string, fields ...string) *ProxyProductUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxyProduct entity.
func (_u *ProxyProductUpdateOne) Save(ctx context.Context) (*ProxyProduct, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyProductUpdateOne) SaveX(ctx context.Context) *ProxyProduct {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxyProductUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyProductUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyProductUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxyproduct.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyProductUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxyproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxyProduct.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationDays(); ok {
		if err := proxyproduct.DurationDaysValidator(v); err != nil {
			return &ValidationError{Name: "duration_days", err: fmt.Errorf(`ent: validator failed for field "ProxyProduct.duration_days": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyProductUpdateOne) sqlSave(ctx context.Context) (_node *ProxyProduct, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxyproduct.Table, proxyproduct.Columns, sqlgraph.NewFieldSpec(proxyproduct.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxyProduct.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxyproduct.FieldID)
		for _, f := range fields {
			if !proxyproduct.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxyproduct.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyproduct.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxyproduct.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(proxyproduct.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.DurationDays(); ok {
		_spec.SetField(proxyproduct.FieldDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationDays(); ok {
		_spec.AddField(proxyproduct.FieldDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TrafficLimitGB(); ok {
		_spec.SetField(proxyproduct.FieldTrafficLimitGB, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTrafficLimitGB(); ok {
		_spec.AddField(proxyproduct.FieldTrafficLimitGB, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(proxyproduct.FieldPrice, field.TypeOther, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(proxyproduct.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(proxyproduct.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(proxyproduct.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.RentalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyproduct.RentalsTable,
			Columns: []string{proxyproduct.RentalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRentalsIDs(); len(nodes) > 0 && !_u.mutation.RentalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyproduct.RentalsTable,
			Columns: []string{proxyproduct.RentalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RentalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyproduct.RentalsTable,
			Columns: []string{proxyproduct.RentalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProxyProduct{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxyproduct.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
