// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/meitianwang/fast-frame/ent/proxyproduct"
	"github.com/shopspring/decimal"
)

// ProxyProduct is the model entity for the ProxyProduct schema.
type ProxyProduct struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// DurationDays holds the value of the "duration_days" field.
	DurationDays int `json:"duration_days,omitempty"`
	// TrafficLimitGB holds the value of the "traffic_limit_gb" field.
	TrafficLimitGB int `json:"traffic_limit_gb,omitempty"`
	// Price holds the value of the "price" field.
	Price decimal.Decimal `json:"price,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProxyProductQuery when eager-loading is set.
	Edges        ProxyProductEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProxyProductEdges holds the relations/edges for other nodes in the graph.
type ProxyProductEdges struct {
	// Rentals holds the value of the rentals edge.
	Rentals []*ProxyRental `json:"rentals,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RentalsOrErr returns the Rentals value or an error if the edge
// was not loaded in eager-loading.
func (e ProxyProductEdges) RentalsOrErr() ([]*ProxyRental, error) {
	if e.loadedTypes[0] {
		return e.Rentals, nil
	}
	return nil, &NotLoadedError{edge: "rentals"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProxyProduct) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxyproduct.FieldPrice:
			values[i] = new(decimal.Decimal)
		case proxyproduct.FieldIsActive:
			values[i] = new(sql.NullBool)
		case proxyproduct.FieldID, proxyproduct.FieldDurationDays, proxyproduct.FieldTrafficLimitGB, proxyproduct.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case proxyproduct.FieldName, proxyproduct.FieldDescription:
			values[i] = new(sql.NullString)
		case proxyproduct.FieldCreatedAt, proxyproduct.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProxyProduct fields.
func (_m *ProxyProduct) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxyproduct.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case proxyproduct.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxyproduct.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case proxyproduct.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case proxyproduct.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case proxyproduct.FieldDurationDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_days", values[i])
			} else if value.Valid {
				_m.DurationDays = int(value.Int64)
			}
		case proxyproduct.FieldTrafficLimitGB:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field traffic_limit_gb", values[i])
			} else if value.Valid {
				_m.TrafficLimitGB = int(value.Int64)
			}
		case proxyproduct.FieldPrice:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value != nil {
				_m.Price = *value
			}
		case proxyproduct.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case proxyproduct.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProxyProduct.
// This includes values selected through modifiers, order, etc.
func (_m *ProxyProduct) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRentals queries the "rentals" edge of the ProxyProduct entity.
func (_m *ProxyProduct) QueryRentals() *ProxyRentalQuery {
	return NewProxyProductClient(_m.config).QueryRentals(_m)
}

// Update returns a builder for updating this ProxyProduct.
// Note that you need to call ProxyProduct.Unwrap() before calling this method if this ProxyProduct
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProxyProduct) Update() *ProxyProductUpdateOne {
	return NewProxyProductClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProxyProduct entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProxyProduct) Unwrap() *ProxyProduct {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProxyProduct is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProxyProduct) String() string {
	var builder strings.Builder
	builder.WriteString("ProxyProduct(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("duration_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationDays))
	builder.WriteString(", ")
	builder.WriteString("traffic_limit_gb=")
	builder.WriteString(fmt.Sprintf("%v", _m.TrafficLimitGB))
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteByte(')')
	return builder.String()
}

// ProxyProducts is a parsable slice of ProxyProduct.
type ProxyProducts []*ProxyProduct
