// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/meitianwang/fast-frame/ent/proxycredential"
	"github.com/meitianwang/fast-frame/ent/proxyrental"
)

// ProxyCredentialCreate is the builder for creating a ProxyCredential entity.
type ProxyCredentialCreate struct {
	config
	mutation *ProxyCredentialMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxyCredentialCreate) SetCreatedAt(v time.Time) *ProxyCredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxyCredentialCreate) SetNillableCreatedAt(v *time.Time) *ProxyCredentialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxyCredentialCreate) SetUpdatedAt(v time.Time) *ProxyCredentialCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxyCredentialCreate) SetNillableUpdatedAt(v *time.Time) *ProxyCredentialCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRentalID sets the "rental_id" field.
func (_c *ProxyCredentialCreate) SetRentalID(v int64) *ProxyCredentialCreate {
	_c.mutation.SetRentalID(v)
	return _c
}

// SetHTTPUsername sets the "http_username" field.
func (_c *ProxyCredentialCreate) SetHTTPUsername(v string) *ProxyCredentialCreate {
	_c.mutation.SetHTTPUsername(v)
	return _c
}

// SetHTTPPassword sets the "http_password" field.
func (_c *ProxyCredentialCreate) SetHTTPPassword(v string) *ProxyCredentialCreate {
	_c.mutation.SetHTTPPassword(v)
	return _c
}

// SetVlessUUID sets the "vless_uuid" field.
func (_c *ProxyCredentialCreate) SetVlessUUID(v string) *ProxyCredentialCreate {
	_c.mutation.SetVlessUUID(v)
	return _c
}

// SetVlessLink sets the "vless_link" field.
func (_c *ProxyCredentialCreate) SetVlessLink(v string) *ProxyCredentialCreate {
	_c.mutation.SetVlessLink(v)
	return _c
}

// SetRental sets the "rental" edge to the ProxyRental entity.
func (_c *ProxyCredentialCreate) SetRental(v *ProxyRental) *ProxyCredentialCreate {
	return _c.SetRentalID(v.ID)
}

// Mutation returns the ProxyCredentialMutation object of the builder.
func (_c *ProxyCredentialCreate) Mutation() *ProxyCredentialMutation {
	return _c.mutation
}

// Save creates the ProxyCredential in the database.
func (_c *ProxyCredentialCreate) Save(ctx context.Context) (*ProxyCredential, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxyCredentialCreate) SaveX(ctx context.Context) *ProxyCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyCredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyCredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxyCredentialCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := proxycredential.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := proxycredential.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxyCredentialCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxyCredential.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxyCredential.updated_at"`)}
	}
	if _, ok := _c.mutation.RentalID(); !ok {
		return &ValidationError{Name: "rental_id", err: errors.New(`ent: missing required field "ProxyCredential.rental_id"`)}
	}
	if _, ok := _c.mutation.HTTPUsername(); !ok {
		return &ValidationError{Name: "http_username", err: errors.New(`ent: missing required field "ProxyCredential.http_username"`)}
	}
	if v, ok := _c.mutation.HTTPUsername(); ok {
		if err := proxycredential.HTTPUsernameValidator(v); err != nil {
			return &ValidationError{Name: "http_username", err: fmt.Errorf(`ent: validator failed for field "ProxyCredential.http_username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HTTPPassword(); !ok {
		return &ValidationError{Name: "http_password", err: errors.New(`ent: missing required field "ProxyCredential.http_password"`)}
	}
	if v, ok := _c.mutation.HTTPPassword(); ok {
		if err := proxycredential.HTTPPasswordValidator(v); err != nil {
			return &ValidationError{Name: "http_password", err: fmt.Errorf(`ent: validator failed for field "ProxyCredential.http_password": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VlessUUID(); !ok {
		return &ValidationError{Name: "vless_uuid", err: errors.New(`ent: missing required field "ProxyCredential.vless_uuid"`)}
	}
	if v, ok := _c.mutation.VlessUUID(); ok {
		if err := proxycredential.VlessUUIDValidator(v); err != nil {
			return &ValidationError{Name: "vless_uuid", err: fmt.Errorf(`ent: validator failed for field "ProxyCredential.vless_uuid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VlessLink(); !ok {
		return &ValidationError{Name: "vless_link", err: errors.New(`ent: missing required field "ProxyCredential.vless_link"`)}
	}
	if v, ok := _c.mutation.VlessLink(); ok {
		if err := proxycredential.VlessLinkValidator(v); err != nil {
			return &ValidationError{Name: "vless_link", err: fmt.Errorf(`ent: validator failed for field "ProxyCredential.vless_link": %w`, err)}
		}
	}
	if len(_c.mutation.RentalIDs()) == 0 {
		return &ValidationError{Name: "rental", err: errors.New(`ent: missing required edge "ProxyCredential.rental"`)}
	}
	return nil
}

func (_c *ProxyCredentialCreate) sqlSave(ctx context.Context) (*ProxyCredential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxyCredentialCreate) createSpec() (*ProxyCredential, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxyCredential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxycredential.Table, sqlgraph.NewFieldSpec(proxycredential.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxycredential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxycredential.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.HTTPUsername(); ok {
		_spec.SetField(proxycredential.FieldHTTPUsername, field.TypeString, value)
		_node.HTTPUsername = value
	}
	if value, ok := _c.mutation.HTTPPassword(); ok {
		_spec.SetField(proxycredential.FieldHTTPPassword, field.TypeString, value)
		_node.HTTPPassword = value
	}
	if value, ok := _c.mutation.VlessUUID(); ok {
		_spec.SetField(proxycredential.FieldVlessUUID, field.TypeString, value)
		_node.VlessUUID = value
	}
	if value, ok := _c.mutation.VlessLink(); ok {
		_spec.SetField(proxycredential.FieldVlessLink, field.TypeString, value)
		_node.VlessLink = value
	}
	if nodes := _c.mutation.RentalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   proxycredential.RentalTable,
			Columns: []string{proxycredential.RentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RentalID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxyCredential.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyCredentialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyCredentialCreate) OnConflict(opts ...sql.ConflictOption) *ProxyCredentialUpsertOne {
	_c.conflict = opts
	return &ProxyCredentialUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxyCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyCredentialCreate) OnConflictColumns(columns ...string) *ProxyCredentialUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyCredentialUpsertOne{
		create: _c,
	}
}

type (
	// ProxyCredentialUpsertOne is the builder for "upsert"-ing
	//  one ProxyCredential node.
	ProxyCredentialUpsertOne struct {
		create *ProxyCredentialCreate
	}

	// ProxyCredentialUpsert is the "OnConflict" setter.
	ProxyCredentialUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyCredentialUpsert) SetUpdatedAt(v time.Time) *ProxyCredentialUpsert {
	u.Set(proxycredential.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyCredentialUpsert) UpdateUpdatedAt() *ProxyCredentialUpsert {
	u.SetExcluded(proxycredential.FieldUpdatedAt)
	return u
}

// SetRentalID sets the "rental_id" field.
func (u *ProxyCredentialUpsert) SetRentalID(v int64) *ProxyCredentialUpsert {
	u.Set(proxycredential.FieldRentalID, v)
	return u
}

// UpdateRentalID sets the "rental_id" field to the value that was provided on create.
func (u *ProxyCredentialUpsert) UpdateRentalID() *ProxyCredentialUpsert {
	u.SetExcluded(proxycredential.FieldRentalID)
	return u
}

// SetHTTPUsername sets the "http_username" field.
func (u *ProxyCredentialUpsert) SetHTTPUsername(v string) *ProxyCredentialUpsert {
	u.Set(proxycredential.FieldHTTPUsername, v)
	return u
}

// UpdateHTTPUsername sets the "http_username" field to the value that was provided on create.
func (u *ProxyCredentialUpsert) UpdateHTTPUsername() *ProxyCredentialUpsert {
	u.SetExcluded(proxycredential.FieldHTTPUsername)
	return u
}

// SetHTTPPassword sets the "http_password" field.
func (u *ProxyCredentialUpsert) SetHTTPPassword(v string) *ProxyCredentialUpsert {
	u.Set(proxycredential.FieldHTTPPassword, v)
	return u
}

// UpdateHTTPPassword sets the "http_password" field to the value that was provided on create.
func (u *ProxyCredentialUpsert) UpdateHTTPPassword() *ProxyCredentialUpsert {
	u.SetExcluded(proxycredential.FieldHTTPPassword)
	return u
}

// SetVlessUUID sets the "vless_uuid" field.
func (u *ProxyCredentialUpsert) SetVlessUUID(v string) *ProxyCredentialUpsert {
	u.Set(proxycredential.FieldVlessUUID, v)
	return u
}

// UpdateVlessUUID sets the "vless_uuid" field to the value that was provided on create.
func (u *ProxyCredentialUpsert) UpdateVlessUUID() *ProxyCredentialUpsert {
	u.SetExcluded(proxycredential.FieldVlessUUID)
	return u
}

// SetVlessLink sets the "vless_link" field.
func (u *ProxyCredentialUpsert) SetVlessLink(v string) *ProxyCredentialUpsert {
	u.Set(proxycredential.FieldVlessLink, v)
	return u
}

// UpdateVlessLink sets the "vless_link" field to the value that was provided on create.
func (u *ProxyCredentialUpsert) UpdateVlessLink() *ProxyCredentialUpsert {
	u.SetExcluded(proxycredential.FieldVlessLink)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProxyCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxyCredentialUpsertOne) UpdateNewValues() *ProxyCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(proxycredential.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxyCredential.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProxyCredentialUpsertOne) Ignore() *ProxyCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyCredentialUpsertOne) DoNothing() *ProxyCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyCredentialCreate.OnConflict
// documentation for more info.
func (u *ProxyCredentialUpsertOne) Update(set func(*ProxyCredentialUpsert)) *ProxyCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyCredentialUpsertOne) SetUpdatedAt(v time.Time) *ProxyCredentialUpsertOne {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyCredentialUpsertOne) UpdateUpdatedAt() *ProxyCredentialUpsertOne {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRentalID sets the "rental_id" field.
func (u *ProxyCredentialUpsertOne) SetRentalID(v int64) *ProxyCredentialUpsertOne {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.SetRentalID(v)
	})
}

// UpdateRentalID sets the "rental_id" field to the value that was provided on create.
func (u *ProxyCredentialUpsertOne) UpdateRentalID() *ProxyCredentialUpsertOne {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.UpdateRentalID()
	})
}

// SetHTTPUsername sets the "http_username" field.
func (u *ProxyCredentialUpsertOne) SetHTTPUsername(v string) *ProxyCredentialUpsertOne {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.SetHTTPUsername(v)
	})
}

// UpdateHTTPUsername sets the "http_username" field to the value that was provided on create.
func (u *ProxyCredentialUpsertOne) UpdateHTTPUsername() *ProxyCredentialUpsertOne {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.UpdateHTTPUsername()
	})
}

// SetHTTPPassword sets the "http_password" field.
func (u *ProxyCredentialUpsertOne) SetHTTPPassword(v string) *ProxyCredentialUpsertOne {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.SetHTTPPassword(v)
	})
}

// UpdateHTTPPassword sets the "http_password" field to the value that was provided on create.
func (u *ProxyCredentialUpsertOne) UpdateHTTPPassword() *ProxyCredentialUpsertOne {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.UpdateHTTPPassword()
	})
}

// SetVlessUUID sets the "vless_uuid" field.
func (u *ProxyCredentialUpsertOne) SetVlessUUID(v string) *ProxyCredentialUpsertOne {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.SetVlessUUID(v)
	})
}

// UpdateVlessUUID sets the "vless_uuid" field to the value that was provided on create.
func (u *ProxyCredentialUpsertOne) UpdateVlessUUID() *ProxyCredentialUpsertOne {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.UpdateVlessUUID()
	})
}

// SetVlessLink sets the "vless_link" field.
func (u *ProxyCredentialUpsertOne) SetVlessLink(v string) *ProxyCredentialUpsertOne {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.SetVlessLink(v)
	})
}

// UpdateVlessLink sets the "vless_link" field to the value that was provided on create.
func (u *ProxyCredentialUpsertOne) UpdateVlessLink() *ProxyCredentialUpsertOne {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.UpdateVlessLink()
	})
}

// Exec executes the query.
func (u *ProxyCredentialUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyCredentialCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyCredentialUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProxyCredentialUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProxyCredentialUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProxyCredentialCreateBulk is the builder for creating many ProxyCredential entities in bulk.
type ProxyCredentialCreateBulk struct {
	config
	err      error
	builders []*ProxyCredentialCreate
	conflict []sql.ConflictOption
}

// Save creates the ProxyCredential entities in the database.
func (_c *ProxyCredentialCreateBulk) Save(ctx context.Context) ([]*ProxyCredential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxyCredential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxyCredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxyCredentialCreateBulk) SaveX(ctx context.Context) []*ProxyCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyCredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyCredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxyCredential.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyCredentialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyCredentialCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProxyCredentialUpsertBulk {
	_c.conflict = opts
	return &ProxyCredentialUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxyCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyCredentialCreateBulk) OnConflictColumns(columns ...string) *ProxyCredentialUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyCredentialUpsertBulk{
		create: _c,
	}
}

// ProxyCredentialUpsertBulk is the builder for "upsert"-ing
// a bulk of ProxyCredential nodes.
type ProxyCredentialUpsertBulk struct {
	create *ProxyCredentialCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProxyCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxyCredentialUpsertBulk) UpdateNewValues() *ProxyCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(proxycredential.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxyCredential.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProxyCredentialUpsertBulk) Ignore() *ProxyCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyCredentialUpsertBulk) DoNothing() *ProxyCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyCredentialCreateBulk.OnConflict
// documentation for more info.
func (u *ProxyCredentialUpsertBulk) Update(set func(*ProxyCredentialUpsert)) *ProxyCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyCredentialUpsertBulk) SetUpdatedAt(v time.Time) *ProxyCredentialUpsertBulk {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyCredentialUpsertBulk) UpdateUpdatedAt() *ProxyCredentialUpsertBulk {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRentalID sets the "rental_id" field.
func (u *ProxyCredentialUpsertBulk) SetRentalID(v int64) *ProxyCredentialUpsertBulk {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.SetRentalID(v)
	})
}

// UpdateRentalID sets the "rental_id" field to the value that was provided on create.
func (u *ProxyCredentialUpsertBulk) UpdateRentalID() *ProxyCredentialUpsertBulk {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.UpdateRentalID()
	})
}

// SetHTTPUsername sets the "http_username" field.
func (u *ProxyCredentialUpsertBulk) SetHTTPUsername(v string) *ProxyCredentialUpsertBulk {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.SetHTTPUsername(v)
	})
}

// UpdateHTTPUsername sets the "http_username" field to the value that was provided on create.
func (u *ProxyCredentialUpsertBulk) UpdateHTTPUsername() *ProxyCredentialUpsertBulk {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.UpdateHTTPUsername()
	})
}

// SetHTTPPassword sets the "http_password" field.
func (u *ProxyCredentialUpsertBulk) SetHTTPPassword(v string) *ProxyCredentialUpsertBulk {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.SetHTTPPassword(v)
	})
}

// UpdateHTTPPassword sets the "http_password" field to the value that was provided on create.
func (u *ProxyCredentialUpsertBulk) UpdateHTTPPassword() *ProxyCredentialUpsertBulk {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.UpdateHTTPPassword()
	})
}

// SetVlessUUID sets the "vless_uuid" field.
func (u *ProxyCredentialUpsertBulk) SetVlessUUID(v string) *ProxyCredentialUpsertBulk {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.SetVlessUUID(v)
	})
}

// UpdateVlessUUID sets the "vless_uuid" field to the value that was provided on create.
func (u *ProxyCredentialUpsertBulk) UpdateVlessUUID() *ProxyCredentialUpsertBulk {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.UpdateVlessUUID()
	})
}

// SetVlessLink sets the "vless_link" field.
func (u *ProxyCredentialUpsertBulk) SetVlessLink(v string) *ProxyCredentialUpsertBulk {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.SetVlessLink(v)
	})
}

// UpdateVlessLink sets the "vless_link" field to the value that was provided on create.
func (u *ProxyCredentialUpsertBulk) UpdateVlessLink() *ProxyCredentialUpsertBulk {
	return u.Update(func(s *ProxyCredentialUpsert) {
		s.UpdateVlessLink()
	})
}

// Exec executes the query.
func (u *ProxyCredentialUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProxyCredentialCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyCredentialCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyCredentialUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
