// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/meitianwang/fast-frame/ent/predicate"
	"github.com/meitianwang/fast-frame/ent/proxyrental"
	"github.com/meitianwang/fast-frame/ent/proxytrafficlog"
	"github.com/meitianwang/fast-frame/ent/user"
)

// ProxyTrafficLogUpdate is the builder for updating ProxyTrafficLog entities.
type ProxyTrafficLogUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyTrafficLogMutation
}

// Where appends a list predicates to the ProxyTrafficLogUpdate builder.
func (_u *ProxyTrafficLogUpdate) Where(ps ...predicate.ProxyTrafficLog) *ProxyTrafficLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyTrafficLogUpdate) SetUpdatedAt(v time.Time) *ProxyTrafficLogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRentalID sets the "rental_id" field.
func (_u *ProxyTrafficLogUpdate) SetRentalID(v int64) *ProxyTrafficLogUpdate {
	_u.mutation.SetRentalID(v)
	return _u
}

// SetNillableRentalID sets the "rental_id" field if the given value is not nil.
func (_u *ProxyTrafficLogUpdate) SetNillableRentalID(v *int64) *ProxyTrafficLogUpdate {
	if v != nil {
		_u.SetRentalID(*v)
	}
	return _u
}

// SetDeltaBytes sets the "delta_bytes" field.
func (_u *ProxyTrafficLogUpdate) SetDeltaBytes(v int64) *ProxyTrafficLogUpdate {
	_u.mutation.ResetDeltaBytes()
	_u.mutation.SetDeltaBytes(v)
	return _u
}

// SetNillableDeltaBytes sets the "delta_bytes" field if the given value is not nil.
func (_u *ProxyTrafficLogUpdate) SetNillableDeltaBytes(v *int64) *ProxyTrafficLogUpdate {
	if v != nil {
		_u.SetDeltaBytes(*v)
	}
	return _u
}

// AddDeltaBytes adds value to the "delta_bytes" field.
func (_u *ProxyTrafficLogUpdate) AddDeltaBytes(v int64) *ProxyTrafficLogUpdate {
	_u.mutation.AddDeltaBytes(v)
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *ProxyTrafficLogUpdate) SetOperatorID(v int64) *ProxyTrafficLogUpdate {
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *ProxyTrafficLogUpdate) SetNillableOperatorID(v *int64) *ProxyTrafficLogUpdate {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *ProxyTrafficLogUpdate) SetNote(v string) *ProxyTrafficLogUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ProxyTrafficLogUpdate) SetNillableNote(v *string) *ProxyTrafficLogUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetRental sets the "rental" edge to the ProxyRental entity.
func (_u *ProxyTrafficLogUpdate) SetRental(v *ProxyRental) *ProxyTrafficLogUpdate {
	return _u.SetRentalID(v.ID)
}

// SetOperator sets the "operator" edge to the User entity.
func (_u *ProxyTrafficLogUpdate) SetOperator(v *User) *ProxyTrafficLogUpdate {
	return _u.SetOperatorID(v.ID)
}

// Mutation returns the ProxyTrafficLogMutation object of the builder.
func (_u *ProxyTrafficLogUpdate) Mutation() *ProxyTrafficLogMutation {
	return _u.mutation
}

// ClearRental clears the "rental" edge to the ProxyRental entity.
func (_u *ProxyTrafficLogUpdate) ClearRental() *ProxyTrafficLogUpdate {
	_u.mutation.ClearRental()
	return _u
}

// ClearOperator clears the "operator" edge to the User entity.
func (_u *ProxyTrafficLogUpdate) ClearOperator() *ProxyTrafficLogUpdate {
	_u.mutation.ClearOperator()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyTrafficLogUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyTrafficLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxyTrafficLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyTrafficLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyTrafficLogUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxytrafficlog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyTrafficLogUpdate) check() error {
	if v, ok := _u.mutation.DeltaBytes(); ok {
		if err := proxytrafficlog.DeltaBytesValidator(v); err != nil {
			return &ValidationError{Name: "delta_bytes", err: fmt.Errorf(`ent: validator failed for field "ProxyTrafficLog.delta_bytes": %w`, err)}
		}
	}
	if _u.mutation.RentalCleared() && len(_u.mutation.RentalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProxyTrafficLog.rental"`)
	}
	if _u.mutation.OperatorCleared() && len(_u.mutation.OperatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProxyTrafficLog.operator"`)
	}
	return nil
}

func (_u *ProxyTrafficLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxytrafficlog.Table, proxytrafficlog.Columns, sqlgraph.NewFieldSpec(proxytrafficlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxytrafficlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeltaBytes(); ok {
		_spec.SetField(proxytrafficlog.FieldDeltaBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeltaBytes(); ok {
		_spec.AddField(proxytrafficlog.FieldDeltaBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(proxytrafficlog.FieldNote, field.TypeString, value)
	}
	if _u.mutation.RentalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxytrafficlog.RentalTable,
			Columns: []string{proxytrafficlog.RentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RentalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxytrafficlog.RentalTable,
			Columns: []string{proxytrafficlog.RentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OperatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxytrafficlog.OperatorTable,
			Columns: []string{proxytrafficlog.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OperatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxytrafficlog.OperatorTable,
			Columns: []string{proxytrafficlog.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxytrafficlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxyTrafficLogUpdateOne is the builder for updating a single ProxyTrafficLog entity.
type ProxyTrafficLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyTrafficLogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyTrafficLogUpdateOne) SetUpdatedAt(v time.Time) *ProxyTrafficLogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRentalID sets the "rental_id" field.
func (_u *ProxyTrafficLogUpdateOne) SetRentalID(v int64) *ProxyTrafficLogUpdateOne {
	_u.mutation.SetRentalID(v)
	return _u
}

// SetNillableRentalID sets the "rental_id" field if the given value is not nil.
func (_u *ProxyTrafficLogUpdateOne) SetNillableRentalID(v *int64) *ProxyTrafficLogUpdateOne {
	if v != nil {
		_u.SetRentalID(*v)
	}
	return _u
}

// SetDeltaBytes sets the "delta_bytes" field.
func (_u *ProxyTrafficLogUpdateOne) SetDeltaBytes(v int64) *ProxyTrafficLogUpdateOne {
	_u.mutation.ResetDeltaBytes()
	_u.mutation.SetDeltaBytes(v)
	return _u
}

// SetNillableDeltaBytes sets the "delta_bytes" field if the given value is not nil.
func (_u *ProxyTrafficLogUpdateOne) SetNillableDeltaBytes(v *int64) *ProxyTrafficLogUpdateOne {
	if v != nil {
		_u.SetDeltaBytes(*v)
	}
	return _u
}

// AddDeltaBytes adds value to the "delta_bytes" field.
func (_u *ProxyTrafficLogUpdateOne) AddDeltaBytes(v int64) *ProxyTrafficLogUpdateOne {
	_u.mutation.AddDeltaBytes(v)
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *ProxyTrafficLogUpdateOne) SetOperatorID(v int64) *ProxyTrafficLogUpdateOne {
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *ProxyTrafficLogUpdateOne) SetNillableOperatorID(v *int64) *ProxyTrafficLogUpdateOne {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *ProxyTrafficLogUpdateOne) SetNote(v string) *ProxyTrafficLogUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ProxyTrafficLogUpdateOne) SetNillableNote(v *string) *ProxyTrafficLogUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetRental sets the "rental" edge to the ProxyRental entity.
func (_u *ProxyTrafficLogUpdateOne) SetRental(v *ProxyRental) *ProxyTrafficLogUpdateOne {
	return _u.SetRentalID(v.ID)
}

// SetOperator sets the "operator" edge to the User entity.
func (_u *ProxyTrafficLogUpdateOne) SetOperator(v *User) *ProxyTrafficLogUpdateOne {
	return _u.SetOperatorID(v.ID)
}

// Mutation returns the ProxyTrafficLogMutation object of the builder.
func (_u *ProxyTrafficLogUpdateOne) Mutation() *ProxyTrafficLogMutation {
	return _u.mutation
}

// ClearRental clears the "rental" edge to the ProxyRental entity.
func (_u *ProxyTrafficLogUpdateOne) ClearRental() *ProxyTrafficLogUpdateOne {
	_u.mutation.ClearRental()
	return _u
}

// ClearOperator clears the "operator" edge to the User entity.
func (_u *ProxyTrafficLogUpdateOne) ClearOperator() *ProxyTrafficLogUpdateOne {
	_u.mutation.ClearOperator()
	return _u
}

// Where appends a list predicates to the ProxyTrafficLogUpdate builder.
func (_u *ProxyTrafficLogUpdateOne) Where(ps ...predicate.ProxyTrafficLog) *ProxyTrafficLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyTrafficLogUpdateOne) Select(field string, fields ...string) *ProxyTrafficLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxyTrafficLog entity.
func (_u *ProxyTrafficLogUpdateOne) Save(ctx context.Context) (*ProxyTrafficLog, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyTrafficLogUpdateOne) SaveX(ctx context.Context) *ProxyTrafficLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxyTrafficLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyTrafficLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyTrafficLogUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxytrafficlog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyTrafficLogUpdateOne) check() error {
	if v, ok := _u.mutation.DeltaBytes(); ok {
		if err := proxytrafficlog.DeltaBytesValidator(v); err != nil {
			return &ValidationError{Name: "delta_bytes", err: fmt.Errorf(`ent: validator failed for field "ProxyTrafficLog.delta_bytes": %w`, err)}
		}
	}
	if _u.mutation.RentalCleared() && len(_u.mutation.RentalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProxyTrafficLog.rental"`)
	}
	if _u.mutation.OperatorCleared() && len(_u.mutation.OperatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProxyTrafficLog.operator"`)
	}
	return nil
}

func (_u *ProxyTrafficLogUpdateOne) sqlSave(ctx context.Context) (_node *ProxyTrafficLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxytrafficlog.Table, proxytrafficlog.Columns, sqlgraph.NewFieldSpec(proxytrafficlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxyTrafficLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxytrafficlog.FieldID)
		for _, f := range fields {
			if !proxytrafficlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxytrafficlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxytrafficlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeltaBytes(); ok {
		_spec.SetField(proxytrafficlog.FieldDeltaBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeltaBytes(); ok {
		_spec.AddField(proxytrafficlog.FieldDeltaBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(proxytrafficlog.FieldNote, field.TypeString, value)
	}
	if _u.mutation.RentalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxytrafficlog.RentalTable,
			Columns: []string{proxytrafficlog.RentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RentalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxytrafficlog.RentalTable,
			Columns: []string{proxytrafficlog.RentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyrental.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OperatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxytrafficlog.OperatorTable,
			Columns: []string{proxytrafficlog.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OperatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxytrafficlog.OperatorTable,
			Columns: []string{proxytrafficlog.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProxyTrafficLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxytrafficlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
