// Code generated by ent, DO NOT EDIT.

package proxyproduct

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/meitianwang/fast-frame/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldDescription, v))
}

// DurationDays applies equality check predicate on the "duration_days" field. It's identical to DurationDaysEQ.
func DurationDays(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldDurationDays, v))
}

// TrafficLimitGB applies equality check predicate on the "traffic_limit_gb" field. It's identical to TrafficLimitGBEQ.
func TrafficLimitGB(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldTrafficLimitGB, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v decimal.Decimal) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldPrice, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldSortOrder, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldContainsFold(FieldDescription, v))
}

// DurationDaysEQ applies the EQ predicate on the "duration_days" field.
func DurationDaysEQ(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldDurationDays, v))
}

// DurationDaysNEQ applies the NEQ predicate on the "duration_days" field.
func DurationDaysNEQ(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNEQ(FieldDurationDays, v))
}

// DurationDaysIn applies the In predicate on the "duration_days" field.
func DurationDaysIn(vs ...int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldIn(FieldDurationDays, vs...))
}

// DurationDaysNotIn applies the NotIn predicate on the "duration_days" field.
func DurationDaysNotIn(vs ...int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNotIn(FieldDurationDays, vs...))
}

// DurationDaysGT applies the GT predicate on the "duration_days" field.
func DurationDaysGT(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGT(FieldDurationDays, v))
}

// DurationDaysGTE applies the GTE predicate on the "duration_days" field.
func DurationDaysGTE(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGTE(FieldDurationDays, v))
}

// DurationDaysLT applies the LT predicate on the "duration_days" field.
func DurationDaysLT(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLT(FieldDurationDays, v))
}

// DurationDaysLTE applies the LTE predicate on the "duration_days" field.
func DurationDaysLTE(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLTE(FieldDurationDays, v))
}

// TrafficLimitGBEQ applies the EQ predicate on the "traffic_limit_gb" field.
func TrafficLimitGBEQ(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldTrafficLimitGB, v))
}

// TrafficLimitGBNEQ applies the NEQ predicate on the "traffic_limit_gb" field.
func TrafficLimitGBNEQ(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNEQ(FieldTrafficLimitGB, v))
}

// TrafficLimitGBIn applies the In predicate on the "traffic_limit_gb" field.
func TrafficLimitGBIn(vs ...int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldIn(FieldTrafficLimitGB, vs...))
}

// TrafficLimitGBNotIn applies the NotIn predicate on the "traffic_limit_gb" field.
func TrafficLimitGBNotIn(vs ...int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNotIn(FieldTrafficLimitGB, vs...))
}

// TrafficLimitGBGT applies the GT predicate on the "traffic_limit_gb" field.
func TrafficLimitGBGT(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGT(FieldTrafficLimitGB, v))
}

// TrafficLimitGBGTE applies the GTE predicate on the "traffic_limit_gb" field.
func TrafficLimitGBGTE(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGTE(FieldTrafficLimitGB, v))
}

// TrafficLimitGBLT applies the LT predicate on the "traffic_limit_gb" field.
func TrafficLimitGBLT(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLT(FieldTrafficLimitGB, v))
}

// TrafficLimitGBLTE applies the LTE predicate on the "traffic_limit_gb" field.
func TrafficLimitGBLTE(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLTE(FieldTrafficLimitGB, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v decimal.Decimal) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v decimal.Decimal) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...decimal.Decimal) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...decimal.Decimal) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v decimal.Decimal) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v decimal.Decimal) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v decimal.Decimal) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v decimal.Decimal) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLTE(FieldPrice, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldLTE(FieldSortOrder, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.FieldNEQ(FieldIsActive, v))
}

// HasRentals applies the HasEdge predicate on the "rentals" edge.
func HasRentals() predicate.ProxyProduct {
	return predicate.ProxyProduct(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RentalsTable, RentalsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRentalsWith applies the HasEdge predicate on the "rentals" edge with a given conditions (other predicates).
func HasRentalsWith(preds ...predicate.ProxyRental) predicate.ProxyProduct {
	return predicate.ProxyProduct(func(s *sql.Selector) {
		step := newRentalsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProxyProduct) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProxyProduct) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProxyProduct) predicate.ProxyProduct {
	return predicate.ProxyProduct(sql.NotPredicates(p))
}
